/-
The theorems of Hashemi.lean as predicates: for every theorem `X` with data binders and
hypotheses, `prop_X (data binders) : Prop := h₁ → h₂ → … → conclusion`, printed back from the
compiled graph, and `prop_X_ok : ∀ data, prop_X data := X` - Lean checks that the printed
statement IS the theorem's. The megakernel evaluates every `prop_X` at the machine's state.
`lake build RequestProject.HashemiPropsGen` writes HashemiProps.lean.
-/
import RequestProject.Hashemi
import RequestProject.Ccc

open Lean Meta Ccc

namespace HashemiPropsGen

def leanDir : String := "/Users/faezs/manifold-pareto/lean/RequestProject"

/-- auto-generated companions of structures and the like, never theorems of the design -/
def autoNames : List String :=
  ["injEq", "sizeOf_spec", "noConfusion", "noConfusionType", "casesOn", "recOn", "rec", "mk",
   "below", "brecOn", "ibelow", "binductionOn", "ext", "ext_iff", "inj", "mk.injEq", "mk.inj"]

def run : MetaM Unit := do
  let env ← getEnv
  let root := `TandoorHashemi
  let mut names : Array Name := #[]
  let mut defNames : Array Name := #[]
  for (n, ci) in env.constants.toList do
    if !(root.isPrefixOf n) then continue
    if n.isInternal || isAutoGenerated n then continue
    if autoNames.contains n.getString! then continue
    if (n.getString!.endsWith "_ok") || (n.getString!.endsWith "_ccc") then continue
    if (n.getString!.startsWith "eq_") then continue          -- auto equation lemmas
    if (← getProjectionFnInfo? n).isSome then continue        -- a structure's fields, Prop ones included
    if ← isInstance n then continue
    match ci with
    | .thmInfo _ => names := names.push n
    | .defnInfo _ =>
      -- the definitions, for the `simp` set that unfolds them in the round-trip proofs
      let ty ← instantiateMVars ci.type
      let isTypeLevel ← forallTelescope ty fun _ b => do pure (b.isSort && !b.isProp)
      if !isTypeLevel then defNames := defNames.push n
    | _ => continue
  let sorted := names.qsort (fun a b => a.toString < b.toString)
  let defsSorted := defNames.qsort (fun a b => a.toString < b.toString)
  -- the simp set of the round trip: every definition of the file, plus what the printer expands -
  -- pair and function equalities into components, `∀ i : Fin n` into a conjunction, `![…] i`
  let simpSet := ", ".intercalate (defsSorted.toList.map fun n => n.toString) ++
    ", TandoorMount.spot, TandoorSphere.sag, TandoorSphere.focal, funext_iff, Prod.ext_iff, " ++
    "Fin.forall_fin_succ, Fin.forall_fin_one, Matrix.cons_val_zero, Matrix.cons_val_succ, " ++
    "Matrix.cons_val, Matrix.head_cons, Matrix.tail_cons, " ++
    "Pi.add_apply, Pi.sub_apply, Pi.neg_apply, Pi.smul_apply, Pi.zero_apply, smul_eq_mul, " ++
    "IsEmpty.forall_iff, and_true"
  let mut out : Array String := #[
    "/- generated by RequestProject/HashemiPropsGen.lean from Hashemi.lean - do not edit.",
    "   Every theorem's statement as a predicate on its data binders (hypotheses as implications),",
    "   each proved by the theorem it came from: the round trip of the theorem compiler. -/",
    "import RequestProject.Hashemi", "", "namespace TandoorHashemi", "open Classical",
    "set_option maxHeartbeats 1000000", "set_option linter.unusedVariables false", ""]
  let mut ok : Array Name := #[]
  let mut skipped : Array (Name × String) := #[]
  for n in sorted do
    match ← compileDef root n with
    | .error msg => skipped := skipped.push (n, msg)
    | .ok f =>
      let full := (n.replacePrefix root .anonymous).toString      -- `Leg.footLong`-style suffixes kept
      let nm := full.replace "." "_"
      let binders := " ".intercalate (f.binders.toList.map fun (b, ty) => s!"({b} : {ty})")
      let dataNames := " ".intercalate (f.binders.toList.map (·.1))
      let body := leanBody f.graph true f.output.flatten f.output "  "
      let hypNames := (List.range f.nHyps).map fun k => s!"_h{k + 1}"
      -- the original theorem applied in its own binder order; each hypothesis is the printed one,
      -- brought to the original's form by the same simp set; the conclusion likewise
      let call := " ".intercalate (f.thmArgs.toList.map fun a =>
        if a.startsWith "_h" then s!"(by simpa only [{simpSet}] using {a})" else a)
      let intro := if f.nHyps == 0 then "" else s!"  refine fun {" ".intercalate hypNames} => ?_\n"
      let proof := s!"  unfold prop_{nm}\n{intro}  have h := @{full} {call}\n  simpa only [{simpSet}] using h"
      out := out.push s!"/-- the statement of `{full}` -/"
      if f.binders.isEmpty then
        out := out.push s!"def prop_{nm} : Prop :=\n{body}"
        out := out.push s!"theorem prop_{nm}_ok : prop_{nm} := by\n{proof}\n"
      else
        out := out.push s!"def prop_{nm} {binders} : Prop :=\n{body}"
        out := out.push s!"theorem prop_{nm}_ok {binders} : prop_{nm} {dataNames} := by\n{proof}\n"
      ok := ok.push n
  out := out.push "end TandoorHashemi"
  IO.FS.writeFile (leanDir ++ "/HashemiProps.lean") ("\n".intercalate out.toList)
  logInfo m!"props: {ok.size} theorems compiled, {skipped.size} skipped"
  for (n, m) in skipped do
    logInfo m!"skipped {n}: {m}"

end HashemiPropsGen

#eval HashemiPropsGen.run
