/-
The driver: compile every definition of `TandoorHashemi` (Hashemi.lean) through `Ccc`, and write
- hashemi_ccc.h      C99 device functions, Props as bool functions, closed theorems as checks
- dot/<name>.dot     the dataflow graph of each definition
- hashemi_ccc.json   the table of what compiled, its shapes, and sample inputs for the parity test
- HashemiCccRound.lean   `theorem f_ccc : f = <round trip> := rfl` for every compiled definition
- HashemiCccFloat.lean   the computable Float twin, with `#eval`s at the sample inputs
`lake build RequestProject.HashemiCcc` runs it (the `#eval` at the end).
-/
import RequestProject.Hashemi
import RequestProject.HashemiStep
import RequestProject.Ccc

open Lean Meta Ccc

namespace HashemiCcc

def outDir : String := "/Users/faezs/ARTIST-compliant/tutorials/hashemi_ccc"
def leanDir : String := "/Users/faezs/manifold-pareto/lean/RequestProject"

/-- a deterministic pseudo-random sample in [0.2, 1.8) from a name and an index -/
def sample (seed : Nat) (k : Nat) : String :=
  let x := (seed * 6364136223846793005 + k * 1442695040888963407 + 1442695040888963407) % 1000000
  let v := 200000 + (x * 16) / 10   -- 0.2 .. 1.8, six decimals
  let vs := toString v
  let ip := String.ofList (vs.toList.take (vs.length - 6))
  (if ip.isEmpty then "0" else ip) ++ "." ++ (String.ofList (vs.toList.drop (vs.length - 6)))

def jsonStr (s : String) : String :=
  "\"" ++ ((s.replace "\\" "\\\\").replace "\"" "\\\"") ++ "\""

def run : MetaM Unit := do
  let env ← getEnv
  let root := `TandoorHashemi
  -- the candidates: user-level constants of the namespace, in a stable order
  let mut names : Array Name := #[]
  for (n, ci) in env.constants.toList do
    if n.getPrefix != root then continue
    if n.isInternal then continue
    match ci with
    | .defnInfo _ | .thmInfo _ => names := names.push n
    | _ => continue
  let sorted := names.qsort (fun a b => a.toString < b.toString)
  let mut funs : Array Fun := #[]
  let mut skipped : Array (Name × String) := #[]
  for n in sorted do
    -- skip projection functions, instances of classes, and type-level definitions
    if (← getProjectionFnInfo? n).isSome then continue
    if ← isInstance n then continue
    let ci ← getConstInfo n
    let ty ← instantiateMVars ci.type
    let isTypeLevel ← forallTelescope ty fun _ b => do pure (b.isSort && !b.isProp)
    if isTypeLevel then continue
    match ← compileDef root n with
    | .ok f => funs := funs.push f
    | .error msg => skipped := skipped.push (n, msg)
  -- ---- the C header
  let mut h : Array String := #[
    "/* generated by RequestProject/Ccc.lean from RequestProject/Hashemi.lean - do not edit.",
    "   Each function is one definition of Hashemi.lean, read as it stands and compiled to a",
    "   hash-consed dataflow graph; the includer sets hk_real and the math macros. */",
    "#ifndef HASHEMI_CCC_H", "#define HASHEMI_CCC_H",
    "#ifndef HK_NO_STD", "#include <math.h>", "#include <stdbool.h>", "#endif",
    "#ifndef HK_STATIC", "#define HK_STATIC static inline", "#endif",
    "#ifndef HK_ADDR", "#define HK_ADDR", "#endif",
    "#ifndef hk_real", "#define hk_real float", "#endif",
    "#ifndef HK_LIT", "#define HK_LIT(x) ((hk_real)(x))", "#endif",
    "#ifndef HK_PI", "#define HK_PI HK_LIT(3.14159265358979323846)", "#endif",
    "#ifndef hk_sqrt", "#define hk_sqrt sqrt", "#define hk_sin sin", "#define hk_cos cos",
    "#define hk_tan tan", "#define hk_atan atan", "#define hk_exp exp", "#define hk_log log",
    "#define hk_fabs fabs", "#define hk_min fmin", "#define hk_max fmax", "#endif",
    "/* `=` on ℝ, in floating point: a relative tolerance, the includer may tighten or loosen it */",
    "#ifndef hk_eq", "#define hk_eq(a, b) (hk_fabs((a) - (b)) <= HK_LIT(1e-9) * hk_max(HK_LIT(1), hk_max(hk_fabs(a), hk_fabs(b))))", "#endif", ""]
  let defs := funs.filter fun f => !f.isTheorem && !f.isProp
  let props := funs.filter fun f => !f.isTheorem && f.isProp
  let thms := funs.filter fun f => f.isTheorem
  h := h.push "/* ---- definitions ---- */"
  for f in defs do h := h.push (printC f) |>.push ""
  h := h.push "/* ---- the requirements (Props), as predicates ---- */"
  for f in props do h := h.push (printC f) |>.push ""
  h := h.push "/* ---- closed theorem statements, as checks (true in exact arithmetic; here in hk_real) ---- */"
  for f in thms do h := h.push (printC { f with name := Name.mkStr f.name.getPrefix ("check_" ++ f.name.getString!) }) |>.push ""
  h := h.push "#endif"
  IO.FS.createDirAll (outDir ++ "/dot")
  IO.FS.writeFile (outDir ++ "/hashemi_ccc.h") ("\n".intercalate h.toList)
  -- ---- dot
  for f in funs do
    IO.FS.writeFile (outDir ++ "/dot/" ++ f.name.getString! ++ ".dot") (printDot f)
  -- ---- samples, the Float twin and the round trip
  let mut json : Array String := #[]
  let mut fl : Array String := #["import Std", "namespace HashemiCccFloat", "set_option maxRecDepth 4000",
    "/-- `=` on ℝ, in floating point -/",
    "def feq (a b : Float) : Bool := Float.abs (a - b) <= 1e-9 * max 1.0 (max (Float.abs a) (Float.abs b))", ""]
  let mut rt : Array String := #["import RequestProject.HashemiStep", "namespace TandoorHashemi",
    "set_option maxHeartbeats 1000000", ""]
  let mut seed := 7
  for f in funs do
    seed := seed + 1
    let nm := f.name.getString!
    let inputs := f.inputs.map (·.1)
    let shape := f.output.shape
    let outN := f.output.flatten.size
    -- samples: three vectors
    let mut svs : Array (Array String) := #[]
    for k in [0:3] do
      let mut sv := #[]
      for j in [0:inputs.size] do
        sv := sv.push (sample (seed * 131 + k) j)
      svs := svs.push sv
    let kind := if f.isTheorem then "theorem" else if f.isProp then "prop" else "def"
    json := json.push ("  {" ++ ", ".intercalate [
      "\"name\": " ++ jsonStr nm,
      "\"c\": " ++ jsonStr (if f.isTheorem then "hk_check_" ++ nm else cName f.name),
      "\"kind\": " ++ jsonStr kind,
      "\"inputs\": [" ++ ", ".intercalate (inputs.toList.map jsonStr) ++ "]",
      "\"shape\": " ++ jsonStr shape,
      "\"n_out\": " ++ toString outN,
      "\"n_nodes\": " ++ toString f.graph.nodes.size,
      "\"samples\": [" ++ ", ".intercalate (svs.toList.map fun sv => "[" ++ ", ".intercalate sv.toList ++ "]") ++ "]"] ++ "}")
    -- the Float twin: flattened Float parameters, the output as Float / Bool / Array Float
    let params := " ".intercalate (inputs.toList.map fun i => s!"({i} : Float)")
    let (retTy, body) := match f.output with
      | Val.s _ => ("Float", leanVal f.graph false f.output)
      | Val.b _ => ("Bool", leanVal f.graph false f.output)
      | v => ("Array Float", "#[" ++ ", ".intercalate (v.flatten.toList.map (leanExpr f.graph false)) ++ "]")
    let fname := if f.isTheorem then "check_" ++ nm else nm
    fl := fl.push s!"def {fname} {params} : {retTy} :=\n  {body}\n"
    for sv in svs do
      let call := if inputs.isEmpty then fname else fname ++ " " ++ " ".intercalate sv.toList
      let shown := match f.output with
        | Val.s _ => s!"toString ({call}).toBits"
        | Val.b _ => s!"toString ({call})"
        | _ => s!"toString (({call}).map Float.toBits)"
      fl := fl.push s!"#eval IO.println (\"{fname} \" ++ {shown})"
    fl := fl.push ""
    -- the round trip, for definitions with a value shape the ℝ printer can write
    if !f.isTheorem then
      match f.output with
      | .struct .. => pure ()
      | _ => rt := rt.push (printRoundTrip f) |>.push ""
  fl := fl.push "end HashemiCccFloat"
  rt := rt.push "end TandoorHashemi"
  IO.FS.writeFile (leanDir ++ "/HashemiCccFloat.lean") ("\n".intercalate fl.toList)
  -- the NumPy twin
  let mut py : Array String := #["# generated by RequestProject/Ccc.lean from Hashemi.lean - do not edit.",
    "# The same graphs as hashemi_ccc.h, printed for NumPy: the env-side reference twin, vectorised over agents.",
    "import numpy as np", "",
    "def hk_eq(a, b):", "    \"\"\"`=` on ℝ, in floating point\"\"\"",
    "    return np.abs(a - b) <= 1e-9 * np.maximum(1.0, np.maximum(np.abs(a), np.abs(b)))", ""]
  for f in funs do
    let fname := if f.isTheorem then "hk_check_" ++ f.name.getString! else cName f.name
    py := py.push (printNumpy f fname) |>.push ""
  IO.FS.writeFile (outDir ++ "/hashemi_ccc.py") ("\n".intercalate py.toList)
  IO.FS.writeFile (leanDir ++ "/HashemiCccRound.lean") ("\n".intercalate rt.toList)
  let skippedJson := skipped.toList.map fun (n, m) => "  {\"name\": " ++ jsonStr n.getString! ++ ", \"reason\": " ++ jsonStr m ++ "}"
  IO.FS.writeFile (outDir ++ "/hashemi_ccc.json")
    ("{\n\"functions\": [\n" ++ ",\n".intercalate json.toList ++ "\n],\n\"skipped\": [\n" ++
     ",\n".intercalate skippedJson ++ "\n]\n}\n")
  logInfo m!"compiled {funs.size} ({defs.size} definitions, {props.size} props, {thms.size} theorem checks); skipped {skipped.size}"
  for (n, m) in skipped do
    logInfo m!"skipped {n}: {m}"

end HashemiCcc

#eval HashemiCcc.run
