/-
The renderer's driver: compile `HashemiScene.lean`'s two definitions through `Ccc` and write

- `render/hashemi_scene.h`   the C twin of `sceneSegments` and `raySegment` (`hk_sceneSegments`,
  `hk_raySegment`), with the same preamble as `hashemi_ccc.h` so a program may include both;
- `render/hashemi_scene.json`  the row groups (`sceneGroups`), the binder order of each function,
  and the shapes - what `render/main.c` fills the arguments from.

This is a SEPARATE driver from `HashemiCcc.lean`: it touches none of that file's outputs and adds
no target to the lakefile.  `lake build RequestProject.HashemiRenderCcc` runs it (the `#eval`
below), exactly as `lake build RequestProject.HashemiCcc` runs the other one.

Nothing here writes geometry: the header is printed from the Lean definitions, which are written
from the spec's own points.  The renderer therefore cannot drift from the spec - it can only fail
to rebuild.
-/
import RequestProject.HashemiScene
import RequestProject.Ccc

open Lean Meta Ccc

namespace HashemiRenderCcc

def outDir : String := "/Users/faezs/ARTIST-compliant/tutorials/hashemi_ccc/render"

def jsonStr (s : String) : String :=
  let t := ((s.replace "\\" "\\\\").replace "\"" "\\\"")
  "\"" ++ ((t.replace "\n" " ").replace "\t" " ") ++ "\""

/-- the string literals of an array literal expression, in order (as `HashemiCcc.strLits`) -/
partial def strLits (e : Expr) : Array String :=
  match e with
  | .mdata _ e => strLits e
  | .lit (.strVal s) => #[s]
  | .letE _ _ v b _ => strLits (b.instantiate1 v)
  | e =>
    let f := e.getAppFn
    let args := e.getAppArgs
    if f.isConstOf ``List.toArray && args.size == 2 then strLits args[1]!
    else if f.isConstOf ``List.cons && args.size == 3 then strLits args[1]! ++ strLits args[2]!
    else if f.isConstOf ``List.nil then #[]
    else args.foldl (fun acc a => acc ++ strLits a) #[]

/-- the header's preamble, the same macros `hashemi_ccc.h` opens with (and guarded, so a
translation unit may include both headers) -/
def preamble : Array String := #[
  "/* generated by RequestProject/HashemiRenderCcc.lean from RequestProject/HashemiScene.lean -",
  "   do not edit.  Each function is one definition of the scene, itself written from the points",
  "   Hashemi.lean names; the includer sets hk_real and the math macros. */",
  "#ifndef HASHEMI_SCENE_H", "#define HASHEMI_SCENE_H",
  "#ifndef HK_NO_STD", "#include <math.h>", "#include <stdbool.h>", "#endif",
  "#ifndef HK_STATIC", "#define HK_STATIC static inline", "#endif",
  "#ifndef HK_ADDR", "#define HK_ADDR", "#endif",
  "#ifndef hk_real", "#define hk_real float", "#endif",
  "#ifndef HK_LIT", "#define HK_LIT(x) ((hk_real)(x))", "#endif",
  "#ifndef HK_PI", "#define HK_PI HK_LIT(3.14159265358979323846)", "#endif",
  "#ifndef hk_sqrt", "#define hk_sqrt sqrt", "#define hk_sin sin", "#define hk_cos cos",
  "#define hk_tan tan", "#define hk_atan atan", "#define hk_acos acos", "#define hk_asin asin",
  "#define hk_exp exp", "#define hk_log log",
  "#define hk_fabs fabs", "#define hk_floor floor", "#define hk_tanh tanh",
  "#define hk_min fmin", "#define hk_max fmax", "#endif",
  "#ifndef hk_eq",
  "#define hk_eq(a, b) (hk_fabs((a) - (b)) <= HK_LIT(1e-9) * hk_max(HK_LIT(1), hk_max(hk_fabs(a), hk_fabs(b))))",
  "#endif",
  "#ifndef hk_sigmoid", "#define hk_sigmoid(x) (HK_LIT(1) / (HK_LIT(1) + hk_exp(-(x))))", "#endif",
  "#ifndef HK_RADDR", "#define HK_RADDR", "#endif", ""]

/-- the scene's definitions, in the order the header prints them -/
def sceneDefs : List String := ["roofPt", "dishPt", "seg", "sceneSegments", "raySegment"]

def run : MetaM Unit := do
  let root := `TandoorHashemi
  let mut funs : Array Fun := #[]
  let mut failed : Array (String × String) := #[]
  for nm in sceneDefs do
    match ← compileDef root (root ++ nm.toName) with
    | .ok f =>
      funs := funs.push f
      logInfo m!"{nm}: {f.graph.nodes.size} nodes, {f.output.flatten.size} outputs, {f.inputs.size} inputs"
    | .error msg => failed := failed.push (nm, msg); logInfo m!"{nm} did not compile: {msg}"
  let mut h := preamble
  for f in funs do h := h.push (printC f) |>.push ""
  h := h.push "#endif"
  IO.FS.createDirAll outDir
  IO.FS.writeFile (outDir ++ "/hashemi_scene.h") ("\n".intercalate h.toList)
  -- the manifest: the row groups and each function's binder order
  let groupsE ← instantiateMVars ((← getConstInfo (root ++ `sceneGroups)).value?.getD (mkConst `none))
  let groups := strLits groupsE
  let fj := funs.toList.map fun f =>
    "  {" ++ ", ".intercalate [
      "\"name\": " ++ jsonStr f.name.getString!,
      "\"c\": " ++ jsonStr (cName f.name),
      "\"inputs\": [" ++ ", ".intercalate ((f.inputs.map (·.1)).toList.map jsonStr) ++ "]",
      "\"n_in\": " ++ toString f.inputs.size,
      "\"n_out\": " ++ toString f.output.flatten.size,
      "\"shape\": " ++ jsonStr f.output.shape,
      "\"n_nodes\": " ++ toString f.graph.nodes.size] ++ "}"
  IO.FS.writeFile (outDir ++ "/hashemi_scene.json")
    ("{\n\"source\": \"RequestProject/HashemiScene.lean, through Ccc.lean\",\n" ++
     "\"columns\": [\"x0\", \"y0\", \"z0\", \"x1\", \"y1\", \"z1\", \"colour\"],\n" ++
     "\"rows\": " ++ toString groups.size ++ ",\n" ++
     "\"groups\": [" ++ ", ".intercalate (groups.toList.map jsonStr) ++ "],\n" ++
     "\"functions\": [\n" ++ ",\n".intercalate fj ++ "\n]\n}\n")
  logInfo m!"scene: {funs.size} functions, {groups.size} rows; {failed.size} failed"

end HashemiRenderCcc

#eval HashemiRenderCcc.run
