/-
The driver: compile every definition of `TandoorHashemi` (Hashemi.lean) through `Ccc`, and write
- hashemi_ccc.h      C99 device functions, Props as bool functions, closed theorems as checks
- dot/<name>.dot     the dataflow graph of each definition
- hashemi_ccc.json   the table of what compiled, its shapes, and sample inputs for the parity test
- HashemiCccRound.lean   `theorem f_ccc : f = <round trip> := rfl` for every compiled definition
- HashemiCccFloat.lean   the computable Float twin, with `#eval`s at the sample inputs
- hashemi_mega.json      the megakernel's column names (`megaNames`) and its input order
Theorems with binders compile to property functions (their hypotheses as implications);
their round trip is HashemiProps.lean (`prop_X_ok`), written by HashemiPropsGen.
`lake build RequestProject.HashemiCcc` runs it (the `#eval` at the end).
-/
import RequestProject.Hashemi
import RequestProject.HashemiStep
import RequestProject.HashemiProps
import RequestProject.HashemiMega
import RequestProject.HashemiTrace
import RequestProject.HashemiTraceProps
import RequestProject.Ccc

open Lean Meta Ccc

namespace HashemiCcc

def outDir : String := "/Users/faezs/ARTIST-compliant/tutorials/hashemi_ccc"
def leanDir : String := "/Users/faezs/manifold-pareto/lean/RequestProject"

/-- a deterministic pseudo-random sample in [0.2, 1.8) from a name and an index -/
def sample (seed : Nat) (k : Nat) : String :=
  let x := (seed * 6364136223846793005 + k * 1442695040888963407 + 1442695040888963407) % 1000000
  let v := 200000 + (x * 16) / 10   -- 0.2 .. 1.8, six decimals
  let vs := toString v
  let ip := String.ofList (vs.toList.take (vs.length - 6))
  (if ip.isEmpty then "0" else ip) ++ "." ++ (String.ofList (vs.toList.drop (vs.length - 6)))

def jsonStr (s : String) : String :=
  "\"" ++ ((s.replace "\\" "\\\\").replace "\"" "\\\"") ++ "\""

/-- the string literals of an array/list literal expression, in order -/
partial def strLits (e : Expr) : Array String :=
  match e with
  | .mdata _ e => strLits e
  | .lit (.strVal s) => #[s]
  | .letE _ _ v b _ => strLits (b.instantiate1 v)     -- long list literals elaborate in `let` chunks
  | e =>
    let f := e.getAppFn
    let args := e.getAppArgs
    if f.isConstOf ``List.toArray && args.size == 2 then strLits args[1]!
    else if f.isConstOf ``List.cons && args.size == 3 then strLits args[1]! ++ strLits args[2]!
    else if f.isConstOf ``List.nil then #[]
    else args.foldl (fun acc a => acc ++ strLits a) #[]

def run : MetaM Unit := do
  let env ← getEnv
  let root := `TandoorHashemi
  -- the candidates: user-level constants of the namespace, in a stable order
  let mut names : Array Name := #[]
  let notCompiled : List String := ["b2r", "megaNames", "megaNames_size"]
  for (n, ci) in env.constants.toList do
    if !(root.isPrefixOf n) then continue
    if n.isInternal || isAutoGenerated n then continue
    let last := n.getString!
    if last.startsWith "eq_" || last.endsWith "_ok" || last.endsWith "_ccc" then continue
    if ["injEq", "sizeOf_spec", "noConfusion", "noConfusionType", "casesOn", "recOn", "rec", "mk",
        "below", "brecOn", "ibelow", "binductionOn", "ext", "ext_iff", "inj"].contains last then continue
    if notCompiled.contains last then continue
    match ci with
    | .defnInfo _ | .thmInfo _ => names := names.push n
    | _ => continue
  let sorted := names.qsort (fun a b => a.toString < b.toString)
  let mut funs : Array Fun := #[]
  let mut skipped : Array (Name × String) := #[]
  for n in sorted do
    -- skip projection functions, instances of classes, and type-level definitions
    if (← getProjectionFnInfo? n).isSome then continue
    if ← isInstance n then continue
    let ci ← getConstInfo n
    let ty ← instantiateMVars ci.type
    let isTypeLevel ← forallTelescope ty fun _ b => do pure (b.isSort && !b.isProp)
    if isTypeLevel then continue
    match ← compileDef root n with
    | .ok f => funs := funs.push f
    | .error msg => skipped := skipped.push (n, msg)
  -- ---- the C header
  let mut h : Array String := #[
    "/* generated by RequestProject/Ccc.lean from RequestProject/Hashemi.lean - do not edit.",
    "   Each function is one definition of Hashemi.lean, read as it stands and compiled to a",
    "   hash-consed dataflow graph; the includer sets hk_real and the math macros. */",
    "#ifndef HASHEMI_CCC_H", "#define HASHEMI_CCC_H",
    "#ifndef HK_NO_STD", "#include <math.h>", "#include <stdbool.h>", "#endif",
    "#ifndef HK_STATIC", "#define HK_STATIC static inline", "#endif",
    "#ifndef HK_ADDR", "#define HK_ADDR", "#endif",
    "#ifndef hk_real", "#define hk_real float", "#endif",
    "#ifndef HK_LIT", "#define HK_LIT(x) ((hk_real)(x))", "#endif",
    "#ifndef HK_PI", "#define HK_PI HK_LIT(3.14159265358979323846)", "#endif",
    "#ifndef hk_sqrt", "#define hk_sqrt sqrt", "#define hk_sin sin", "#define hk_cos cos",
    "#define hk_tan tan", "#define hk_atan atan", "#define hk_acos acos", "#define hk_asin asin",
    "#define hk_exp exp", "#define hk_log log",
    "#define hk_fabs fabs", "#define hk_min fmin", "#define hk_max fmax", "#endif",
    "/* `=` on ℝ, in floating point: a relative tolerance, the includer may tighten or loosen it */",
    "#ifndef hk_eq", "#define hk_eq(a, b) (hk_fabs((a) - (b)) <= HK_LIT(1e-9) * hk_max(HK_LIT(1), hk_max(hk_fabs(a), hk_fabs(b))))", "#endif", ""]
  let defs := funs.filter fun f => !f.isTheorem && !f.isProp
  let props := funs.filter fun f => !f.isTheorem && f.isProp
  let thms := funs.filter fun f => f.isTheorem
  h := h.push "/* ---- definitions ---- */"
  for f in defs do h := h.push (printC f) |>.push ""
  h := h.push "/* ---- the requirements (Props), as predicates ---- */"
  for f in props do h := h.push (printC f) |>.push ""
  h := h.push "/* ---- theorem statements, as checks: hypotheses -> conclusion, true in exact arithmetic (here in hk_real) ---- */"
  for f in thms do h := h.push (printC { f with name := Name.mkStr f.name.getPrefix ("check_" ++ f.name.getString!) }) |>.push ""
  h := h.push "#endif"
  IO.FS.createDirAll (outDir ++ "/dot")
  IO.FS.writeFile (outDir ++ "/hashemi_ccc.h") ("\n".intercalate h.toList)
  -- ---- dot
  for f in funs do
    IO.FS.writeFile (outDir ++ "/dot/" ++ f.name.getString! ++ ".dot") (printDot f)
  -- ---- samples, the Float twin and the round trip
  let mut json : Array String := #[]
  let mut fl : Array String := #["import Std", "namespace HashemiCccFloat", "set_option maxRecDepth 4000",
    "/-- `=` on ℝ, in floating point -/",
    "def feq (a b : Float) : Bool := Float.abs (a - b) <= 1e-9 * max 1.0 (max (Float.abs a) (Float.abs b))", ""]
  -- the round trip names every compiled definition, so it imports the top module of the chain
  let mut rt : Array String := #["import RequestProject.HashemiTraceProps", "namespace TandoorHashemi",
    "open Classical", "set_option maxHeartbeats 4000000", "set_option maxRecDepth 8000", ""]
  let mut seed := 7
  for f in funs do
    seed := seed + 1
    let nm := ((f.name.replacePrefix root .anonymous).toString).replace "." "_"
    let inputs := f.inputs.map (·.1)
    let shape := f.output.shape
    let outN := f.output.flatten.size
    -- samples: three vectors
    let mut svs : Array (Array String) := #[]
    for k in [0:3] do
      let mut sv := #[]
      for j in [0:inputs.size] do
        sv := sv.push (sample (seed * 131 + k) j)
      svs := svs.push sv
    let kind := if f.isTheorem then "theorem" else if f.isProp then "prop" else "def"
    json := json.push ("  {" ++ ", ".intercalate [
      "\"name\": " ++ jsonStr nm,
      "\"c\": " ++ jsonStr (if f.isTheorem then "hk_check_" ++ nm else cName f.name),
      "\"kind\": " ++ jsonStr kind,
      "\"inputs\": [" ++ ", ".intercalate (inputs.toList.map jsonStr) ++ "]",
      "\"shape\": " ++ jsonStr shape,
      "\"n_out\": " ++ toString outN,
      "\"n_nodes\": " ++ toString f.graph.nodes.size,
      "\"n_hyps\": " ++ toString f.nHyps,
      "\"samples\": [" ++ ", ".intercalate (svs.toList.map fun sv => "[" ++ ", ".intercalate sv.toList ++ "]") ++ "]"] ++ "}")
    -- the Float twin: flattened Float parameters, the output as Float / Bool / Array Float
    let params := " ".intercalate (inputs.toList.map fun i => s!"({i} : Float)")
    -- printed with `let`s for shared nodes (leanBody): the inline printer is exponential on the mega graphs
    let outs := f.output.flatten
    let (retTy, body) := match f.output with
      | Val.s _ => ("Float", leanBody f.graph false outs f.output "  ")
      | Val.b _ => ("Bool", leanBody f.graph false outs f.output "  ")
      | v => ("Array Float", leanBody f.graph false outs (Val.vec (v.flatten.map Val.s)) "  ")
    let fname := if f.isTheorem then "check_" ++ nm else nm
    let body := if retTy == "Array Float" then body.replace "![" "#[" else body
    fl := fl.push s!"def {fname} {params} : {retTy} :=\n{body}\n"
    for sv in svs do
      let call := if inputs.isEmpty then fname else fname ++ " " ++ " ".intercalate sv.toList
      let shown := match f.output with
        | Val.s _ => s!"toString ({call}).toBits"
        | Val.b _ => s!"toString ({call})"
        | _ => s!"toString (({call}).map Float.toBits)"
      fl := fl.push s!"#eval IO.println (\"{fname} \" ++ {shown})"
    fl := fl.push ""
    -- the round trip, for definitions with a value shape the ℝ printer can write (theorems: HashemiProps)
    if !f.isTheorem then
      match f.output with
      | .struct .. => pure ()
      | _ =>
        let ref := (f.name.replacePrefix root .anonymous).toString
        -- the 24-fold bisection (`swingOfLength`, and `step`/`megaStep` through it): its `rfl` is a
        -- defeq check on a term that doubles at every level, beyond any heartbeat budget. The step
        -- itself, `bisectStep`, round-trips; the iterate rule is checked on a 3-fold instance below;
        -- the C and Float twins agree on these three at the samples
        if ["swingOfLength", "step", "megaStep"].contains ref then
          rt := rt.push s!"-- {ref}: round trip by the twins (the 24-fold bisection is beyond rfl's budget)" |>.push ""
        else
          rt := rt.push (printRoundTrip f ref (ref.replace "." "_")) |>.push ""
  fl := fl.push "end HashemiCccFloat"
  rt := rt.push "/-- the translator unrolls `f^[n]` into `n` applications: the rule, on a 3-fold instance of the bisection -/"
  rt := rt.push "theorem bisect3_unroll (ym hp a ze L : ℝ) (s : ℝ × ℝ) :"
  rt := rt.push "    (bisectStep ym hp a ze L)^[3] s = bisectStep ym hp a ze L (bisectStep ym hp a ze L (bisectStep ym hp a ze L s)) := rfl"
  rt := rt.push ""
  rt := rt.push "end TandoorHashemi"
  IO.FS.writeFile (leanDir ++ "/HashemiCccFloat.lean") ("\n".intercalate fl.toList)
  -- the NumPy twin
  let mut py : Array String := #["# generated by RequestProject/Ccc.lean from Hashemi.lean - do not edit.",
    "# The same graphs as hashemi_ccc.h, printed for NumPy: the env-side reference twin, vectorised over agents.",
    "import numpy as np", "",
    "def hk_eq(a, b):", "    \"\"\"`=` on ℝ, in floating point\"\"\"",
    "    return np.abs(a - b) <= 1e-9 * np.maximum(1.0, np.maximum(np.abs(a), np.abs(b)))", ""]
  for f in funs do
    let fname := if f.isTheorem then "hk_check_" ++ f.name.getString! else cName f.name
    py := py.push (printNumpy f fname) |>.push ""
  IO.FS.writeFile (outDir ++ "/hashemi_ccc.py") ("\n".intercalate py.toList)
  IO.FS.writeFile (leanDir ++ "/HashemiCccRound.lean") ("\n".intercalate rt.toList)
  -- the megakernel's manifest: column names from `megaNames` (a literal array of strings), the
  -- six functions in order, and the shared input order
  let namesE ← instantiateMVars ((← getConstInfo (root ++ `megaNames)).value?.getD (mkConst `none))
  let cols := strLits namesE
  let megaFns := ["megaStep", "megaGeom", "megaScrew", "megaReqs", "megaThmsClosed", "megaThmsState"]
  let mut megaJson : Array String := #[]
  let mut off := 0
  let mut megaInputs : Array String := #[]
  for mf in megaFns do
    match funs.find? (fun f => f.name.getString! == mf) with
    | some f =>
      let n := f.output.flatten.size
      megaJson := megaJson.push ("  {\"name\": " ++ jsonStr mf ++ ", \"c\": " ++ jsonStr (cName f.name) ++
        ", \"offset\": " ++ toString off ++ ", \"n_out\": " ++ toString n ++ "}")
      off := off + n
      if megaInputs.isEmpty then megaInputs := f.inputs.map (·.1)
    | none => logInfo m!"mega function {mf} did not compile"
  IO.FS.writeFile (outDir ++ "/hashemi_mega.json")
    ("{\n\"columns\": [" ++ ", ".intercalate (cols.toList.map jsonStr) ++ "],\n\"inputs\": [" ++
     ", ".intercalate (megaInputs.toList.map jsonStr) ++ "],\n\"functions\": [\n" ++
     ",\n".intercalate megaJson.toList ++ "\n],\n\"n_columns\": " ++ toString off ++ "\n}\n")
  logInfo m!"mega: {off} columns in the kernel, {cols.size} names"
  let skippedJson := skipped.toList.map fun (n, m) => "  {\"name\": " ++ jsonStr n.getString! ++ ", \"reason\": " ++ jsonStr m ++ "}"
  IO.FS.writeFile (outDir ++ "/hashemi_ccc.json")
    ("{\n\"functions\": [\n" ++ ",\n".intercalate json.toList ++ "\n],\n\"skipped\": [\n" ++
     ",\n".intercalate skippedJson ++ "\n]\n}\n")
  logInfo m!"compiled {funs.size} ({defs.size} definitions, {props.size} props, {thms.size} theorem checks); skipped {skipped.size}"
  for (n, m) in skipped do
    logInfo m!"skipped {n}: {m}"

end HashemiCcc

#eval HashemiCcc.run
