/-
# The emit driver

`lake build RequestProject.SceneCcc` runs the `#eval` at the bottom and writes, into
`tutorials/hashemi_ccc/render/`:

* `scene_hashemi.h/.py/.json`, `scene_beam.h/.py/.json`, `scene_optic.h/.py/.json` — three scenes
  through ONE printer (`CccScene.lean`), which has no knowledge of any of them;
* `scene_registry.h` — the three as a table, so `main.c` picks one with `--scene`;
* `scene_sun.h/.py` — `sunAt`, printed on its own so the headless check can measure it against
  the trainer's `solar_position`.

There is no geometry in this file either: it names three lists of data and a printer.
-/
import RequestProject.CccScene
import RequestProject.HashemiSceneInst

open Lean Meta Ccc CccScene

namespace SceneCcc

def outDir : String := "/Users/faezs/ARTIST-compliant/tutorials/hashemi_ccc/render"

def run : MetaM Unit := do
  let root := `TandoorHashemi
  let mut rows : List String := []
  let mut names : List String := []
  for (nm, sceneName, src, sc) in [
      (`sceneHashemi, "hashemi",
        "RequestProject/HashemiSceneInst.lean, hashemiScene — Hashemi.lean, HashemiMega.lean, HashemiTrace.lean",
        HashemiSceneInst.hashemiScene),
      (`sceneBeam, "beam",
        "RequestProject/HashemiSceneInst.lean, beamScene — HashemiBeamdown.lean",
        HashemiSceneInst.beamScene),
      (`sceneOptic, "optic",
        "RequestProject/HashemiSceneInst.lean, opticScene — OpticGadt.lean's hashemiBeam chain, stage by stage",
        HashemiSceneInst.opticScene)] do
    match ← emitScene outDir root nm sceneName src sc with
    | some row => rows := rows ++ [row]; names := names ++ [sceneName]
    | none => pure ()
  IO.FS.writeFile (outDir ++ "/scene_registry.h") (registryHeader names rows)
  -- the sun, on its own: the headless check measures it against the trainer's solar_position
  match ← compileDef root (root ++ `sunAt) with
  | .ok f =>
    -- printed under its own name, so a translation unit may hold this header and the
    -- machine's own hashemi_ccc.h (which prints every TandoorHashemi definition) at once
    let f := { f with name := `sceneSunAt }
    let h := (preamble "SCENE_SUN_H").push (printC f) |>.push "#endif"
    IO.FS.writeFile (outDir ++ "/scene_sun.h") ("\n".intercalate h.toList)
    IO.FS.writeFile (outDir ++ "/scene_sun.py") ("\n".intercalate [
      "# generated by RequestProject/SceneCcc.lean - do not edit.",
      "import numpy as np", "",
      "def hk_eq(a, b):",
      "    return np.abs(a - b) <= 1e-9 * np.maximum(1.0, np.maximum(np.abs(a), np.abs(b)))", "",
      printNumpy f (cName f.name), ""])
    logInfo m!"sunAt: {f.graph.nodes.size} nodes, {f.inputs.size} inputs"
  | .error msg => logInfo m!"sunAt did not compile: {msg}"
  logInfo m!"scenes written: {names}"

end SceneCcc

#eval SceneCcc.run
