# generated by RequestProject/Ccc.lean (HashemiCcc.lean) from HashemiPolicy.lean - do not edit.
"""The policy interface of his machine, as the spec states it: one mirror, two motors.

The observation Box takes its bounds from `obsLo` / `obsHi` (Lean, through the NumPy twin), the
command Box is `[-1, 1]` per motor (`mlpPolicy_bounded`, `follower_bounded`), the heads are the
seven levels of `headToCmd`, and `heads_to_commands` / `commands_to_drives` are the compiled
`headToCmd`, `driveAz`, `driveEl` themselves."""
import os, sys
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hashemi_ccc as _H
try:
    from gymnasium import spaces as _spaces
except ImportError:                       # pragma: no cover
    from gym import spaces as _spaces

OBS_NAMES = ["e_az", "e_el", "swing", "taut", "holds", "oil", "reach_s", "lost_s", "margin", "flow", "deg"]
ACTION_NAMES = ["u_az", "u_el", "u_pump"]
ACTION_LEVELS = 7
MOTOR_HEADS = [3, 4]                      # the parent tandoor env's azimuth and elevation heads
N_OBS, N_ACT = len(OBS_NAMES), len(ACTION_NAMES)
OBS_LO = np.asarray(_H.hk_obsLo(), dtype=np.float32).reshape(N_OBS)
OBS_HI = np.asarray(_H.hk_obsHi(), dtype=np.float32).reshape(N_OBS)
AZ_FULL, EL_FULL = float(_H.hk_azFull()), float(_H.hk_elFull())     # rad/s of the dish at full command


def observation_space():
    """the machine's eight observations, bounded by the spec"""
    return _spaces.Box(low=OBS_LO, high=OBS_HI, shape=(N_OBS,), dtype=np.float32)


def action_space():
    """the two commands in [-1, 1]: the roller and the winch at a fraction of full command"""
    return _spaces.Box(low=-1.0, high=1.0, shape=(N_ACT,), dtype=np.float32)


def action_space_heads():
    """the same interface through seven-level heads (the parent trainer's kind)"""
    return _spaces.MultiDiscrete([ACTION_LEVELS] * N_ACT)


def heads_to_commands(heads):
    """`headToCmd`: (B, 2) head values 0..6 -> commands in [-1, 1]"""
    h = np.asarray(heads, dtype=np.float64)
    return np.stack([np.asarray(_H.hk_headToCmd(h[..., k]), dtype=np.float64) for k in range(N_ACT)], axis=-1)


def commands_to_drives(u, arm, rw=0.05, R=1.2192, rDrum=0.03):
    """`driveAz`, `driveEl`: commands (B, 2) -> (omega_m, omega_d) at the wire's lever arm `arm`"""
    u = np.asarray(u, dtype=np.float64); B = u.shape[0]
    om = np.asarray(_H.hk_driveAz(u[:, 0], np.full(B, rw), np.full(B, R)), dtype=np.float64)
    od = np.asarray(_H.hk_driveEl(u[:, 1], np.asarray(arm, dtype=np.float64), np.full(B, rDrum)), dtype=np.float64)
    return np.stack([om, od], axis=-1)
