// generated by RequestProject/Ccc.lean (HashemiCcc.lean) from HashemiReward.lean - do not edit.
// ONE kernel for the trainer's reward: buffer 0 the inputs (B, n_in), buffer 1 the outputs (B, 3),
// buffer 2 the count; dispatch B threads in groups of 1.
kernel void hashemi_reward(device const float* hk_x [[buffer(0)]], device float* hk_y [[buffer(1)]], device const int* hk_n [[buffer(2)]], uint hk_b [[threadgroup_position_in_grid]], uint hk_i [[thread_position_in_threadgroup]]) {
  if ((int)hk_b >= hk_n[0]) return;
  device const float* hk_xb = hk_x + hk_b * 8;
  const hk_real t0 = hk_xb[0];
  const hk_real t1 = hk_xb[1];
  const hk_real t2 = hk_xb[2];
  const hk_real t3 = hk_xb[3];
  const hk_real t4 = hk_xb[4];
  const hk_real t5 = hk_xb[5];
  const hk_real t6 = hk_xb[6];
  const hk_real t7 = hk_xb[7];
  const hk_real t8 = (t5 * t6);
  const hk_real t9 = (t8 * t1);
  const hk_real t10 = (t9 / t7);
  const hk_real t11 = (t10 * t2);
  const hk_real t12 = (t11 * t3);
  const hk_real t13 = (t0 + t12);
  const hk_real t14 = (t13 / t4);
  if (hk_i == 0) {
    hk_y[hk_b * 3 + 0] = t12;
    hk_y[hk_b * 3 + 1] = t13;
    hk_y[hk_b * 3 + 2] = t14;
  }
}
