"""THE HAND-WRITTEN HALF of `puffer_hashemi_ccc`, and the only one.

`hashemi_tandoor_ccc.py` beside this file is GENERATED by RequestProject/HashemiCcc.lean from the
kernels' own manifests: the input row, the column gathers, the state write-back, the reward
composition, the spaces, the machine-JSON load and the scene map, once for both paths.  This file
is what a manifest of Hashemi.lean cannot say, and every line of it is the PARENT tandoor env's
contract or the device plumbing under it:

  * SUBCLASSING `tandoor_hashemi_env.TandoorHashemiEnv` and its ini kwargs.  The parent's pot,
    wall chain, bread, guillotine, observations and reward are what puffer scores; its keyword
    arguments, its head layout (`N_HEADS`, the shutter, the jam, the load heads), its `reward_div`
    and `roti_energy` are its own and change when it changes.  No spec declares them.
  * THE PARENT'S HOOKS: `_trace_power` (its NumPy step), `_fused_power` (its Metal step, called
    from `tandoor_fused_step` after `step_pre`), `_gpu_full_step`, `step`, `reset`,
    `el_dish_deg` / `el_dish_t`.  Their names, their signatures and WHEN they are called are the
    parent's; their bodies are three lines each into the generated module.
  * THE NEUTRALISED HEADS.  His dish has no membrane, so the parent's level head is the pump's
    and its two motor heads are the machine's: the parent must be stepped with the rest held.
    Which head is which is the parent's layout.
  * THE RESYNC.  The parent re-parks a cut agent's motors and every agent's at day over; the
    machine's state follows its motors there.  The guillotine is the parent's device.
  * THE DEVICE PLUMBING: torch tensors on mps, the parent's generator for the ray table, the
    host mirrors its readers expect, the pufferlib contract (RuntimeWarnings are errors).
  * THE RENDER WINDOW: opening it, the HUD's text, writing SVGs.  The scene's own input row is
    the generated module's `scene_map`; this is the window around it.
  * THE OPTIONAL COBOUNDARY `_pb_raw`: potential-based pointing shaping, `k (phi - phi_prev)`.
    It is not part of the printed morphism (RewardTopos.lean: a coboundary), it is off in every
    ini, and it is folded into `parentRaw` so the division still happens once, inside the kernel.

No law, no constant of the machine and no column index appears here.  A number in this file is
either the parent's own or a bug.
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
TUT = os.path.dirname(HERE)
ROOT = os.path.dirname(TUT)
for _p in (ROOT, TUT, HERE):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import torch                                        # noqa: E402
from tandoor_hashemi_env import TandoorHashemiEnv   # noqa: E402
import hashemi_tandoor_ccc as G                     # noqa: E402  the generated module


class HashemiHarness(TandoorHashemiEnv):
    """the parent's contract; the machine is `self.M`, from the generated module"""

    MACHINE = None                      # the generated `Machine`, bound by the generated subclass
    DRAWS = None                        # the generated ray table (`draws`)
    ROTI_REWARD_RAW = 5.0               # tandoor_rl_env: rew += 5.0 * cooked (the PARENT's price)

    def __init__(self, *args, lost_shaping=0.0, pointing_shaping=0.0, capture_shaping=0.2,
                 t_amb=300.0, trace_rays=None, machine_receiver="oil", oil_nodes=8,
                 pump_price=None, deg_price=None, dish_half=None, dish_design=1, dish_R=None,
                 dish_k=None, mount_dims="held", beam_L=1.25, beam_dm=0.06, beam_rm=0.06,
                 beam_rt=0.55, beam_slot=0.06, beam_beta=0.0, **kwargs):
        self.machine_receiver = str(machine_receiver)
        self.oil_nodes = int(oil_nodes)
        self.pump_price = float(G.PUMP_PRICE if pump_price is None else pump_price)
        self.deg_price = float(G.DEG_PRICE if deg_price is None else deg_price)
        self.lost_shaping = float(lost_shaping)
        self.pointing_shaping = float(pointing_shaping)
        self.capture_shaping = float(capture_shaping)
        self.t_amb = float(t_amb)
        self._beam_kw = dict(L=beam_L, dm=beam_dm, rm=beam_rm, rt=beam_rt,
                             slotW=beam_slot, beta=beam_beta)
        self._mk = dict(dish_half=dish_half, dish_design=dish_design, dish_R=dish_R,
                        dish_k=dish_k, mount_dims=mount_dims)
        if trace_rays is not None and int(trace_rays) != G.ENV_RAYS:
            print("  [hashemi_ccc] trace_rays=%s ignored: the megakernel's rays are the spec's %d"
                  % (trace_rays, G.ENV_RAYS))
        self._phi_prev = self._phi_prev_t = None
        self._pb_skip = self._pb_skip_t = None
        self._fused_profile = None
        self._beam_profile = None
        # THE PARENT'S DAY GATED BY THE SPEC'S DEAD POINT: its beam and its guillotine are gated
        # by `el_min`, its own knob; the spec's `SunReachable` is `pi/2 - tDead <= elSun`, so the
        # parent's flag coincides with the compiled column.  `lost_deg` stays the parent's.
        kwargs.setdefault("el_min", 90.0 - np.degrees(G.mount_rest()["t_dead"]))
        if str(kwargs.get("render_mode", "")).lower() in ("none", "", "off"):
            kwargs["render_mode"] = None
        super().__init__(*args, **kwargs)
        B = self.num_agents
        self.M = self.MACHINE(B, self.dt, receiver=self.machine_receiver, t_amb=self.t_amb,
                              oil_nodes=self.oil_nodes, n_nodes=self.n_nodes, n_belt=self.n_belt,
                              beam_design=self._beam_kw, **self._mk)
        self.t_dead = self.M.t_dead
        self.dish_area = self.M.dish_area
        self.dish_design = self.M.dish_design
        self.machine = self.M.machine
        self._params = self.M.params                   # the kernel's inputs, by name
        self._np = G._Back()
        self.hk_state = np.zeros((B, 3))
        self.M.reset(self._np, self.hk_state)
        self.row = self.M.row_host
        self.hk_row = self.row
        self.cap_traced = np.zeros(B)
        self.u_pump = np.zeros(B)
        self.r_cols = np.zeros((B, G.REWARD.n_out))
        self.machine_observation_space = G.observation_space()
        self.machine_action_space = G.action_space()
        self.machine_obs = np.zeros((B, len(G.OBS_NAMES)), dtype=np.float32)
        miss = self.M.missing_obs()
        if miss:
            print("  [hashemi_ccc] the %s kernel carries no %s: those observations read zero"
                  % (self.machine_receiver, ", ".join(miss)))
        self._t = None
        self._rew_cols_t = None
        if self.gpu and self._metal is not None:
            self._t = G._TorchBack("mps")
            self._st = torch.zeros(B, 3, dtype=torch.float32, device="mps")
            self.M.reset(self._t, self._st)
            self._hk_out = torch.zeros(B, self.M.cols.n_out, dtype=torch.float32, device="mps")

    # --- the parent's sag model is not this machine's: the dish's elevation is the Lean state
    def el_dish_deg(self, el_m, wind):
        return np.asarray(el_m, dtype=np.float64)

    def el_dish_t(self, el_m, wind):
        return el_m

    def _sun(self):
        """the sun now: elevation (rad), azimuth (rad, the mount's frame) - the PARENT's sim"""
        import tandoor_hashemi_env as _m
        el0, az0, _ = _m._sim.solar_position(self.lat, self.day, float(self.t_solar[0]))
        return float(np.radians(el0)), float(az0)

    def _valve_np(self):
        """the parent's beam gate, as it will compute it this step: dni x cos x shutter x jammed"""
        el_deg = np.degrees(self._sun()[0])
        cosf = 1.0 if el_deg > 8.0 else 0.0
        return np.asarray(self.dni, dtype=np.float64) * cosf \
            * np.asarray(self.shutter, dtype=np.float64) * np.asarray(self.jammed, dtype=np.float64)

    def _sync_from_motors(self, mask):
        """a cut agent's motors were re-parked by the parent: the machine's state follows"""
        mask = np.asarray(mask, dtype=bool)
        if not mask.any():
            return
        self.hk_state[mask, 0] = np.radians(np.asarray(self.az_m, dtype=np.float64)[mask])
        t = np.radians(90.0 - np.asarray(self.el_m, dtype=np.float64)[mask])
        self.hk_state[mask, 1] = np.clip(t, 0.0, self.t_dead)
        self.hk_state[mask, 2] = 0.0
        self.el_m = np.asarray(self.el_m, dtype=np.float64)
        self.el_m[mask] = 90.0 - np.degrees(self.hk_state[mask, 1])
        if self._t is not None:
            self._st.copy_(torch.as_tensor(self.hk_state, dtype=torch.float32))

    def reset(self, *args, **kwargs):
        res = super().reset(*args, **kwargs)
        self._phi_prev = self._phi_prev_t = None
        self._pb_skip = self._pb_skip_t = None
        self._sync_from_motors(np.ones(self.num_agents, dtype=bool))
        self.M.reset(self._np, self.hk_state)
        if self._t is not None:
            self.M.reset(self._t, self._st)
        return res

    # --- the beam receiver's node profile: where the parent's own trace puts the pot's power
    def _profile_from(self, per0, lib):
        tot = per0.sum(1, keepdims=True) if lib is np else per0.sum(1, keepdim=True)
        prof = lib.where(tot > 0, per0 / (lib.maximum(tot, 1e-9) if lib is np else tot.clamp_min(1e-9)),
                         0.0 * per0)
        uni = lib.zeros(per0.shape[1]) if lib is np else torch.zeros(per0.shape[1], device=per0.device)
        uni[:self.n_nodes] = 1.0 / self.n_nodes
        ok = (prof.sum(1, keepdims=True) if lib is np else prof.sum(1, keepdim=True)) > 0
        return lib.where(ok, prof, uni[None, :])

    # --- the optional coboundary, in the parent's raw units (off in every ini)
    def _pb_raw(self, pe, reach, resync, xp):
        if not self.pointing_shaping:
            return 0.0
        if xp is np:
            phi = -np.minimum(pe, 0.5)
            prev = phi if self._phi_prev is None else self._phi_prev
            skip = resync if self._pb_skip is None else (resync | self._pb_skip)
            pb = np.where(skip, 0.0, self.pointing_shaping * (phi - prev) * reach)
            self._phi_prev = phi.copy()
            self._pb_skip = np.asarray(resync, dtype=bool).copy()
        else:
            phi = -pe.clamp(max=0.5)
            prev = phi if self._phi_prev_t is None else self._phi_prev_t
            skip = resync if self._pb_skip_t is None else (resync | self._pb_skip_t)
            pb = torch.where(skip, torch.zeros_like(phi), self.pointing_shaping * (phi - prev) * reach)
            self._phi_prev_t = phi.clone()
            self._pb_skip_t = resync.clone()
        return pb

    def _reward_ctx(self, be, parent_raw, divided, extra=0.0):
        """the reward's non-column sources: the ini's constants and the parent's own price.

        `divided` says whether the parent has already applied `reward_div` (its NumPy step has,
        its fused step has not): the lift back into the morphism's own fibre is the generated
        `lift_parent`, the only change of base there is, and the optional coboundary is folded in
        here so the division still happens once, inside the kernel."""
        div = float(getattr(self, "reward_div", 1.0))
        return dict(parent_raw=self.M.lift_parent(be, parent_raw, divided, div) + extra,
                    dt=float(self.dt), reward_div=div, cap_shaping=float(self.capture_shaping),
                    roti_reward=float(self.ROTI_REWARD_RAW), roti_energy=float(self.roti_energy),
                    pump_price=float(self.pump_price), deg_price=float(self.deg_price))

    # ------------------------------------------------------------------ the numpy path
    def _machine_ctx_np(self, a):
        return dict(head=np.asarray(a, dtype=np.float64),
                    sun_el=self._sun()[0], sun_az=self._sun()[1],
                    dni=np.asarray(self.dni, dtype=np.float64),
                    soil=np.asarray(self.soil, dtype=np.float64),
                    wind=np.asarray(self.wind, dtype=np.float64),
                    T=np.asarray(self.T, dtype=np.float64),
                    gate=self._valve_np())

    def _publish(self, be):
        row = self.M.publish(be)
        self.row = row
        self.hk_row = row
        self.machine_obs = self.M.obs
        self.u_pump = self.M.u_pump
        for att, key in G.PUBLISH:
            if key in self.M.mirror[be.tag]:
                setattr(self, att, be.host(self.M.mirror[be.tag][key]))
        if self.M.oil:
            self.hist = row[:, self.M.cols.like("hist_")]
            self.ret = row[:, self.M.cols.like("ret_")]
        self.el_m = 90.0 - np.degrees(self.hk_state[:, 1])
        self.az_m = np.degrees(self.hk_state[:, 0])

    def _trace_power(self, p_eff, sigma_b, offset_w, soil):
        """the parent's NumPy step asks for its aperture per unit DNI, per node"""
        if self.machine_receiver == "beam":
            self._beam_profile = self._profile_from(
                super()._trace_power(p_eff, sigma_b, offset_w, soil).numpy(), np)
            return torch.as_tensor(self.M.mirror["np"]["per_dni"][:, None] * self._beam_profile,
                                   dtype=torch.float32)
        per = self.M.per_node(self._np, self.M.mirror["np"]["q_pot"], self._valve_np())
        return torch.as_tensor(per, dtype=torch.float32)

    # ------------------------------------------------------------------ the fused path
    def _fused_power(self, F, aux, soil_eff):
        """after the parent's step_pre (its gate is current): F.per from the exchanger's power"""
        if self.machine_receiver == "beam":
            self._fused_profile = self._profile_from(F.per.clone(), torch)
            F.per.copy_(self._fused_profile * self.M.mirror["mps"]["per_dni"][:, None])
            return
        self._fused_profile = self.M.profile(self._t)
        F.per.copy_(self.M.per_node(self._t, self.M.mirror["mps"]["q_pot"], F.gate))

    def _gpu_full_step(self, actions):
        B = self.num_agents
        if self._gpu is None:
            from tandoor_fused_step import make_state
            self._gpu = make_state(self)
        F = self._gpu
        if not getattr(F, "fused", False):
            raise RuntimeError("HashemiTandoorEnv gpu=1 needs the fused Metal step (MPS)")
        a = actions if torch.is_tensor(actions) else \
            torch.as_tensor(np.asarray(actions, dtype=np.float32), device=self.device)
        a = a.reshape(B, self.N_HEADS).float()
        el, az = self._sun()
        g = self._gen
        dr = torch.cat([torch.rand(B, G.ENV_RAYS, self.M.cols.table("dr")["m"] - 4, generator=g, device=self.device),
                        torch.randn(B, G.ENV_RAYS, 4, generator=g, device=self.device)], 2)
        ctx = dict(head=a, sun_el=el, sun_az=az, dni=F.dni, soil=F.soil, wind=F.wind,
                   T=F.T, gate=F.gate, dr=dr)
        out = self.M.step(self._t, ctx)
        if self.render_mode == "human":
            self._scene_dr = dr                    # the picture uses the step's OWN rays
        self._hk_out = out
        return self._finish_step(F, a, out, t_before=float(self.t_solar[0]))

    def _finish_step(self, F, a, out, t_before):
        """the parent's fused step after the machine's: the motors into the packed state, the
        neutralised heads, the shaping, the resync of cut and day-over agents"""
        F.el_m.copy_(90.0 - torch.rad2deg(self._st[:, 1]))
        F.az_m.copy_(torch.rad2deg(self._st[:, 0]))
        F.el_dish.copy_(F.el_m)
        neutral = a.clone()
        neutral[:, 3] = 3
        neutral[:, 4] = 3
        neutral[:, 0] = 4          # the level head pinned (his dish has no membrane)
        neutral[:, 2] = 6          # the jam head held on (the parent gates the beam by `jammed`)
        from tandoor_fused_step import fused_full_step
        obs_t, rew_t, infos = fused_full_step(self, neutral)
        mask = F.trunc > 0.5
        if float(self.t_solar[0]) < t_before - 1.0:
            mask = torch.ones_like(mask, dtype=torch.bool)
        # `rew_t` leaves here RAW: step and step_torch divide by reward_div after this, and the
        # parent's own division IS the morphism's `r_trainer` column.
        C = self.M.cols
        extra = self._pb_raw(out[:, C["pointing_err"]], out[:, C["sun_reachable"]], mask, torch)
        if self.lost_shaping:
            extra = extra - self.lost_shaping * out[:, C["lost_sun_s"]]
        cols = self.M.reward(self._t, self._reward_ctx(self._t, rew_t, divided=False, extra=extra))
        shape = self.M.reward_col(cols, "r_shape_raw") + extra
        rew_t = self.M.reward_col(cols, "r_raw")
        self._rew_cols_t = cols
        F.ep_return.add_(shape)
        res = (obs_t, rew_t, infos)
        az_p = torch.deg2rad(F.az_m)
        t_p = torch.deg2rad(90.0 - F.el_m).clamp(0.0, self.t_dead)
        self._st[:, 0] = torch.where(mask, az_p, self._st[:, 0])
        self._st[:, 1] = torch.where(mask, t_p, self._st[:, 1])
        self._st[:, 2] = torch.where(mask, torch.zeros_like(t_p), self._st[:, 2])
        return res

    # --- the picture: the scene kernel's vertices, of THIS step
    def _scene_setup(self):
        import importlib
        rd = os.path.join(HERE, "render")
        if rd not in sys.path:
            sys.path.insert(0, rd)
        sk = importlib.import_module("scene_kernel")
        sd = importlib.import_module("scene_draw")
        name = "beam" if self.machine_receiver == "beam" else "env"
        self._scene_sk, self._scene_sd = sk, sd
        self._scene_name = name
        self._scene_kern = sk.SceneMetal(name)
        self._scene_man = self._scene_kern.man
        k = self._scene_kern
        self._scene_x = torch.zeros((1, k.n_in), dtype=torch.float32, device=self.device)
        if name == "env":
            self._scene_map = self.M.scene_map(k.inputs)
        else:
            view = importlib.import_module("view")
            a = float(self.M.params.get("a", 2.0))
            mach = os.path.join(HERE, G.machine_name(a, bool(self.dish_design)))
            if not os.path.exists(mach):
                G.load_machine(a, design=bool(self.dish_design))
            self._scene_pool = view.pool(mach)
            self._scene_x = torch.as_tensor(k.row(self._scene_pool, 1), device=self.device)
            self._scene_map = self.M.scene_map_partial(k.inputs)
        self._scene_win = sd.SceneWindow("hashemi — %s (the env's own step)" % name)

    def render(self):
        if self.render_mode != "human":
            return super().render()
        if getattr(self, "_scene_kern", None) is None:
            try:
                # pufferlib promotes RuntimeWarnings to errors; the twins take arccos at the edge
                # of its domain like every twin, so the setup runs under errstate
                with np.errstate(all="ignore"):
                    self._scene_setup()
            except Exception as exc:
                print("  [hashemi] the scene kernel is not available (%s); the parent's picture" % exc)
                self._scene_kern = False
        if self._scene_kern is False:
            return super().render()
        k, sd = self._scene_kern, self._scene_sd
        x = self.M._x.get("mps")
        if x is not None:
            for js, je in self._scene_map:
                self._scene_x[0, js] = x[0, je]
        dr = getattr(self, "_scene_dr", None)
        if dr is None:
            dr = self._scene_sk.device_draws(torch, self.num_agents, 0, k.P, self.M.cols.table("dr")["m"])

        def tab(nm):
            if nm == "dr":
                return dr[:1]
            t = self.M.tables.get("mps", {}).get(nm)
            if t is None:
                t = torch.as_tensor(np.asarray(self.M.tables["np"][nm], dtype=np.float32),
                                    device=self.device)
            return t[:1]
        tabs = [tab(aa["name"]) for aa in k.man["arrays"]]
        with np.errstate(all="ignore"):
            vs, vr = k(self._scene_x, *tabs)
        vs = vs.cpu().numpy()[0, :k.n_static]
        vr = vr.cpu().numpy()[0, :, :k.n_ray]
        C = self.M.cols
        r = self.row[0] if getattr(self, "row", None) is not None else None
        hud = ["puffer_hashemi_ccc — the env's own step, drawn from scene_%s.metal" % self._scene_name,
               "agent 0   %02d:%02.0f   az %7.2f deg   t %6.2f deg"
               % (int(self.t_solar[0]), (self.t_solar[0] % 1) * 60,
                  np.degrees(self.hk_state[0, 0]), np.degrees(self.hk_state[0, 1]))]
        if r is not None:
            hud.append("capture %.3f   p_in %6.0f W   point %.3f deg"
                       % (r[C["capture"]], r[C["p_in"]], np.degrees(r[C["pointing_err"]])))
            if self.M.oil:
                hud.append("T_oil %6.1f K   film margin %+6.1f K   q_pot %6.0f W"
                           % (r[C["T_oil"]], r[C["film_margin"]], r[C["q_pot"]]))
        hud.append("rotis %.0f   scorch %.0f   reward %.3f"
                   % (float(self.ep_rotis[0]), float(getattr(self, "ep_scorch", [0])[0]),
                      float(np.asarray(self.rewards).ravel()[0])))
        if self._scene_win.ok:
            self._scene_win.draw(self._scene_man, vs, vr, hud)
        else:
            out = os.environ.get("HASHEMI_FRAME_DIR")
            if out:
                os.makedirs(out, exist_ok=True)
                sd.to_svg(self._scene_man, vs, vr,
                          os.path.join(out, "env_%05d.svg" % int(self._scene_frame)))
        self._scene_frame = getattr(self, "_scene_frame", 0) + 1
        return None

    # --- the step
    def step(self, actions):
        if self.gpu and self._metal is not None:
            res = super().step(actions)              # routes through _gpu_full_step above
            self.M.row = self._hk_out
            self._publish(self._t)
            self.hk_state[:] = self._st.cpu().numpy()
            if self._rew_cols_t is not None:
                self.r_cols = self._rew_cols_t.cpu().numpy().astype(np.float64)
            self.el_m = 90.0 - np.degrees(self.hk_state[:, 1])
            self.az_m = np.degrees(self.hk_state[:, 0])
            return res
        B = self.num_agents
        a = np.asarray(actions).reshape(B, self.N_HEADS)
        ctx = self._machine_ctx_np(a)
        ctx["dr"] = self.DRAWS(self.rng, B)
        self.M.step(self._np, ctx)
        self._publish(self._np)
        neutral = np.array(np.round(a), dtype=np.int64)
        neutral[:, 3] = 3
        neutral[:, 4] = 3
        neutral[:, 0] = 4
        neutral[:, 2] = 6
        t_before = float(self.t_solar[0])
        res = super().step(neutral)
        C = self.M.cols
        wrapped = float(self.t_solar[0]) < t_before - 1.0
        resync = np.asarray(self.truncations, dtype=bool).copy()
        if wrapped:
            resync[:] = True
        extra = self._pb_raw(self.row[:, C["pointing_err"]], self.row[:, C["sun_reachable"]], resync, np)
        if self.lost_shaping:
            extra = extra - self.lost_shaping * self.row[:, C["lost_sun_s"]]
        # the parent has already divided its reward: the lift back into the morphism's own fibre
        # is the generated `lift_parent`, the only change of base there is.
        cols = self.M.reward(self._np, self._reward_ctx(
            self._np, np.asarray(self.rewards, dtype=np.float64), divided=True, extra=extra))
        self.r_cols = cols
        self.rewards[:] = self.M.reward_col(cols, "r_trainer").astype(np.float32)
        self.ep_return += self.M.reward_col(cols, "r_shape_raw") + extra
        self._sync_from_motors(resync)
        return res
