# generated by RequestProject/Ccc.lean (HashemiCcc.lean) from HashemiEnv.lean, HashemiReward.lean
# and HashemiPolicy.lean - do not edit.
"""The wrapper of his machine onto the tandoor, GENERATED from the kernels' own manifests.

Every kernel of this directory is printed from Lean by one driver.  Until this module the ONE
hand-written layer left was the wrapper, and every defect of the week lived there and nowhere in
anything compiled: the pointing shaping entered raw on one path and divided on the other (75x);
the exchanger's conductance was a bare `60.0` with no law behind it, binding on 99.9 % of steps;
the dish's conic constant was pinned in Python at the favourable end of the spec's own interval;
the scene's inputs were pooled on a host instead of composed in the graph; the exchanger's node
profile was inherited by accident from the parent env's tri chain.  They are all the same defect:
a number or a formula written twice, once per path, by hand.

So the wrapper is printed too, and it is printed ONCE for BOTH paths.  `Machine.step` is a single
method; `Backend` is the only thing that differs between the parent's NumPy step and its fused
Metal step.  The row the kernel is handed, the columns read back out of it, the state written
back, the reward composed, the observation gathered - each is ONE table in this file, executed by
both paths.  Nothing here can disagree with itself about units, because there is no second copy.

NOTHING IS ADDRESSED BY INDEX.  Columns and inputs are resolved by name out of the manifests
(`hashemi_env.json`, `hashemi_reward.json`, `hashemi_policy.json`, `hashemi_beam.json`); the two
pipe histories are found by their name pattern, not by a length; the parameters of the machine
are exactly the kernel inputs this file does not bind, computed as a set difference and CHECKED
to be a partition at import.  When the graded manifest lands (`"grades"` beside `"columns"`, and
`hashemi_grade.py`), `Cols.by_grade` selects on the grade; until then it says so instead of
guessing, and everything else works off the names it already has.

WHAT IS HAND-WRITTEN, and why it cannot be generated: `hashemi_harness.py` - the subclass of the
parent tandoor env (its ini kwargs, its heads, its beam gate, its guillotine and resync, the
torch/Metal device plumbing, the pufferlib contract, the render window).  That is the PARENT's
contract, not this spec's: no manifest of Hashemi.lean mentions it, and it changes when the
tandoor env changes.  The harness carries no law and no constant of the machine; it hands this
module the parent's own quantities by name and takes back the columns.
"""
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
TUT = os.path.dirname(HERE)
ROOT = os.path.dirname(TUT)
for _p in (ROOT, TUT, HERE):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import hashemi_ccc as H                                                      # noqa: E402
import hashemi_policy as machine_policy                                      # noqa: E402
from hashemi_env_kernel import (HashemiEnvMetal, draws, env_numpy, env_params,  # noqa: E402
                                exch_ua, PUMP_PRICE, DEG_PRICE)
from hashemi_reward_kernel import HashemiRewardMetal, reward_numpy           # noqa: E402

LEAN_DIR = os.environ.get("HASHEMI_LEAN_DIR", os.path.expanduser("~/manifold-pareto/lean"))


# --------------------------------------------------------------------------- the manifests
class Cols:
    """one compiled kernel's manifest, addressed BY NAME.

    `m["p_in"]` is the column, `m.inp("UAxMax")` the input, `m.like("hist_")` the columns of a
    named table in their own order (so no length is ever written down).  `by_grade` defers to the
    graded manifest (`hashemi_grade.py`, `"grades"` parallel to `"columns"`) and raises a clear
    message while that is still being emitted."""

    def __init__(self, stem):
        self.stem = stem
        self.man = json.load(open(os.path.join(HERE, stem + ".json")))
        self.columns = list(self.man["columns"])
        self.inputs = list(self.man.get("inputs", []))
        self.arrays = list(self.man.get("arrays", []))
        self._c = {n: i for i, n in enumerate(self.columns)}
        self._i = {n: i for i, n in enumerate(self.inputs)}

    # -- columns
    def __contains__(self, n):
        return n in self._c

    def __getitem__(self, n):
        return self._c[n]

    def get(self, n, default=None):
        return self._c.get(n, default)

    def many(self, names):
        return [self._c[n] for n in names]

    def like(self, prefix):
        """the columns `<prefix><k>`, k = 0, 1, 2, ... in order - a table's width is its own"""
        out, k = [], 0
        while (prefix + str(k)) in self._c:
            out.append(self._c[prefix + str(k)])
            k += 1
        return out

    # -- inputs
    def inp(self, n):
        return self._i[n]

    def has_input(self, n):
        return n in self._i

    @property
    def n_in(self):
        return len(self.inputs)

    @property
    def n_out(self):
        return int(self.man["n_columns"])

    def table(self, name):
        for a in self.arrays:
            if a["name"] == name:
                return a
        raise KeyError("%s has no table %r" % (self.stem, name))

    # -- the grades (a36a754's manifest: "grades" parallel to "columns", and hashemi_grade.py)
    def by_grade(self, **sel):
        try:
            import hashemi_grade
        except ImportError:
            hashemi_grade = None
        if hashemi_grade is None or "grades" not in self.man:
            raise RuntimeError("manifest %s carries no grades: rebuild RequestProject.HashemiCcc"
                               % self.stem)
        return hashemi_grade.cols_of(self.man, **sel)

    def grade(self, name):
        try:
            import hashemi_grade
        except ImportError:
            raise RuntimeError("manifest %s carries no grades: rebuild RequestProject.HashemiCcc"
                               % self.stem)
        return hashemi_grade.grade_of(self.man, name)


ENV = Cols("hashemi_env")
REWARD = Cols("hashemi_reward")
BEAM = Cols("hashemi_beam")
MEGA = Cols("hashemi_mega")
POLICY = json.load(open(os.path.join(HERE, "hashemi_policy.json")))
HEAD_AZ, HEAD_EL = POLICY["motor_heads"]
ACTION_LEVELS = int(POLICY["action_levels"])
OBS_NAMES = list(machine_policy.OBS_NAMES)
# the two full-command rates of the spec (`azFull`, `elFull`), from the compiled twin
AZ_FULL, EL_FULL = float(H.hk_azFull()), float(H.hk_elFull())


def kernel_of(receiver):
    """the compiled env step of a receiver: the oil loop's, or the hyperboloid beam-down's"""
    return BEAM if receiver == "beam" else ENV


# --------------------------------------------------------------- ONE description, both paths
#
# THE KERNEL'S INPUT ROW.  Left: the input, as the compiled morphism names it.  Right: the source,
# as this module names it - either a quantity the harness hands over (the parent's own) or one
# `_derive` computes below from the compiled twin.  Every input of the manifest that is NOT in
# this table is a PARAMETER of the machine (`Machine.params`), and `_partition` checks at import
# that the two sets are disjoint and cover the manifest: an input added in Lean and forgotten
# here is an error at import, not a silent zero.
ENV_BIND = (
    ("az", "state_az"),
    ("t", "state_t"),
    ("slack", "state_slack"),
    ("omegam", "drive_az"),
    ("omegad", "drive_el"),
    ("dt", "dt"),
    ("elSun", "sun_el"),
    ("azSun", "sun_az"),
    ("dni", "dni"),
    ("soil", "soil"),
    ("Twall", "t_wall"),
    ("Ta", "t_amb"),
    ("uPump", "u_pump"),
    ("Vw", "wind"),
    ("degPrev", "deg"),
    ("UAxMax", "ua_gated"),
)
BEAM_BIND = (
    ("az", "state_az"),
    ("t", "state_t"),
    ("slack", "state_slack"),
    ("omegam", "drive_az"),
    ("omegad", "drive_el"),
    ("dt", "dt"),
    ("elSun", "sun_el"),
    ("azSun", "sun_az"),
    ("dni", "dni"),
    ("soil", "soil"),
)
# the state the wrapper carries between steps IS three of the kernel's own columns
STATE_WRITE = (
    ("state_az", "az_next"),
    ("state_t", "t_next"),
    ("state_slack", "slack_next"),
)
# the two fields along the pipe, written back into the tables the kernel reads next step
TABLE_WRITE = (
    ("hist", "hist_"),
    ("ret", "ret_"),
)
# the columns the host keeps a mirror of, and the attribute the parent's readers know them by.
# `oil` marks a column only the loop receiver's kernel carries.
MIRROR = (
    ("cap_traced", "capture", "both"),
    ("arm", "arm", "both"),
    ("p_in", "p_in", "both"),
    ("per_dni", "per_dni", "both"),
    ("pointing_err", "pointing_err", "both"),
    ("sun_reachable", "sun_reachable", "both"),
    ("lost_sun_s", "lost_sun_s", "both"),
    ("t_oil", "T_oil", "oil"),
    ("q_pot", "q_pot", "oil"),
    ("deg", "deg", "oil"),
    ("p_pump", "p_pump", "oil"),
    ("film_margin", "film_margin", "oil"),
)
# THE REWARD, in the printed morphism's own units.  `col:` reads the env row by name, `excess:`
# the negative part of one (the film's margin below its limit), `?0` is zero when the receiver's
# kernel does not carry that column; everything else is a quantity the harness hands over.  Both
# paths execute THIS table: `reward_div` is applied once, inside `rewardStep`, and the 75x of
# 2026-09-19 cannot recur because there is no second expression to disagree with.
REWARD_BIND = (
    ("parentRaw", "parent_raw"),
    ("dt", "dt"),
    ("pIn", "col:p_in"),
    ("reach", "col:sun_reachable"),
    ("rewardDiv", "reward_div"),
    ("capShaping", "cap_shaping"),
    ("rotiReward", "roti_reward"),
    ("rotiEnergy", "roti_energy"),
    ("pPump", "col:p_pump?0"),
    ("filmExcess", "excess:film_margin?0"),
    ("pumpPrice", "pump_price"),
    ("degPrice", "deg_price"),
)


def _partition(cols, bind, extra=()):
    """the inputs this module binds per step, and the rest - the machine's parameters.

    A partition, checked: an input of the compiled morphism is either bound from a source above
    or a parameter, never both and never neither."""
    bound = [n for n, _ in bind]
    dup = [n for n in bound if bound.count(n) > 1]
    if dup:
        raise RuntimeError("%s: bound twice: %s" % (cols.stem, sorted(set(dup))))
    unknown = [n for n in bound if not cols.has_input(n)]
    if unknown:
        raise RuntimeError("%s: bound inputs that the kernel does not take: %s" % (cols.stem, unknown))
    params = [n for n in cols.inputs if n not in bound]
    missing = [n for n in params if n not in extra]
    return params, missing


PARAM_INPUTS, _ = _partition(ENV, ENV_BIND)
BEAM_PARAM_INPUTS, _ = _partition(BEAM, BEAM_BIND)


# --------------------------------------------------------------------------- the two backends
class _Back:
    """the only thing that differs between the parent's NumPy step and its fused Metal step"""

    numpy = True
    tag = "np"

    def __init__(self, device=None):
        self.device = device

    def zeros(self, shape, fill=0.0):
        return np.full(shape, fill, dtype=np.float64)

    def put(self, x, j, v):
        x[:, j] = v

    def take(self, row, j):
        return row[:, j]

    def zeros_like(self, v):
        return np.zeros_like(v)

    def where(self, c, a, b):
        return np.where(c, a, b)

    def clamp(self, v, lo, hi):
        # min (max v lo) hi, the shape `headToCmd` is printed in
        return np.minimum(np.maximum(v, lo), hi)

    def clamp_min(self, v, lo):
        return np.maximum(v, lo)

    def gt(self, v, x):
        return v > x

    def indicator(self, c):
        """a gate as a number: the exchanger's ceiling opens with the parent's beam gate"""
        return np.asarray(c, dtype=np.float64)

    def neg_part(self, v):
        return np.maximum(0.0, -v)

    def full(self, ref, value):
        return np.full(ref.shape[0], value, dtype=np.float64)

    def copy(self, v):
        return np.array(v, dtype=np.float64)

    def host(self, v):
        return np.asarray(v, dtype=np.float64)


class _TorchBack(_Back):
    numpy = False
    tag = "mps"

    def __init__(self, device):
        import torch
        self.torch = torch
        self.device = device

    def zeros(self, shape, fill=0.0):
        return self.torch.full(shape, float(fill), dtype=self.torch.float32, device=self.device)

    def zeros_like(self, v):
        return self.torch.zeros_like(v)

    def where(self, c, a, b):
        return self.torch.where(c, a, b)

    def clamp(self, v, lo, hi):
        return v.clamp(lo, hi)

    def clamp_min(self, v, lo):
        return v.clamp_min(lo)

    def indicator(self, c):
        return c.float()

    def neg_part(self, v):
        return (-v).clamp_min(0.0)

    def full(self, ref, value):
        return self.torch.full_like(ref if ref.dim() == 1 else ref[:, 0], float(value))

    def copy(self, v):
        return v.clone()

    def host(self, v):
        return v.detach().cpu().numpy().astype(np.float64)


# ------------------------------------------------------------------- the machine's parameters
def machine_name(a, design=False):
    """`hashemi_machine_0.8.json`, `hashemi_machine_2.0_designed.json`"""
    s = "%g" % float(a)
    return ("hashemi_machine_" + (s if "." in s else s + ".0")
            + ("_designed" if design else "") + ".json")


def load_machine(a, design=False):
    """THE MACHINE AT HALF-SIDE `a`, DERIVED IN LEAN (RequestProject/HashemiScale.lean).

    Reads the shipped file; if there is none, asks Lean for it (`lake exe machine_scale <a>
    <path>`), which is the only thing allowed to compute it.  `design=True` is the same
    derivation with the held quantities solved from the constraints that name them."""
    path = os.path.join(HERE, machine_name(a, design))
    if not os.path.exists(path):
        import subprocess
        r = subprocess.run(["lake", "exe", "machine_scale", "%g" % float(a), path]
                           + (["--design"] if design else []),
                           cwd=LEAN_DIR, capture_output=True, text=True)
        if r.returncode != 0 or not os.path.exists(path):
            raise RuntimeError("no %s and `lake exe machine_scale` failed in %s:\n%s\n%s"
                               % (os.path.basename(path), LEAN_DIR, r.stdout, r.stderr))
    return json.load(open(path))


def apply_machine(params, m, a, design, cols, log=print):
    """the machine file into the kernel's parameters, BY NAME.

    Which of the file's fields are parameters is not a list here: it is the manifest's own input
    names.  `UAxMax` is the spec's `uaExch` at this machine's buried coil (it was a hand-written
    60.0, measured binding on 99.9 % of a day's steps)."""
    for block in ("kernel", "mount", "loop"):
        for kk, vv in (m.get(block) or {}).items():
            if cols.has_input(kk):
                params[kk] = vv
    if cols.has_input("UAxMax"):
        params["UAxMax"] = exch_ua(os.path.join(HERE, machine_name(a, design)))
        log("  [hashemi_ccc] the exchanger conducts %.2f W/K (uaExch, the coil in the liner)"
            % params["UAxMax"])
    if m.get("designed") and m.get("design_changes"):
        log("  [hashemi_ccc] the machine at a=%s is DESIGNED: " % a
            + ", ".join("%s %g -> %g (%s)" % (c["held"], c["from"], c["to"], c["constraint"])
                        for c in m["design_changes"]))
    bad = {k: v for k, v in m.get("constraints", {}).items() if v != "holds"}
    if bad:
        log("  [hashemi_ccc] the machine at a=%s does not satisfy the spec: " % a
            + ", ".join("%s: %s" % (k, v) for k, v in bad.items()))
    return params


# the pose the mount's own constants are read at: parked, no command, the sun anywhere.  `dt` is
# 1 s and not 0 because the loop's columns divide by it; the mount's do not depend on it at zero
# command, so the pose is the rest pose either way.
MOUNT_REST_POSE = dict(dt=1.0, elSun=0.5, azSun=0.0, dni=800.0, soil=1.0, Twall=300.0, Ta=300.0)
# what the wrapper calls each, and the mount column it is
MOUNT_REST_COLS = (("t_dead", "mount_t_dead"), ("roller_R", "mount_rollerRadius"),
                   ("arm_rest", "mount_arm"), ("dish_side", "mount_dishSide"))


# the mount kernel's own pose inputs; everything else it takes is a dimension or a parameter
MOUNT_POSE = dict(az=0.0, t=0.0, slack=0.0, omegam=0.0, omegad=0.0, dt=0.0,
                  elSun=0.5, azSun=0.0, dni=800.0)
# the dimensions the mount has taken as arguments, and the optics input each one is
MOUNT_DIM_OF = (("dHalf", "a"), ("wFacet", "w"), ("rCoil", "rc"))


def mount_held():
    """the mount kernel at ITS OWN parameters and the SPEC's own dimensions.

    This is the constant set the hand-written wrapper read (one launch of the mount kernel at
    `megaParams`, which carries no dimension), and it is what `mount_dims="held"` means.  It is
    assembled from `hashemi_mega.json` - the parameters are the kernel's inputs that are not the
    pose, in its own order, and the dimensions it has since taken as arguments are the spec's own
    optics inputs - so it does not go stale when the mount takes another one."""
    prm = np.asarray(H.hk_megaParams(), dtype=np.float64).ravel()
    names = [n for n in MEGA.inputs if n not in MOUNT_POSE]
    vals = dict(zip(names[:prm.size], prm))
    opt = env_params()
    for n, src in MOUNT_DIM_OF:
        if n in names and n not in vals:
            vals[n] = float(opt[src])
    missing = [n for n in names if n not in vals]
    if missing:
        raise RuntimeError("the mount kernel takes %s and this module has no source for them"
                           % missing)
    args = [np.array([float(MOUNT_POSE.get(n, vals.get(n, 0.0)))]) for n in MEGA.inputs]
    out = {}
    with np.errstate(all="ignore"):
        for f in MEGA.man["functions"]:
            v = np.asarray(getattr(H, f["c"])(*args), dtype=np.float64).reshape(1, f["n_out"])
            for k, c in MOUNT_REST_COLS:
                j = MEGA[c[len("mount_"):]] if c.startswith("mount_") else MEGA[c]
                if f["offset"] <= j < f["offset"] + f["n_out"]:
                    out[k] = float(v[0, j - f["offset"]])
    return out


def mount_rest(params=None):
    """the mount's own constants, read from THE ENV MORPHISM'S OWN COLUMNS at the parked pose.

    `t_dead` is the dead point the parent's `el_min` is set to, `mount_rollerRadius` and
    `mount_arm` (`wireLever` at rest) are what the drives are scaled by.  They are read out of
    `hashemiEnv` itself - one launch of the twin at zero command - and not out of a second,
    separately packed launch of the mount kernel: the env carries the whole mount under
    `mountNames`, so these are the very numbers the step will use, at the literals it uses.
    (Until 2026-09-20 they came from a hand-packed `mega_numpy` call, which silently went stale
    the moment the mount took its dimensions as arguments.)"""
    prm = dict(env_params() if params is None else params)
    x = np.zeros((1, ENV.n_in))
    for n in ENV.inputs:
        x[0, ENV.inp(n)] = float(prm.get(n, MOUNT_REST_POSE.get(n, 0.0)))
    w = len(ENV.like("hist_"))
    hist = np.full((1, w), MOUNT_REST_POSE["Ta"])
    dr = np.full((1, ENV_RAYS, ENV.table("dr")["m"]), 0.5)
    with np.errstate(all="ignore"):
        row = env_numpy(x, hist, hist.copy(), dr)
    return {k: float(row[0, ENV[c]]) for k, c in MOUNT_REST_COLS}


# the columns the parent's own readers know by an attribute of the env (the machine's, never the
# parent's own `p_in`): the harness publishes these and nothing else.
PUBLISH = (
    ("cap_traced", "cap_traced"),
    ("t_oil", "t_oil"),
    ("deg", "deg"),
    ("_q_pot", "q_pot"),
    ("_p_pump", "p_pump"),
)
ENV_RAYS = int(ENV.man["rays"])


# ------------------------------------------------------------------------- the spaces (spec's)
def observation_space():
    """the machine's observations, bounded by the spec (`obsLo` / `obsHi`)"""
    return machine_policy.observation_space()


def action_space():
    """the machine's commands in [-1, 1] per motor"""
    return machine_policy.action_space()


# ------------------------------------------------------------------------------- the machine
class Machine:
    """his machine inside the tandoor env: one compiled morphism, run on either backend.

    The harness constructs one of these and hands it the parent's own quantities each step
    (`ctx`); everything else - the commands the heads mean, the pump's fraction, the wall the
    exchanger sees, the row, the columns, the state, the reward - is this class, and this class
    has one copy of each."""

    def __init__(self, B, dt, receiver="oil", t_amb=300.0, oil_nodes=8, n_nodes=None, n_belt=None,
                 dish_half=None, dish_design=1, dish_k=None, dish_R=None, beam_design=None,
                 mount_dims="held", log=print):
        self.B, self.dt, self.receiver = int(B), float(dt), str(receiver)
        self.t_amb = float(t_amb)
        self.cols = kernel_of(self.receiver)
        self.oil = self.receiver != "beam"
        self.oil_nodes, self.n_nodes, self.n_belt = int(oil_nodes), n_nodes, n_belt
        self.log = log
        self.params = env_params()
        if dish_k is not None and self.cols.has_input("k"):
            self.params["k"] = float(np.clip(float(dish_k), -1.0, 0.0))
        self.beam_design = dict(beam_design or {})
        self.machine = None
        self.dish_design = int(dish_design)
        self.r_drive = 0.05          # `Hashemi.carriage.rDrive`, replaced by the machine's own
        if dish_half is not None:
            m = load_machine(float(dish_half), design=bool(self.dish_design))
            apply_machine(self.params, m, dish_half, bool(self.dish_design), self.cols, log=log)
            self.machine = m
            self.r_drive = float(m["machine"].get("rDrive", self.r_drive))
            for kk in ("a", "R", "f"):
                if kk in m["kernel"]:
                    self.beam_design[kk] = m["kernel"][kk]
            if dish_R is not None:
                R = float(dish_R)
                self.params.update(R=R, f=R / 2.0)
                self.beam_design.update(R=R, f=R / 2.0)
        for kk, vv in self.beam_design.items():
            if self.cols.has_input(kk):
                self.params[kk] = vv
        self.dish_area = (2.0 * float(self.params["a"])) ** 2
        # THE MOUNT'S DIMENSIONS, and what a full command therefore means.  The mount takes its own
        # dimensions as arguments now (`dHalf`, `wFacet`, `rCoil`), so the ring rail's radius and
        # the wire's lever arm are no longer his 1.22 m and 1.03 m at every size: at a = 2 m the
        # ring is 3.05 m.  The drive is `driveAz u rw R = u azFull R / rw`, and the kernel turns
        # that back into the dish's rate with ITS OWN ring, so which `R` the wrapper drives with
        # decides what a full command does:
        #   "held"    - the mount at the SPEC'S OWN machine.  That is what the hand-written
        #     wrapper's separately packed `mega_numpy` call returned at any size, so it is what
        #     every measured day and every checkpoint was made with.  MEASURED at a = 2 m: the
        #     dish then turns at 0.0140 deg/s at full command, while the parent env's `RATE_AZ`,
        #     the cook's follower and the policy all believe it turns at 0.035.
        #   "machine" - the mount at THIS machine's dimensions (its own `mount_rollerRadius`
        #     column).  The dish then turns at exactly `azFull` = 0.0350 deg/s, which is what
        #     `driveAz_rate` proves and what the parent assumes - and MEASURED, the naive
        #     follower's day falls from 51.8 rotis to 0.1, because its gain was written against a
        #     machine that slewed at 40 % of full command.
        # The default is "held", so that printing the wrapper changes no number; the finding is
        # the notice below, and the choice belongs to whoever owns the mount.
        self.mount_dims = str(mount_dims)
        held, mach = mount_held(), mount_rest(self.params)
        rest = mach if self.mount_dims == "machine" else held
        if any(abs(held[k] - mach[k]) > 1e-9 for k in held):
            log("  [hashemi_ccc] the mount's dimensions are per-machine now: the ring rail is "
                "%.4f m at the spec's own machine and %.4f m at this one, the wire's rest lever "
                "%.4f / %.4f. mount_dims=%s, so a full azimuth command turns the dish at "
                "%.4f deg/s (azFull is %.4f)."
                % (held["roller_R"], mach["roller_R"], held["arm_rest"], mach["arm_rest"],
                   self.mount_dims, np.degrees(AZ_FULL) * rest["roller_R"] / mach["roller_R"],
                   np.degrees(AZ_FULL)))
        self.t_dead = rest["t_dead"]
        self.roller_R = rest["roller_R"]
        self.arm_rest = rest["arm_rest"]     # `wireLever` at rest, for step one
        self.r_drum = float(self.params["rDrum"])
        # THE DRIVES, in the printed morphism's own shape.  `headToCmd h = (min (max h 0) 6 - 3)/3`,
        # `driveAz u rw R = u azFull R / rw`, `headToDriveEl h arm rDrum = driveEl (-(headToCmd h))
        # arm rDrum` - so the expression below is those three, associated as the printer
        # associates them, with `azFull` / `elFull` taken from the compiled twin and the seven
        # levels from the policy's manifest.  It is not enough that it be algebraically right: a
        # last-bit difference from the printed order moves a boolean in the ray sum a few hundred
        # steps later and the day's rotis with it (measured 2026-09-20: 51.75 vs 0.62 over a day
        # from one ulp).  `_check_drives` therefore requires EXACT equality with
        # `headToDriveAz` / `headToDriveEl` at import, not a tolerance.
        self.h_max = float(ACTION_LEVELS - 1)
        self.h_mid = self.h_max / 2.0
        self._check_drives()
        # the params of this kernel that are not bound per step, as a set difference
        self.param_inputs = [n for n in self.cols.inputs
                             if n not in [b for b, _ in self._bind()]]
        miss = [n for n in self.param_inputs if n not in self.params]
        if miss:
            raise RuntimeError("the %s kernel takes %s, and neither this module nor the machine "
                               "file supplies them" % (self.cols.stem, miss))
        # the row and its tables, per backend
        self._x = {}
        self._kern = {}
        self._rew_x = {}
        self._rew_kern = {}
        self.tables = {}
        self.state = {}
        self.mirror = {}
        self.row = None                 # the last step's columns, on that step's own backend
        self.row_host = np.zeros((self.B, self.cols.n_out))
        self.obs = np.zeros((self.B, len(OBS_NAMES)), dtype=np.float32)
        self.r_cols = np.zeros((self.B, REWARD.n_out))
        self.r_cols_dev = None
        self.u_pump = np.zeros(self.B)
        self._profile = {}

    # -- the description, per receiver
    def _bind(self):
        return BEAM_BIND if self.receiver == "beam" else ENV_BIND

    def _check_drives(self):
        """the description against the compiled `headToDriveAz` / `headToDriveEl`, BIT FOR BIT"""
        be = _Back()
        h = np.concatenate([np.arange(0.0, self.h_max + 1.0), np.linspace(-1.0, 7.0, 17)])
        arm = np.linspace(0.2, 3.0, h.size)
        az = np.asarray(H.hk_headToDriveAz(h, np.full(h.shape, self.r_drive),
                                           np.full(h.shape, self.roller_R)), dtype=np.float64)
        el = np.asarray(H.hk_headToDriveEl(h, arm, np.full(h.shape, self.r_drum)), dtype=np.float64)
        u = self._cmd_of(be, h)
        mine_az = self.drive_az(be, u)
        mine_el = self.drive_el(be, u, arm)
        if not (np.array_equal(mine_az, az) and np.array_equal(mine_el, el)):
            raise RuntimeError("the drive description is not the printed one, bit for bit: "
                               "%.3e / %.3e" % (float(np.max(np.abs(mine_az - az))),
                                                float(np.max(np.abs(mine_el - el)))))

    def _cmd_of(self, be, head):
        """`headToCmd`: a head's value to a command in [-1, 1], on either backend"""
        return (be.clamp(head, 0.0, self.h_max) - self.h_mid) / self.h_mid

    def drive_az(self, be, u):
        """`driveAz`: the roller's rate, in the printer's own association"""
        return u * AZ_FULL * self.roller_R / self.r_drive

    def drive_el(self, be, u, arm):
        """`headToDriveEl`: the drum's rate at the wire's lever arm; a positive command lowers"""
        return (-u) * EL_FULL * arm / self.r_drum

    # -- the exchanger's node profile.  DEFINED, never inherited: the coil in the pot's wall heats
    # the first `oil_nodes` belt slots uniformly and nothing on the loaf columns.  (Until
    # 2026-09-19 it was the parent's own tri-chain spot, frozen at the first step.)
    def profile(self, be):
        p = self._profile.get(be.tag)
        if p is None:
            k = max(1, min(self.oil_nodes, self.n_belt))
            prof = np.zeros((self.B, self.n_nodes + self.n_belt))
            prof[:, :k] = 1.0 / k
            if be.numpy:
                p = prof
            else:
                p = be.torch.as_tensor(prof, dtype=be.torch.float32, device=be.device)
            self._profile[be.tag] = p
        return p

    def wall_seen(self, be, T):
        """the wall the exchanger delivers into: the pot's nodes under the coil's own profile"""
        pn = self.profile(be)[:, :self.n_nodes]
        return (T[:, :self.n_nodes] * pn).sum(1) / be.clamp_min(pn.sum(1), 1e-9)

    def per_node(self, be, q_pot, gate):
        """the pot's aperture per unit DNI: the exchanger's power along the coil's own profile,
        through the parent's own gate (`per_dni x gate x 0.85` is what its nodes absorb)"""
        per = be.where(be.gt(gate, 0.0), q_pot / be.clamp_min(gate * 0.85, 1e-9), be.zeros_like(gate))
        return self.profile(be) * per[:, None]

    # -- the state this wrapper carries, and the tables the kernel reads
    def reset(self, be, state):
        self.state[be.tag] = state
        for name, _ in TABLE_WRITE:
            if self.oil:
                self.tables.setdefault(be.tag, {})[name] = be.zeros(
                    (self.B, len(self.cols.like(name + "_"))), self.t_amb)
        self.mirror.setdefault(be.tag, {})
        for att, col, who in MIRROR:
            if who == "oil" and not self.oil:
                continue
            if col in self.cols:
                self.mirror[be.tag].setdefault(att, be.zeros((self.B,)))

    def sync_state(self, be, az, t, slack):
        st = self.state[be.tag]
        st[:, 0], st[:, 1], st[:, 2] = az, t, slack

    # -- ONE step, ONE description, either backend
    def _derive(self, be, ctx):
        """the sources the table above names, from the parent's own quantities.

        This is where the heads become the spec's commands, the pump's head becomes a fraction,
        the pot's nodes become the wall the exchanger sees, and the exchanger's ceiling is opened
        with the parent's beam gate.  ONE copy, so the two paths cannot drift."""
        st = self.state[be.tag]
        head = ctx["head"]
        arm_prev = self.mirror[be.tag]["arm"]
        arm = be.where(be.gt(arm_prev, 0.05), arm_prev, be.full(arm_prev, self.arm_rest))
        u_az = self._cmd_of(be, head[:, HEAD_AZ])
        u_el = self._cmd_of(be, head[:, HEAD_EL])
        # the pump is the parent's pinned head 0 (`pumpOf`), read BEFORE the host neutralises it
        u_pump = be.clamp(head[:, 0], 0.0, self.h_max) / self.h_max
        src = {
            "state_az": st[:, 0], "state_t": st[:, 1], "state_slack": st[:, 2],
            "drive_az": self.drive_az(be, u_az),
            "drive_el": self.drive_el(be, u_el, arm),
            "dt": self.dt, "t_amb": self.t_amb,
            "sun_el": ctx["sun_el"], "sun_az": ctx["sun_az"],
            "dni": ctx["dni"], "soil": ctx["soil"], "wind": ctx.get("wind", 0.0),
            "u_pump": u_pump,
        }
        if self.oil:
            src["deg"] = self.mirror[be.tag]["deg"]
            src["t_wall"] = self.wall_seen(be, ctx["T"])
            src["ua_gated"] = float(self.params["UAxMax"]) * be.indicator(be.gt(ctx["gate"], 0.0))
        return src, u_pump

    def row_buffer(self, be):
        x = self._x.get(be.tag)
        if x is None:
            x = be.zeros((self.B, self.cols.n_in))
            for n in self.param_inputs:
                be.put(x, self.cols.inp(n), float(self.params[n]))
            self._x[be.tag] = x
        return x

    def kernel(self, be):
        k = self._kern.get(be.tag)
        if k is None:
            if self.receiver == "beam":
                import hashemi_beam_kernel as bk
                k = bk.HashemiBeamMetal()
            else:
                k = HashemiEnvMetal()
            self._kern[be.tag] = k
        return k

    def step(self, be, ctx):
        """the machine's step: assemble, launch, absorb.  The SAME method on both paths."""
        x = self.row_buffer(be)
        src, u_pump = self._derive(be, ctx)
        for name, key in self._bind():
            be.put(x, self.cols.inp(name), src[key])
        dr = ctx["dr"]
        if be.numpy:
            if self.receiver == "beam":
                import hashemi_beam_kernel as bk
                row = bk.beam_numpy(x, dr)
            else:
                tb = self.tables[be.tag]
                row = env_numpy(x, tb["hist"], tb["ret"], dr)
        else:
            if self.receiver == "beam":
                row = self.kernel(be).step(x, dr)
            else:
                tb = self.tables[be.tag]
                row = self.kernel(be).step(x, tb["hist"], tb["ret"], dr)
        self.absorb(be, row)
        self.u_pump = be.host(u_pump)
        return row

    def absorb(self, be, row):
        """the columns back out of the row, BY NAME: the state, the two pipe fields, the mirrors"""
        self.row = row
        st = self.state[be.tag]
        for j, (_, col) in enumerate(STATE_WRITE):
            st[:, j] = be.take(row, self.cols[col])
        if self.oil:
            tb = self.tables[be.tag]
            for name, prefix in TABLE_WRITE:
                js = self.cols.like(prefix)
                if be.numpy:
                    tb[name] = row[:, js].copy()
                else:
                    tb[name].copy_(row[:, js])
        mir = self.mirror[be.tag]
        for att, col, who in MIRROR:
            if who == "oil" and not self.oil:
                continue
            if col in self.cols:
                if be.numpy:
                    mir[att] = row[:, self.cols[col]].copy()
                else:
                    mir[att] = row[:, self.cols[col]]

    def publish(self, be):
        """the host mirrors the parent's readers expect, and the observation row"""
        self.row_host = be.host(self.row)
        self.obs = self.obs_row(self.row_host)
        return self.row_host

    def obs_row(self, row_host):
        """the machine's observations, in the POLICY's order (`obsNames`), by name.

        A receiver whose kernel does not carry one of them reports zero for it rather than
        raising: the loop's three (`margin`, `flow`, `deg`) are not columns of the beam-down."""
        out = np.zeros((row_host.shape[0], len(OBS_NAMES)), dtype=np.float32)
        for j, n in enumerate(OBS_NAMES):
            c = self.cols.get("obs_" + n)
            if c is not None:
                out[:, j] = row_host[:, c]
        return out

    def missing_obs(self):
        return [n for n in OBS_NAMES if ("obs_" + n) not in self.cols]

    # -- the reward, in the printed morphism's own units
    def reward_kernel(self, be):
        k = self._rew_kern.get(be.tag)
        if k is None:
            k = HashemiRewardMetal()
            self._rew_kern[be.tag] = k
        return k

    def lift_parent(self, be, rew, divided, reward_div):
        """the parent's raw reward for the step.

        The fused path hands it over before its own division and the NumPy path after, so the
        lift back into the morphism's fibre happens HERE, once, and never as arithmetic beside a
        second copy of the shaping."""
        return rew * float(reward_div) if divided else rew

    def reward(self, be, ctx):
        """`rewardStep` (HashemiReward.lean): the five columns of the step's reward"""
        x = self._rew_x.get(be.tag)
        if x is None:
            x = be.zeros((self.B, REWARD.n_in))
            self._rew_x[be.tag] = x
        mir = self.mirror[be.tag]
        for name, src in REWARD_BIND:
            if src.startswith("col:") or src.startswith("excess:"):
                kind, col = src.split(":", 1)
                opt = col.endswith("?0")
                col = col[:-2] if opt else col
                if col not in self.cols:
                    if not opt:
                        raise RuntimeError("the %s kernel has no column %r for the reward's %s"
                                           % (self.cols.stem, col, name))
                    v = 0.0
                else:
                    v = mir[col] if col in mir else be.take(self.row, self.cols[col])
                    if kind == "excess":
                        v = be.neg_part(v)
                be.put(x, REWARD.inp(name), v)
            else:
                be.put(x, REWARD.inp(name), ctx[src])
        if be.numpy:
            cols = reward_numpy(x)
            self.r_cols = cols
        else:
            cols = self.reward_kernel(be).step(x)
            self.r_cols_dev = cols
        return cols

    def reward_col(self, cols, name):
        return cols[:, REWARD[name]]

    # -- the picture: the scene kernel's own input row is the env kernel's, name for name
    def scene_map(self, scene_inputs):
        """NOTHING is pooled on a host: every dimension the scene needs is bound in the graph"""
        missing = [n for n in scene_inputs if not self.cols.has_input(n)]
        if missing:
            raise RuntimeError("the %s scene still asks for %s off the graph"
                               % (self.cols.stem, missing))
        return [(j, self.cols.inp(n)) for j, n in enumerate(scene_inputs)]

    def scene_map_partial(self, scene_inputs):
        """a standalone scene: the inputs it shares with the env's row, by name"""
        return [(j, self.cols.inp(n)) for j, n in enumerate(scene_inputs)
                if self.cols.has_input(n)]


# the wrapper the trainer loads: the parent's contract from the hand-written harness, the machine
# from this generated module.  `puffer_hashemi_ccc` names THIS class.
from hashemi_harness import HashemiHarness                                   # noqa: E402


class HashemiTandoorEnv(HashemiHarness):
    """the tandoor with his concentrator: the machine from one compiled morphism"""

    MACHINE = Machine
    DRAWS = staticmethod(draws)
    PUMP_PRICE = PUMP_PRICE
    DEG_PRICE = DEG_PRICE
