/* generated by RequestProject/Ccc.lean from RequestProject/Hashemi.lean - do not edit.
   Each function is one definition of Hashemi.lean, read as it stands and compiled to a
   hash-consed dataflow graph; the includer sets hk_real and the math macros. */
#ifndef HASHEMI_CCC_H
#define HASHEMI_CCC_H
#ifndef HK_NO_STD
#include <math.h>
#include <stdbool.h>
#endif
#ifndef HK_STATIC
#define HK_STATIC static inline
#endif
#ifndef HK_ADDR
#define HK_ADDR
#endif
#ifndef hk_real
#define hk_real float
#endif
#ifndef HK_LIT
#define HK_LIT(x) ((hk_real)(x))
#endif
#ifndef HK_PI
#define HK_PI HK_LIT(3.14159265358979323846)
#endif
#ifndef hk_sqrt
#define hk_sqrt sqrt
#define hk_sin sin
#define hk_cos cos
#define hk_tan tan
#define hk_atan atan
#define hk_exp exp
#define hk_log log
#define hk_fabs fabs
#define hk_min fmin
#define hk_max fmax
#endif
/* `=` on ℝ, in floating point: a relative tolerance, the includer may tighten or loosen it */
#ifndef hk_eq
#define hk_eq(a, b) (hk_fabs((a) - (b)) <= HK_LIT(1e-9) * hk_max(HK_LIT(1), hk_max(hk_fabs(a), hk_fabs(b))))
#endif

/* ---- definitions ---- */
HK_STATIC hk_real hk_azRate(hk_real omegam, hk_real rw, hk_real R) {
  const hk_real t0 = omegam;
  const hk_real t1 = rw;
  const hk_real t2 = R;
  const hk_real t3 = (t0 * t1);
  const hk_real t4 = (t3 / t2);
  return t4;
}

HK_STATIC hk_real hk_boltStress(hk_real W, hk_real reach, hk_real d) {
  const hk_real t0 = W;
  const hk_real t1 = reach;
  const hk_real t2 = d;
  const hk_real t3 = HK_LIT(2);
  const hk_real t4 = (t0 / t3);
  const hk_real t5 = (t4 * t1);
  const hk_real t6 = HK_PI;
  const hk_real t7 = t2 * t2 * t2;
  const hk_real t8 = (t6 * t7);
  const hk_real t9 = HK_LIT(32);
  const hk_real t10 = (t8 / t9);
  const hk_real t11 = (t5 / t10);
  return t11;
}

HK_STATIC hk_real hk_braceHeight(hk_real l_upright, hk_real l_foot, hk_real l_brace, hk_real l_footShort, hk_real l_holes) {
  const hk_real t1 = l_foot;
  const hk_real t2 = l_brace;
  const hk_real t3 = l_footShort;
  const hk_real t5 = t2 * t2;
  const hk_real t6 = (t1 - t3);
  const hk_real t7 = t6 * t6;
  const hk_real t8 = (t5 - t7);
  const hk_real t9 = hk_sqrt(t8);
  return t9;
}

HK_STATIC hk_real hk_cableArea(void) {
  const hk_real t0 = HK_LIT(0.0000015);
  return t0;
}

HK_STATIC hk_real hk_cableDrop(hk_real L, hk_real I) {
  const hk_real t0 = L;
  const hk_real t1 = I;
  const hk_real t2 = HK_LIT(0.0000000172);
  const hk_real t3 = HK_LIT(2);
  const hk_real t4 = (t3 * t0);
  const hk_real t5 = (t2 * t4);
  const hk_real t6 = (t5 * t1);
  const hk_real t7 = HK_LIT(0.0000015);
  const hk_real t8 = (t6 / t7);
  return t8;
}

HK_STATIC hk_real hk_clearance(hk_real l_upright, hk_real l_foot, hk_real l_brace, hk_real l_footShort, hk_real l_holes, hk_real holeDown, hk_real reach) {
  const hk_real t0 = l_upright;
  const hk_real t5 = holeDown;
  const hk_real t6 = reach;
  const hk_real t7 = (t0 - t5);
  const hk_real t8 = (t7 - t6);
  return t8;
}

HK_STATIC void hk_constraints(hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive, hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real HK_ADDR* out) {
  const hk_real t0 = c_chord;
  const hk_real t1 = c_apexH;
  const hk_real t7 = b_zRail;
  const hk_real t9 = b_zBearing;
  const hk_real t12 = HK_LIT(1);
  const hk_real t13 = HK_LIT(0);
  const hk_real t14 = (t13 * t13);
  const hk_real t15 = (t9 * t13);
  const hk_real t16 = (t14 - t15);
  const hk_real t17 = (t9 * t12);
  const hk_real t18 = (t17 - t14);
  const hk_real t19 = (t13 * t12);
  const hk_real t20 = (t14 - t19);
  const hk_real t21 = (t14 - t17);
  const hk_real t22 = (t15 - t14);
  const hk_real t23 = (t19 - t14);
  const hk_real t24 = (t19 - t15);
  const hk_real t25 = (t15 - t19);
  const hk_real t26 = (t14 - t14);
  const hk_real t27 = HK_LIT(2);
  const hk_real t28 = (t0 / t27);
  const hk_real t29 = (t28 * t12);
  const hk_real t30 = (t7 * t13);
  const hk_real t31 = (t29 - t30);
  const hk_real t32 = (t1 * t12);
  const hk_real t33 = (t30 - t32);
  const hk_real t34 = (t1 * t13);
  const hk_real t35 = (t28 * t13);
  const hk_real t36 = (t34 - t35);
  const hk_real t37 = (-t28);
  const hk_real t38 = (t37 * t12);
  const hk_real t39 = (t38 - t30);
  const hk_real t40 = (t37 * t13);
  const hk_real t41 = (t34 - t40);
  out[0] = t12;
  out[1] = t13;
  out[2] = t13;
  out[3] = t16;
  out[4] = t18;
  out[5] = t20;
  out[6] = t13;
  out[7] = t12;
  out[8] = t13;
  out[9] = t21;
  out[10] = t22;
  out[11] = t23;
  out[12] = t13;
  out[13] = t13;
  out[14] = t12;
  out[15] = t24;
  out[16] = t25;
  out[17] = t26;
  out[18] = t13;
  out[19] = t13;
  out[20] = t12;
  out[21] = t31;
  out[22] = t33;
  out[23] = t36;
  out[24] = t13;
  out[25] = t13;
  out[26] = t12;
  out[27] = t39;
  out[28] = t33;
  out[29] = t41;
}

HK_STATIC void hk_constraintsGrooved(hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive, hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real HK_ADDR* out) {
  const hk_real t0 = c_chord;
  const hk_real t1 = c_apexH;
  const hk_real t7 = b_zRail;
  const hk_real t9 = b_zBearing;
  const hk_real t12 = HK_LIT(1);
  const hk_real t13 = HK_LIT(0);
  const hk_real t14 = (t13 * t13);
  const hk_real t15 = (t9 * t13);
  const hk_real t16 = (t14 - t15);
  const hk_real t17 = (t9 * t12);
  const hk_real t18 = (t17 - t14);
  const hk_real t19 = (t13 * t12);
  const hk_real t20 = (t14 - t19);
  const hk_real t21 = (t14 - t17);
  const hk_real t22 = (t15 - t14);
  const hk_real t23 = (t19 - t14);
  const hk_real t24 = (t19 - t15);
  const hk_real t25 = (t15 - t19);
  const hk_real t26 = (t14 - t14);
  const hk_real t27 = HK_LIT(2);
  const hk_real t28 = (t0 / t27);
  const hk_real t29 = (t28 * t12);
  const hk_real t30 = (t7 * t13);
  const hk_real t31 = (t29 - t30);
  const hk_real t32 = (t1 * t12);
  const hk_real t33 = (t30 - t32);
  const hk_real t34 = (t1 * t13);
  const hk_real t35 = (t28 * t13);
  const hk_real t36 = (t34 - t35);
  const hk_real t37 = (-t28);
  const hk_real t38 = (t37 * t12);
  const hk_real t39 = (t38 - t30);
  const hk_real t40 = (t37 * t13);
  const hk_real t41 = (t34 - t40);
  const hk_real t42 = (t7 * t28);
  const hk_real t43 = (t35 - t42);
  const hk_real t44 = (t7 * t1);
  const hk_real t45 = (t44 - t34);
  const hk_real t46 = (t1 * t28);
  const hk_real t47 = (t28 * t1);
  const hk_real t48 = (t46 - t47);
  const hk_real t49 = (t7 * t37);
  const hk_real t50 = (t40 - t49);
  const hk_real t51 = (t1 * t37);
  const hk_real t52 = (t37 * t1);
  const hk_real t53 = (t51 - t52);
  out[0] = t12;
  out[1] = t13;
  out[2] = t13;
  out[3] = t16;
  out[4] = t18;
  out[5] = t20;
  out[6] = t13;
  out[7] = t12;
  out[8] = t13;
  out[9] = t21;
  out[10] = t22;
  out[11] = t23;
  out[12] = t13;
  out[13] = t13;
  out[14] = t12;
  out[15] = t24;
  out[16] = t25;
  out[17] = t26;
  out[18] = t13;
  out[19] = t13;
  out[20] = t12;
  out[21] = t31;
  out[22] = t33;
  out[23] = t36;
  out[24] = t13;
  out[25] = t13;
  out[26] = t12;
  out[27] = t39;
  out[28] = t33;
  out[29] = t41;
  out[30] = t1;
  out[31] = t28;
  out[32] = t13;
  out[33] = t43;
  out[34] = t45;
  out[35] = t48;
  out[36] = t1;
  out[37] = t37;
  out[38] = t13;
  out[39] = t50;
  out[40] = t45;
  out[41] = t53;
}

HK_STATIC hk_real hk_cosTubeCut(void) {
  const hk_real t0 = HK_LIT(3.36);
  const hk_real t1 = HK_LIT(3.2);
  const hk_real t2 = hk_sqrt(t1);
  const hk_real t3 = (t0 - t2);
  const hk_real t4 = HK_LIT(2);
  const hk_real t5 = HK_LIT(4.36);
  const hk_real t6 = (t4 * t2);
  const hk_real t7 = (t5 - t6);
  const hk_real t8 = hk_sqrt(t7);
  const hk_real t9 = (t4 * t8);
  const hk_real t10 = (t3 / t9);
  return t10;
}

HK_STATIC hk_real hk_deadPoint(hk_real ym, hk_real hp, hk_real a, hk_real ze) {
  const hk_real t0 = ym;
  const hk_real t1 = hp;
  const hk_real t2 = a;
  const hk_real t3 = ze;
  const hk_real t4 = (t0 * t2);
  const hk_real t5 = (t1 * t3);
  const bool t6 = (t4 <= t5);
  const hk_real t7 = HK_PI;
  const hk_real t8 = HK_LIT(2);
  const hk_real t9 = (t7 / t8);
  const hk_real t10 = (t0 * t3);
  const hk_real t11 = (t1 * t2);
  const hk_real t12 = (t10 + t11);
  const hk_real t13 = (t4 - t5);
  const hk_real t14 = (t12 / t13);
  const hk_real t15 = hk_atan(t14);
  const hk_real t16 = (t6 ? t9 : t15);
  return t16;
}

HK_STATIC hk_real hk_dishF(void) {
  const hk_real t0 = HK_LIT(1);
  return t0;
}

HK_STATIC hk_real hk_dishHalf(void) {
  const hk_real t0 = HK_LIT(0.8);
  return t0;
}

HK_STATIC hk_real hk_dishR(void) {
  const hk_real t0 = HK_LIT(2);
  return t0;
}

HK_STATIC hk_real hk_dishSide(void) {
  const hk_real t0 = HK_LIT(2);
  const hk_real t1 = HK_LIT(0.8);
  const hk_real t2 = (t0 * t1);
  return t2;
}

HK_STATIC void hk_edgeClipAt(hk_real a, hk_real ze, hk_real t, hk_real HK_ADDR* out) {
  const hk_real t0 = a;
  const hk_real t1 = ze;
  const hk_real t2 = t;
  const hk_real t3 = (-t0);
  const hk_real t4 = hk_cos(t2);
  const hk_real t5 = (t3 * t4);
  const hk_real t6 = (-t1);
  const hk_real t7 = hk_sin(t2);
  const hk_real t8 = (t6 * t7);
  const hk_real t9 = (t5 + t8);
  const hk_real t10 = (-t3);
  const hk_real t11 = (t10 * t7);
  const hk_real t12 = (t6 * t4);
  const hk_real t13 = (t11 + t12);
  out[0] = t9;
  out[1] = t13;
}

HK_STATIC hk_real hk_edgeDepth(hk_real f, hk_real a, hk_real sag, hk_real el) {
  const hk_real t0 = f;
  const hk_real t1 = a;
  const hk_real t2 = sag;
  const hk_real t3 = el;
  const hk_real t4 = (t0 - t2);
  const hk_real t5 = hk_sin(t3);
  const hk_real t6 = (t4 * t5);
  const hk_real t7 = hk_cos(t3);
  const hk_real t8 = (t1 * t7);
  const hk_real t9 = (t6 + t8);
  return t9;
}

HK_STATIC hk_real hk_elPower(hk_real W, hk_real rcm, hk_real t, hk_real omega) {
  const hk_real t0 = W;
  const hk_real t1 = rcm;
  const hk_real t2 = t;
  const hk_real t3 = omega;
  const hk_real t4 = (t0 * t1);
  const hk_real t5 = hk_sin(t2);
  const hk_real t6 = (t4 * t5);
  const hk_real t7 = (t6 * t3);
  return t7;
}

HK_STATIC hk_real hk_elRate(hk_real omegad, hk_real rDrum, hk_real rw) {
  const hk_real t0 = omegad;
  const hk_real t1 = rDrum;
  const hk_real t2 = rw;
  const hk_real t3 = (t0 * t1);
  const hk_real t4 = (t3 / t2);
  return t4;
}

HK_STATIC hk_real hk_facetSpot(hk_real w, hk_real f) {
  const hk_real t0 = w;
  const hk_real t1 = f;
  const hk_real t2 = HK_LIT(0.0093);
  const hk_real t3 = (t1 * t2);
  const hk_real t4 = (t0 + t3);
  return t4;
}

HK_STATIC hk_real hk_focusShift(hk_real h, hk_real eps) {
  const hk_real t0 = h;
  const hk_real t1 = eps;
  const hk_real t2 = hk_sin(t1);
  const hk_real t3 = (t0 * t2);
  return t3;
}

HK_STATIC hk_real hk_hM12(void) {
  const hk_real t0 = HK_LIT(0.00175);
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = HK_PI;
  const hk_real t3 = (t1 * t2);
  const hk_real t4 = (t0 / t3);
  return t4;
}

HK_STATIC hk_real hk_hangerLength(hk_real R, hk_real a, hk_real yr, hk_real dx) {
  const hk_real t0 = R;
  const hk_real t1 = a;
  const hk_real t2 = yr;
  const hk_real t3 = dx;
  const hk_real t4 = t3 * t3;
  const hk_real t5 = t2 * t2;
  const hk_real t6 = (t4 + t5);
  const hk_real t7 = HK_LIT(2);
  const hk_real t8 = (t0 / t7);
  const hk_real t9 = t0 * t0;
  const hk_real t10 = t1 * t1;
  const hk_real t11 = (t10 + t5);
  const hk_real t12 = hk_sqrt(t11);
  const hk_real t13 = t12 * t12;
  const hk_real t14 = (t9 - t13);
  const hk_real t15 = hk_sqrt(t14);
  const hk_real t16 = (t0 - t15);
  const hk_real t17 = (t8 - t16);
  const hk_real t18 = t17 * t17;
  const hk_real t19 = (t6 + t18);
  const hk_real t20 = hk_sqrt(t19);
  return t20;
}

HK_STATIC void hk_hashemi(hk_real HK_ADDR* out) {
  const hk_real t0 = HK_LIT(1.84);
  const hk_real t1 = HK_LIT(0.80);
  const hk_real t2 = HK_LIT(0.98);
  const hk_real t3 = HK_LIT(0.39);
  const hk_real t4 = HK_LIT(0.135);
  const hk_real t5 = HK_LIT(0.05);
  out[0] = t0;
  out[1] = t1;
  out[2] = t2;
  out[3] = t3;
  out[4] = t4;
  out[5] = t5;
}

HK_STATIC void hk_hashemiBase(hk_real HK_ADDR* out) {
  const hk_real t0 = HK_LIT(1.84);
  const hk_real t1 = HK_LIT(0.80);
  const hk_real t6 = HK_LIT(2);
  const hk_real t7 = (t0 / t6);
  const hk_real t8 = t7 * t7;
  const hk_real t9 = t1 * t1;
  const hk_real t10 = (t8 + t9);
  const hk_real t11 = hk_sqrt(t10);
  const hk_real t12 = HK_LIT(0.55);
  const hk_real t13 = HK_LIT(0.75);
  const hk_real t14 = HK_LIT(0.62);
  const hk_real t15 = HK_LIT(0.02);
  const hk_real t16 = HK_LIT(8);
  out[0] = t11;
  out[1] = t12;
  out[2] = t13;
  out[3] = t14;
  out[4] = t15;
  out[5] = t16;
}

HK_STATIC void hk_hashemiHanger(hk_real HK_ADDR* out) {
  const hk_real t0 = HK_LIT(4.36);
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = HK_LIT(3.2);
  const hk_real t3 = hk_sqrt(t2);
  const hk_real t4 = (t1 * t3);
  const hk_real t5 = (t0 - t4);
  const hk_real t6 = hk_sqrt(t5);
  const hk_real t7 = HK_LIT(0.010);
  out[0] = t6;
  out[1] = t7;
}

HK_STATIC void hk_hashemiLeg(hk_real HK_ADDR* out) {
  const hk_real t0 = HK_LIT(1.30);
  const hk_real t1 = HK_LIT(0.62);
  const hk_real t2 = HK_LIT(0.96);
  const hk_real t3 = HK_LIT(0.175);
  const hk_real t4 = HK_LIT(4);
  out[0] = t0;
  out[1] = t1;
  out[2] = t2;
  out[3] = t3;
  out[4] = t4;
}

HK_STATIC void hk_hashemiOutrigger(hk_real HK_ADDR* out) {
  const hk_real t2 = HK_LIT(0.98);
  const hk_real t6 = HK_LIT(1.22);
  const hk_real t7 = HK_LIT(1.35);
  const hk_real t8 = HK_LIT(0.25);
  out[0] = t2;
  out[1] = t6;
  out[2] = t7;
  out[3] = t8;
}

HK_STATIC void hk_hashemiPanel(hk_real HK_ADDR* out) {
  const hk_real t0 = HK_LIT(5);
  out[0] = t0;
}

HK_STATIC void hk_hashemiStand(hk_real HK_ADDR* out) {
  const hk_real t0 = HK_LIT(1.59);
  const hk_real t1 = HK_LIT(1.84);
  const hk_real t2 = HK_LIT(0.41);
  out[0] = t0;
  out[1] = t1;
  out[2] = t2;
}

HK_STATIC hk_real hk_helixAdvance(hk_real pitch, hk_real phi) {
  const hk_real t0 = pitch;
  const hk_real t1 = phi;
  const hk_real t2 = (t0 * t1);
  const hk_real t3 = HK_LIT(2);
  const hk_real t4 = HK_PI;
  const hk_real t5 = (t3 * t4);
  const hk_real t6 = (t2 / t5);
  return t6;
}

HK_STATIC void hk_hingeWrench(hk_real xh, hk_real zBolt, hk_real HK_ADDR* out) {
  const hk_real t0 = xh;
  const hk_real t1 = zBolt;
  const hk_real t2 = HK_LIT(1);
  const hk_real t3 = HK_LIT(0);
  const hk_real t4 = (t3 * t3);
  const hk_real t5 = (t1 * t3);
  const hk_real t6 = (t4 - t5);
  const hk_real t7 = (t1 * t2);
  const hk_real t8 = (t0 * t3);
  const hk_real t9 = (t7 - t8);
  const hk_real t10 = (t3 * t2);
  const hk_real t11 = (t8 - t10);
  const hk_real t12 = (t4 - t7);
  const hk_real t13 = (t5 - t8);
  const hk_real t14 = (t0 * t2);
  const hk_real t15 = (t14 - t4);
  const hk_real t16 = (t10 - t5);
  const hk_real t17 = (t5 - t14);
  const hk_real t18 = (t8 - t4);
  out[0] = t2;
  out[1] = t3;
  out[2] = t3;
  out[3] = t6;
  out[4] = t9;
  out[5] = t11;
  out[6] = t3;
  out[7] = t2;
  out[8] = t3;
  out[9] = t12;
  out[10] = t13;
  out[11] = t15;
  out[12] = t3;
  out[13] = t3;
  out[14] = t2;
  out[15] = t16;
  out[16] = t17;
  out[17] = t18;
  out[18] = t3;
  out[19] = t3;
  out[20] = t3;
  out[21] = t3;
  out[22] = t2;
  out[23] = t3;
  out[24] = t3;
  out[25] = t3;
  out[26] = t3;
  out[27] = t3;
  out[28] = t3;
  out[29] = t2;
}

HK_STATIC hk_real hk_leverAt(hk_real ym, hk_real hp, hk_real a, hk_real ze, hk_real t) {
  const hk_real t0 = ym;
  const hk_real t1 = hp;
  const hk_real t2 = a;
  const hk_real t3 = ze;
  const hk_real t4 = t;
  const hk_real t5 = (-t0);
  const hk_real t6 = (-t2);
  const hk_real t7 = hk_cos(t4);
  const hk_real t8 = (t6 * t7);
  const hk_real t9 = (-t3);
  const hk_real t10 = hk_sin(t4);
  const hk_real t11 = (t9 * t10);
  const hk_real t12 = (t8 + t11);
  const hk_real t13 = (-t6);
  const hk_real t14 = (t13 * t10);
  const hk_real t15 = (t9 * t7);
  const hk_real t16 = (t14 + t15);
  const hk_real t17 = (t5 * t16);
  const hk_real t18 = (t1 * t12);
  const hk_real t19 = (t17 - t18);
  const hk_real t20 = (t12 - t5);
  const hk_real t21 = t20 * t20;
  const hk_real t22 = (t16 - t1);
  const hk_real t23 = t22 * t22;
  const hk_real t24 = (t21 + t23);
  const hk_real t25 = hk_sqrt(t24);
  const hk_real t26 = (t19 / t25);
  return t26;
}

HK_STATIC void hk_pointVel(hk_real t_0, hk_real t_1, hk_real t_2, hk_real t_3, hk_real t_4, hk_real t_5, hk_real p_0, hk_real p_1, hk_real p_2, hk_real HK_ADDR* out) {
  const hk_real t0 = t_0;
  const hk_real t1 = t_1;
  const hk_real t2 = t_2;
  const hk_real t3 = t_3;
  const hk_real t4 = t_4;
  const hk_real t5 = t_5;
  const hk_real t6 = p_0;
  const hk_real t7 = p_1;
  const hk_real t8 = p_2;
  const hk_real t9 = (t1 * t8);
  const hk_real t10 = (t2 * t7);
  const hk_real t11 = (t9 - t10);
  const hk_real t12 = (t11 + t3);
  const hk_real t13 = (t2 * t6);
  const hk_real t14 = (t0 * t8);
  const hk_real t15 = (t13 - t14);
  const hk_real t16 = (t15 + t4);
  const hk_real t17 = (t0 * t7);
  const hk_real t18 = (t1 * t6);
  const hk_real t19 = (t17 - t18);
  const hk_real t20 = (t19 + t5);
  out[0] = t12;
  out[1] = t16;
  out[2] = t20;
}

HK_STATIC void hk_postTop(hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive, hk_real l_upright, hk_real l_foot, hk_real l_brace, hk_real l_footShort, hk_real l_holes, hk_real endIn, hk_real sg, hk_real HK_ADDR* out) {
  const hk_real t0 = c_chord;
  const hk_real t1 = c_apexH;
  const hk_real t6 = l_upright;
  const hk_real t11 = endIn;
  const hk_real t12 = sg;
  const hk_real t13 = HK_LIT(2);
  const hk_real t14 = (t0 / t13);
  const hk_real t15 = (t14 - t11);
  const hk_real t16 = (t12 * t15);
  out[0] = t1;
  out[1] = t16;
  out[2] = t6;
}

HK_STATIC void hk_pulleyAt(hk_real ym, hk_real hp, hk_real HK_ADDR* out) {
  const hk_real t0 = ym;
  const hk_real t1 = hp;
  const hk_real t2 = (-t0);
  out[0] = t2;
  out[1] = t1;
}

HK_STATIC hk_real hk_recip(hk_real t_0, hk_real t_1, hk_real t_2, hk_real t_3, hk_real t_4, hk_real t_5, hk_real w_0, hk_real w_1, hk_real w_2, hk_real w_3, hk_real w_4, hk_real w_5) {
  const hk_real t0 = t_0;
  const hk_real t1 = t_1;
  const hk_real t2 = t_2;
  const hk_real t3 = t_3;
  const hk_real t4 = t_4;
  const hk_real t5 = t_5;
  const hk_real t6 = w_0;
  const hk_real t7 = w_1;
  const hk_real t8 = w_2;
  const hk_real t9 = w_3;
  const hk_real t10 = w_4;
  const hk_real t11 = w_5;
  const hk_real t12 = (t0 * t9);
  const hk_real t13 = (t1 * t10);
  const hk_real t14 = (t12 + t13);
  const hk_real t15 = (t2 * t11);
  const hk_real t16 = (t14 + t15);
  const hk_real t17 = (t3 * t6);
  const hk_real t18 = (t16 + t17);
  const hk_real t19 = (t4 * t7);
  const hk_real t20 = (t18 + t19);
  const hk_real t21 = (t5 * t8);
  const hk_real t22 = (t20 + t21);
  return t22;
}

HK_STATIC hk_real hk_rhoCu(void) {
  const hk_real t0 = HK_LIT(0.0000000172);
  return t0;
}

HK_STATIC hk_real hk_rodTan(void) {
  const hk_real t0 = HK_LIT(0.4);
  const hk_real t1 = HK_LIT(3.2);
  const hk_real t2 = hk_sqrt(t1);
  const hk_real t3 = HK_LIT(1);
  const hk_real t4 = (t2 - t3);
  const hk_real t5 = (t0 / t4);
  return t5;
}

HK_STATIC void hk_rollY(hk_real p_0, hk_real p_1, hk_real p_2, hk_real HK_ADDR* out) {
  const hk_real t0 = p_0;
  const hk_real t1 = p_1;
  const hk_real t2 = p_2;
  const hk_real t3 = HK_LIT(0);
  const hk_real t4 = HK_LIT(1);
  const hk_real t5 = (t1 * t3);
  const hk_real t6 = (t2 * t4);
  const hk_real t7 = (t5 - t6);
  const hk_real t8 = (t2 * t3);
  const hk_real t9 = (t0 * t3);
  const hk_real t10 = (t8 - t9);
  const hk_real t11 = (t0 * t4);
  const hk_real t12 = (t11 - t5);
  out[0] = t3;
  out[1] = t4;
  out[2] = t3;
  out[3] = t7;
  out[4] = t10;
  out[5] = t12;
}

HK_STATIC hk_real hk_rollerRadius(hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive) {
  const hk_real t0 = c_chord;
  const hk_real t1 = c_apexH;
  const hk_real t6 = HK_LIT(2);
  const hk_real t7 = (t0 / t6);
  const hk_real t8 = t7 * t7;
  const hk_real t9 = t1 * t1;
  const hk_real t10 = (t8 + t9);
  const hk_real t11 = hk_sqrt(t10);
  return t11;
}

HK_STATIC void hk_rot(hk_real psi, hk_real p_1, hk_real p_2, hk_real HK_ADDR* out) {
  const hk_real t0 = psi;
  const hk_real t1 = p_1;
  const hk_real t2 = p_2;
  const hk_real t3 = hk_cos(t0);
  const hk_real t4 = (t3 * t1);
  const hk_real t5 = hk_sin(t0);
  const hk_real t6 = (t5 * t2);
  const hk_real t7 = (t4 - t6);
  const hk_real t8 = (t5 * t1);
  const hk_real t9 = (t3 * t2);
  const hk_real t10 = (t8 + t9);
  out[0] = t7;
  out[1] = t10;
}

HK_STATIC hk_real hk_screwLength(hk_real R, hk_real a) {
  const hk_real t0 = R;
  const hk_real t1 = a;
  const hk_real t2 = HK_LIT(2);
  const hk_real t3 = (t0 / t2);
  const hk_real t4 = t0 * t0;
  const hk_real t5 = t1 * t1;
  const hk_real t6 = (t4 - t5);
  const hk_real t7 = hk_sqrt(t6);
  const hk_real t8 = (t0 - t7);
  const hk_real t9 = (t3 - t8);
  return t9;
}

HK_STATIC void hk_screwTwist(hk_real h, hk_real zBolt, hk_real HK_ADDR* out) {
  const hk_real t0 = h;
  const hk_real t1 = zBolt;
  const hk_real t2 = HK_LIT(1);
  const hk_real t3 = HK_LIT(0);
  out[0] = t2;
  out[1] = t3;
  out[2] = t3;
  out[3] = t0;
  out[4] = t1;
  out[5] = t3;
}

HK_STATIC void hk_screwWrench(hk_real xh, hk_real zBolt, hk_real h, hk_real HK_ADDR* out) {
  const hk_real t0 = xh;
  const hk_real t1 = zBolt;
  const hk_real t2 = h;
  const hk_real t3 = HK_LIT(0);
  const hk_real t4 = HK_LIT(1);
  const hk_real t5 = (t3 * t3);
  const hk_real t6 = (t1 * t4);
  const hk_real t7 = (t5 - t6);
  const hk_real t8 = (t1 * t3);
  const hk_real t9 = (t0 * t3);
  const hk_real t10 = (t8 - t9);
  const hk_real t11 = (t0 * t4);
  const hk_real t12 = (t11 - t5);
  const hk_real t13 = (t3 * t4);
  const hk_real t14 = (t13 - t8);
  const hk_real t15 = (t8 - t11);
  const hk_real t16 = (t9 - t5);
  const hk_real t17 = (-t2);
  out[0] = t3;
  out[1] = t4;
  out[2] = t3;
  out[3] = t7;
  out[4] = t10;
  out[5] = t12;
  out[6] = t3;
  out[7] = t3;
  out[8] = t4;
  out[9] = t14;
  out[10] = t15;
  out[11] = t16;
  out[12] = t3;
  out[13] = t3;
  out[14] = t3;
  out[15] = t3;
  out[16] = t4;
  out[17] = t3;
  out[18] = t3;
  out[19] = t3;
  out[20] = t3;
  out[21] = t3;
  out[22] = t3;
  out[23] = t4;
  out[24] = t4;
  out[25] = t3;
  out[26] = t3;
  out[27] = t17;
  out[28] = t1;
  out[29] = t3;
}

HK_STATIC hk_real hk_setLength(hk_real rod, hk_real excess) {
  const hk_real t0 = rod;
  const hk_real t1 = excess;
  const hk_real t2 = (t0 - t1);
  return t2;
}

HK_STATIC hk_real hk_sideGap(void) {
  const hk_real t0 = HK_LIT(1.84);
  const hk_real t6 = HK_LIT(2);
  const hk_real t7 = HK_LIT(0.8);
  const hk_real t8 = (t6 * t7);
  const hk_real t9 = (t0 - t8);
  const hk_real t10 = (t9 / t6);
  return t10;
}

HK_STATIC hk_real hk_slackSpot(hk_real f, hk_real delta, hk_real rw) {
  const hk_real t0 = f;
  const hk_real t1 = delta;
  const hk_real t2 = rw;
  const hk_real t3 = HK_LIT(2);
  const hk_real t4 = (t3 * t0);
  const hk_real t5 = (t4 * t1);
  const hk_real t6 = (t5 / t2);
  return t6;
}

HK_STATIC hk_real hk_slotExit(hk_real a, hk_real ze) {
  const hk_real t0 = a;
  const hk_real t1 = ze;
  const hk_real t2 = (t0 / t1);
  const hk_real t3 = hk_atan(t2);
  return t3;
}

HK_STATIC void hk_step(hk_real az, hk_real t, hk_real omegam, hk_real omegad, hk_real dt, hk_real rw, hk_real R, hk_real rDrum, hk_real ym, hk_real hp, hk_real a, hk_real ze, hk_real f, hk_real h, hk_real HK_ADDR* out) {
  const hk_real t0 = az;
  const hk_real t1 = t;
  const hk_real t2 = omegam;
  const hk_real t3 = omegad;
  const hk_real t4 = dt;
  const hk_real t5 = rw;
  const hk_real t6 = R;
  const hk_real t7 = rDrum;
  const hk_real t8 = ym;
  const hk_real t9 = hp;
  const hk_real t10 = a;
  const hk_real t11 = ze;
  const hk_real t12 = f;
  const hk_real t13 = h;
  const hk_real t14 = (t2 * t5);
  const hk_real t15 = (t14 / t6);
  const hk_real t16 = (t15 * t4);
  const hk_real t17 = (t0 + t16);
  const hk_real t18 = (t3 * t7);
  const hk_real t19 = (-t8);
  const hk_real t20 = (-t10);
  const hk_real t21 = hk_cos(t1);
  const hk_real t22 = (t20 * t21);
  const hk_real t23 = (-t11);
  const hk_real t24 = hk_sin(t1);
  const hk_real t25 = (t23 * t24);
  const hk_real t26 = (t22 + t25);
  const hk_real t27 = (-t20);
  const hk_real t28 = (t27 * t24);
  const hk_real t29 = (t23 * t21);
  const hk_real t30 = (t28 + t29);
  const hk_real t31 = (t19 * t30);
  const hk_real t32 = (t9 * t26);
  const hk_real t33 = (t31 - t32);
  const hk_real t34 = (t26 - t19);
  const hk_real t35 = t34 * t34;
  const hk_real t36 = (t30 - t9);
  const hk_real t37 = t36 * t36;
  const hk_real t38 = (t35 + t37);
  const hk_real t39 = hk_sqrt(t38);
  const hk_real t40 = (t33 / t39);
  const hk_real t41 = (t18 / t40);
  const hk_real t42 = (t41 * t4);
  const hk_real t43 = (t1 + t42);
  const hk_real t44 = HK_LIT(0);
  const bool t45 = (t43 < t44);
  const hk_real t46 = (t8 * t10);
  const hk_real t47 = (t9 * t11);
  const bool t48 = (t46 <= t47);
  const hk_real t49 = HK_PI;
  const hk_real t50 = HK_LIT(2);
  const hk_real t51 = (t49 / t50);
  const hk_real t52 = (t8 * t11);
  const hk_real t53 = (t9 * t10);
  const hk_real t54 = (t52 + t53);
  const hk_real t55 = (t46 - t47);
  const hk_real t56 = (t54 / t55);
  const hk_real t57 = hk_atan(t56);
  const hk_real t58 = (t48 ? t51 : t57);
  const bool t59 = (t58 < t43);
  const hk_real t60 = (t59 ? t58 : t43);
  const hk_real t61 = (t45 ? t44 : t60);
  const hk_real t62 = (t24 / t40);
  const hk_real t63 = hk_cos(t61);
  const hk_real t64 = (t44 * t63);
  const hk_real t65 = (-t12);
  const hk_real t66 = hk_sin(t61);
  const hk_real t67 = (t65 * t66);
  const hk_real t68 = (t64 + t67);
  const hk_real t69 = (-t44);
  const hk_real t70 = (t69 * t66);
  const hk_real t71 = (t65 * t63);
  const hk_real t72 = (t70 + t71);
  const hk_real t73 = HK_LIT(1);
  const hk_real t74 = (t73 * t66);
  const hk_real t75 = (t64 + t74);
  const hk_real t76 = (t73 * t63);
  const hk_real t77 = (t70 + t76);
  const hk_real t78 = (t13 * t61);
  const hk_real t79 = hk_tan(t61);
  const hk_real t80 = (t12 * t79);
  const hk_real t81 = (t10 / t11);
  const hk_real t82 = hk_atan(t81);
  const bool t83 = (t61 < t82);
  const hk_real t84 = (t83 ? t73 : t44);
  const hk_real t85 = (t10 * t66);
  const hk_real t86 = (t11 * t63);
  const hk_real t87 = (t85 + t86);
  out[0] = t17;
  out[1] = t61;
  out[2] = t40;
  out[3] = t62;
  out[4] = t58;
  out[5] = t68;
  out[6] = t72;
  out[7] = t75;
  out[8] = t77;
  out[9] = t78;
  out[10] = t80;
  out[11] = t84;
  out[12] = t87;
}

HK_STATIC void hk_stepParams(hk_real HK_ADDR* out) {
  const hk_real t0 = HK_LIT(1.84);
  const hk_real t1 = HK_LIT(0.80);
  const hk_real t5 = HK_LIT(0.05);
  const hk_real t6 = HK_LIT(2);
  const hk_real t7 = (t0 / t6);
  const hk_real t8 = t7 * t7;
  const hk_real t9 = t1 * t1;
  const hk_real t10 = (t8 + t9);
  const hk_real t11 = hk_sqrt(t10);
  const hk_real t12 = HK_LIT(0.03);
  const hk_real t13 = HK_LIT(1.22);
  const hk_real t14 = HK_LIT(0.34);
  const hk_real t15 = HK_LIT(0.8);
  const hk_real t16 = HK_LIT(3.36);
  const hk_real t17 = hk_sqrt(t16);
  const hk_real t18 = HK_LIT(1);
  const hk_real t19 = (t17 - t18);
  const hk_real t20 = HK_LIT(0.00175);
  const hk_real t21 = HK_PI;
  const hk_real t22 = (t6 * t21);
  const hk_real t23 = (t20 / t22);
  out[0] = t5;
  out[1] = t11;
  out[2] = t12;
  out[3] = t13;
  out[4] = t14;
  out[5] = t15;
  out[6] = t19;
  out[7] = t18;
  out[8] = t23;
}

HK_STATIC hk_real hk_strutStrain(hk_real P_0, hk_real P_1, hk_real P_2, hk_real Q_0, hk_real Q_1, hk_real Q_2, hk_real delta_0, hk_real delta_1, hk_real delta_2) {
  const hk_real t0 = P_0;
  const hk_real t1 = P_1;
  const hk_real t2 = P_2;
  const hk_real t3 = Q_0;
  const hk_real t4 = Q_1;
  const hk_real t5 = Q_2;
  const hk_real t6 = delta_0;
  const hk_real t7 = delta_1;
  const hk_real t8 = delta_2;
  const hk_real t9 = (t0 - t3);
  const hk_real t10 = (t9 * t6);
  const hk_real t11 = (t1 - t4);
  const hk_real t12 = (t11 * t7);
  const hk_real t13 = (t10 + t12);
  const hk_real t14 = (t2 - t5);
  const hk_real t15 = (t14 * t8);
  const hk_real t16 = (t13 + t15);
  return t16;
}

HK_STATIC void hk_swingFocus(hk_real P_1, hk_real P_2, hk_real d, hk_real f, hk_real t, hk_real HK_ADDR* out) {
  const hk_real t0 = P_1;
  const hk_real t1 = P_2;
  const hk_real t2 = d;
  const hk_real t3 = f;
  const hk_real t4 = t;
  const hk_real t5 = hk_sin(t4);
  const hk_real t6 = (t2 * t5);
  const hk_real t7 = (t0 + t6);
  const hk_real t8 = hk_cos(t4);
  const hk_real t9 = (t2 * t8);
  const hk_real t10 = (t1 - t9);
  const hk_real t11 = (-t5);
  const hk_real t12 = (t3 * t11);
  const hk_real t13 = (t7 + t12);
  const hk_real t14 = (t3 * t8);
  const hk_real t15 = (t10 + t14);
  out[0] = t13;
  out[1] = t15;
}

HK_STATIC void hk_swingNormal(hk_real t, hk_real HK_ADDR* out) {
  const hk_real t0 = t;
  const hk_real t1 = hk_sin(t0);
  const hk_real t2 = (-t1);
  const hk_real t3 = hk_cos(t0);
  out[0] = t2;
  out[1] = t3;
}

HK_STATIC void hk_swingTwist(hk_real apexH, hk_real zBolt, hk_real HK_ADDR* out) {
  const hk_real t0 = apexH;
  const hk_real t1 = zBolt;
  const hk_real t2 = HK_LIT(1);
  const hk_real t3 = HK_LIT(0);
  const hk_real t4 = (t3 * t3);
  const hk_real t5 = (t1 * t3);
  const hk_real t6 = (t4 - t5);
  const hk_real t7 = (t1 * t2);
  const hk_real t8 = (t0 * t3);
  const hk_real t9 = (t7 - t8);
  const hk_real t10 = (t3 * t2);
  const hk_real t11 = (t8 - t10);
  out[0] = t2;
  out[1] = t3;
  out[2] = t3;
  out[3] = t6;
  out[4] = t9;
  out[5] = t11;
}

HK_STATIC void hk_swingVertex(hk_real P_1, hk_real P_2, hk_real f, hk_real t, hk_real HK_ADDR* out) {
  const hk_real t0 = P_1;
  const hk_real t1 = P_2;
  const hk_real t2 = f;
  const hk_real t3 = t;
  const hk_real t4 = hk_sin(t3);
  const hk_real t5 = (t2 * t4);
  const hk_real t6 = (t0 + t5);
  const hk_real t7 = hk_cos(t3);
  const hk_real t8 = (t2 * t7);
  const hk_real t9 = (t1 - t8);
  out[0] = t6;
  out[1] = t9;
}

HK_STATIC void hk_swingVertexAt(hk_real P_1, hk_real P_2, hk_real d, hk_real t, hk_real HK_ADDR* out) {
  const hk_real t0 = P_1;
  const hk_real t1 = P_2;
  const hk_real t2 = d;
  const hk_real t3 = t;
  const hk_real t4 = hk_sin(t3);
  const hk_real t5 = (t2 * t4);
  const hk_real t6 = (t0 + t5);
  const hk_real t7 = hk_cos(t3);
  const hk_real t8 = (t2 * t7);
  const hk_real t9 = (t1 - t8);
  out[0] = t6;
  out[1] = t9;
}

HK_STATIC void hk_swungPt(hk_real y0, hk_real z0, hk_real t, hk_real HK_ADDR* out) {
  const hk_real t0 = y0;
  const hk_real t1 = z0;
  const hk_real t2 = t;
  const hk_real t3 = hk_cos(t2);
  const hk_real t4 = (t0 * t3);
  const hk_real t5 = hk_sin(t2);
  const hk_real t6 = (t1 * t5);
  const hk_real t7 = (t4 + t6);
  const hk_real t8 = (-t0);
  const hk_real t9 = (t8 * t5);
  const hk_real t10 = (t1 * t3);
  const hk_real t11 = (t9 + t10);
  out[0] = t7;
  out[1] = t11;
}

HK_STATIC hk_real hk_systemVolts(void) {
  const hk_real t0 = HK_LIT(12);
  return t0;
}

HK_STATIC hk_real hk_tiltOfMismatch(hk_real e) {
  const hk_real t0 = e;
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = HK_LIT(0.8);
  const hk_real t3 = (t1 * t2);
  const hk_real t4 = (t0 / t3);
  return t4;
}

HK_STATIC void hk_wBearX(hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real HK_ADDR* out) {
  const hk_real t3 = b_zBearing;
  const hk_real t6 = HK_LIT(1);
  const hk_real t7 = HK_LIT(0);
  const hk_real t8 = (t7 * t7);
  const hk_real t9 = (t3 * t7);
  const hk_real t10 = (t8 - t9);
  const hk_real t11 = (t3 * t6);
  const hk_real t12 = (t11 - t8);
  const hk_real t13 = (t7 * t6);
  const hk_real t14 = (t8 - t13);
  out[0] = t6;
  out[1] = t7;
  out[2] = t7;
  out[3] = t10;
  out[4] = t12;
  out[5] = t14;
}

HK_STATIC void hk_wBearY(hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real HK_ADDR* out) {
  const hk_real t3 = b_zBearing;
  const hk_real t6 = HK_LIT(0);
  const hk_real t7 = HK_LIT(1);
  const hk_real t8 = (t6 * t6);
  const hk_real t9 = (t3 * t7);
  const hk_real t10 = (t8 - t9);
  const hk_real t11 = (t3 * t6);
  const hk_real t12 = (t11 - t8);
  const hk_real t13 = (t6 * t7);
  const hk_real t14 = (t13 - t8);
  out[0] = t6;
  out[1] = t7;
  out[2] = t6;
  out[3] = t10;
  out[4] = t12;
  out[5] = t14;
}

HK_STATIC void hk_wDrive(hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive, hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real F, hk_real HK_ADDR* out) {
  const hk_real t0 = c_chord;
  const hk_real t1 = c_apexH;
  const hk_real t7 = b_zRail;
  const hk_real t12 = F;
  const hk_real t13 = HK_LIT(2);
  const hk_real t14 = (t0 / t13);
  const hk_real t15 = (t12 * t14);
  const hk_real t16 = t14 * t14;
  const hk_real t17 = t1 * t1;
  const hk_real t18 = (t16 + t17);
  const hk_real t19 = hk_sqrt(t18);
  const hk_real t20 = (t15 / t19);
  const hk_real t21 = (-t20);
  const hk_real t22 = (t12 * t1);
  const hk_real t23 = (t22 / t19);
  const hk_real t24 = HK_LIT(0);
  const hk_real t25 = (t14 * t24);
  const hk_real t26 = (t7 * t23);
  const hk_real t27 = (t25 - t26);
  const hk_real t28 = (t7 * t21);
  const hk_real t29 = (t1 * t24);
  const hk_real t30 = (t28 - t29);
  const hk_real t31 = (t1 * t23);
  const hk_real t32 = (t14 * t21);
  const hk_real t33 = (t31 - t32);
  out[0] = t21;
  out[1] = t23;
  out[2] = t24;
  out[3] = t27;
  out[4] = t30;
  out[5] = t33;
}

HK_STATIC void hk_wRollN(hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive, hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real HK_ADDR* out) {
  const hk_real t0 = c_chord;
  const hk_real t1 = c_apexH;
  const hk_real t7 = b_zRail;
  const hk_real t12 = HK_LIT(0);
  const hk_real t13 = HK_LIT(1);
  const hk_real t14 = HK_LIT(2);
  const hk_real t15 = (t0 / t14);
  const hk_real t16 = (-t15);
  const hk_real t17 = (t16 * t13);
  const hk_real t18 = (t7 * t12);
  const hk_real t19 = (t17 - t18);
  const hk_real t20 = (t1 * t13);
  const hk_real t21 = (t18 - t20);
  const hk_real t22 = (t1 * t12);
  const hk_real t23 = (t16 * t12);
  const hk_real t24 = (t22 - t23);
  out[0] = t12;
  out[1] = t12;
  out[2] = t13;
  out[3] = t19;
  out[4] = t21;
  out[5] = t24;
}

HK_STATIC void hk_wRollNr(hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive, hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real HK_ADDR* out) {
  const hk_real t0 = c_chord;
  const hk_real t1 = c_apexH;
  const hk_real t7 = b_zRail;
  const hk_real t12 = HK_LIT(2);
  const hk_real t13 = (t0 / t12);
  const hk_real t14 = (-t13);
  const hk_real t15 = HK_LIT(0);
  const hk_real t16 = (t14 * t15);
  const hk_real t17 = (t7 * t14);
  const hk_real t18 = (t16 - t17);
  const hk_real t19 = (t7 * t1);
  const hk_real t20 = (t1 * t15);
  const hk_real t21 = (t19 - t20);
  const hk_real t22 = (t1 * t14);
  const hk_real t23 = (t14 * t1);
  const hk_real t24 = (t22 - t23);
  out[0] = t1;
  out[1] = t14;
  out[2] = t15;
  out[3] = t18;
  out[4] = t21;
  out[5] = t24;
}

HK_STATIC void hk_wRollP(hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive, hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real HK_ADDR* out) {
  const hk_real t0 = c_chord;
  const hk_real t1 = c_apexH;
  const hk_real t7 = b_zRail;
  const hk_real t12 = HK_LIT(0);
  const hk_real t13 = HK_LIT(1);
  const hk_real t14 = HK_LIT(2);
  const hk_real t15 = (t0 / t14);
  const hk_real t16 = (t15 * t13);
  const hk_real t17 = (t7 * t12);
  const hk_real t18 = (t16 - t17);
  const hk_real t19 = (t1 * t13);
  const hk_real t20 = (t17 - t19);
  const hk_real t21 = (t1 * t12);
  const hk_real t22 = (t15 * t12);
  const hk_real t23 = (t21 - t22);
  out[0] = t12;
  out[1] = t12;
  out[2] = t13;
  out[3] = t18;
  out[4] = t20;
  out[5] = t23;
}

HK_STATIC void hk_wRollPr(hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive, hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real HK_ADDR* out) {
  const hk_real t0 = c_chord;
  const hk_real t1 = c_apexH;
  const hk_real t7 = b_zRail;
  const hk_real t12 = HK_LIT(2);
  const hk_real t13 = (t0 / t12);
  const hk_real t14 = HK_LIT(0);
  const hk_real t15 = (t13 * t14);
  const hk_real t16 = (t7 * t13);
  const hk_real t17 = (t15 - t16);
  const hk_real t18 = (t7 * t1);
  const hk_real t19 = (t1 * t14);
  const hk_real t20 = (t18 - t19);
  const hk_real t21 = (t1 * t13);
  const hk_real t22 = (t13 * t1);
  const hk_real t23 = (t21 - t22);
  out[0] = t1;
  out[1] = t13;
  out[2] = t14;
  out[3] = t17;
  out[4] = t20;
  out[5] = t23;
}

HK_STATIC void hk_wStop(hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real HK_ADDR* out) {
  const hk_real t3 = b_zBearing;
  const hk_real t6 = HK_LIT(0);
  const hk_real t7 = HK_LIT(1);
  const hk_real t8 = (t6 * t7);
  const hk_real t9 = (t3 * t6);
  const hk_real t10 = (t8 - t9);
  const hk_real t11 = (t9 - t8);
  const hk_real t12 = (t6 * t6);
  const hk_real t13 = (t12 - t12);
  out[0] = t6;
  out[1] = t6;
  out[2] = t7;
  out[3] = t10;
  out[4] = t11;
  out[5] = t13;
}

HK_STATIC hk_real hk_wireLever(hk_real P_1, hk_real P_2, hk_real B_1, hk_real B_2) {
  const hk_real t0 = P_1;
  const hk_real t1 = P_2;
  const hk_real t2 = B_1;
  const hk_real t3 = B_2;
  const hk_real t4 = (t0 * t3);
  const hk_real t5 = (t1 * t2);
  const hk_real t6 = (t4 - t5);
  const hk_real t7 = (t2 - t0);
  const hk_real t8 = t7 * t7;
  const hk_real t9 = (t3 - t1);
  const hk_real t10 = t9 * t9;
  const hk_real t11 = (t8 + t10);
  const hk_real t12 = hk_sqrt(t11);
  const hk_real t13 = (t6 / t12);
  return t13;
}

HK_STATIC hk_real hk_wireTension(hk_real W, hk_real rcm, hk_real rw, hk_real t) {
  const hk_real t0 = W;
  const hk_real t1 = rcm;
  const hk_real t2 = rw;
  const hk_real t3 = t;
  const hk_real t4 = (t0 * t1);
  const hk_real t5 = hk_sin(t3);
  const hk_real t6 = (t4 * t5);
  const hk_real t7 = (t6 / t2);
  return t7;
}

HK_STATIC void hk_wrenchAt(hk_real p_0, hk_real p_1, hk_real p_2, hk_real f_0, hk_real f_1, hk_real f_2, hk_real HK_ADDR* out) {
  const hk_real t0 = p_0;
  const hk_real t1 = p_1;
  const hk_real t2 = p_2;
  const hk_real t3 = f_0;
  const hk_real t4 = f_1;
  const hk_real t5 = f_2;
  const hk_real t6 = (t1 * t5);
  const hk_real t7 = (t2 * t4);
  const hk_real t8 = (t6 - t7);
  const hk_real t9 = (t2 * t3);
  const hk_real t10 = (t0 * t5);
  const hk_real t11 = (t9 - t10);
  const hk_real t12 = (t0 * t4);
  const hk_real t13 = (t1 * t3);
  const hk_real t14 = (t12 - t13);
  out[0] = t3;
  out[1] = t4;
  out[2] = t5;
  out[3] = t8;
  out[4] = t11;
  out[5] = t14;
}

HK_STATIC void hk_yaw(hk_real HK_ADDR* out) {
  const hk_real t0 = HK_LIT(0);
  const hk_real t1 = HK_LIT(1);
  out[0] = t0;
  out[1] = t0;
  out[2] = t1;
  out[3] = t0;
  out[4] = t0;
  out[5] = t0;
}

HK_STATIC hk_real hk_ymHashemi(void) {
  const hk_real t0 = HK_LIT(1.22);
  return t0;
}

/* ---- the requirements (Props), as predicates ---- */
HK_STATIC bool hk_Fits(hk_real b_rRail, hk_real b_zRail, hk_real b_zTube, hk_real b_zBearing, hk_real b_dPipe, hk_real b_nSpokes, hk_real c_chord, hk_real c_apexH, hk_real c_aBase, hk_real c_cross, hk_real c_barW, hk_real c_rDrive) {
  const hk_real t0 = b_rRail;
  const hk_real t6 = c_chord;
  const hk_real t7 = c_apexH;
  const hk_real t12 = HK_LIT(2);
  const hk_real t13 = (t6 / t12);
  const hk_real t14 = t13 * t13;
  const hk_real t15 = t7 * t7;
  const hk_real t16 = (t14 + t15);
  const hk_real t17 = hk_sqrt(t16);
  const bool t18 = hk_eq(t0, t17);
  return t18;
}

HK_STATIC bool hk_HangerClearsPost(hk_real eyeOffset, hk_real dRod) {
  const hk_real t0 = eyeOffset;
  const hk_real t1 = dRod;
  const hk_real t2 = HK_LIT(2);
  const hk_real t3 = (t1 / t2);
  const bool t4 = (t3 < t0);
  return t4;
}

HK_STATIC bool hk_HoldsDish(hk_real Tmax, hk_real W, hk_real rcm, hk_real rw) {
  const hk_real t0 = Tmax;
  const hk_real t1 = W;
  const hk_real t2 = rcm;
  const hk_real t3 = rw;
  const hk_real t4 = (t1 * t2);
  const hk_real t5 = (t0 * t3);
  const bool t6 = (t4 <= t5);
  return t6;
}

HK_STATIC bool hk_MastClears(hk_real ym, hk_real a, hk_real ze) {
  const hk_real t0 = ym;
  const hk_real t1 = a;
  const hk_real t2 = ze;
  const hk_real t3 = t1 * t1;
  const hk_real t4 = t2 * t2;
  const hk_real t5 = (t3 + t4);
  const hk_real t6 = hk_sqrt(t5);
  const bool t7 = (t6 < t0);
  return t7;
}

HK_STATIC bool hk_ReachesVertical(hk_real ym, hk_real hp, hk_real a, hk_real ze) {
  const hk_real t0 = ym;
  const hk_real t1 = hp;
  const hk_real t2 = a;
  const hk_real t3 = ze;
  const hk_real t4 = (t0 * t2);
  const hk_real t5 = (t1 * t3);
  const bool t6 = (t4 <= t5);
  return t6;
}

HK_STATIC bool hk_SlackHarmless(hk_real f, hk_real eps, hk_real delta, hk_real h) {
  const hk_real t0 = f;
  const hk_real t1 = eps;
  const hk_real t2 = delta;
  const hk_real t3 = h;
  const hk_real t4 = hk_tan(t1);
  const hk_real t5 = (t0 * t4);
  const hk_real t6 = (t5 + t2);
  const bool t7 = (t6 <= t3);
  return t7;
}

HK_STATIC bool hk_TrackerBudget(hk_real f, hk_real eps, hk_real h) {
  const hk_real t0 = f;
  const hk_real t1 = eps;
  const hk_real t2 = h;
  const hk_real t3 = hk_tan(t1);
  const hk_real t4 = (t0 * t3);
  const bool t5 = (t4 <= t2);
  return t5;
}

/* ---- closed theorem statements, as checks (true in exact arithmetic; here in hk_real) ---- */
HK_STATIC bool hk_check_AH_bounds(void) {
  const hk_real t0 = HK_LIT(1.833);
  const hk_real t1 = HK_LIT(3.36);
  const hk_real t2 = hk_sqrt(t1);
  const bool t3 = (t0 < t2);
  const hk_real t4 = HK_LIT(1.8331);
  const bool t5 = (t2 < t4);
  const bool t6 = (t3 && t5);
  return t6;
}

HK_STATIC bool hk_check_FC_bounds(void) {
  const hk_real t0 = HK_LIT(1.154);
  const hk_real t1 = HK_LIT(5);
  const hk_real t2 = HK_LIT(2);
  const hk_real t3 = HK_LIT(3.36);
  const hk_real t4 = hk_sqrt(t3);
  const hk_real t5 = (t2 * t4);
  const hk_real t6 = (t1 - t5);
  const hk_real t7 = hk_sqrt(t6);
  const bool t8 = (t0 < t7);
  const hk_real t9 = HK_LIT(1.1551);
  const bool t10 = (t7 < t9);
  const bool t11 = (t8 && t10);
  return t11;
}

HK_STATIC bool hk_check_FC_eq(void) {
  const hk_real t0 = HK_LIT(1);
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = t1 * t1;
  const hk_real t3 = HK_LIT(0.8);
  const hk_real t4 = t3 * t3;
  const hk_real t5 = (t2 - t4);
  const hk_real t6 = hk_sqrt(t5);
  const hk_real t7 = (t1 - t6);
  const hk_real t8 = (t0 - t7);
  const hk_real t9 = t8 * t8;
  const hk_real t10 = (t9 + t4);
  const hk_real t11 = hk_sqrt(t10);
  const hk_real t12 = HK_LIT(5);
  const hk_real t13 = HK_LIT(3.36);
  const hk_real t14 = hk_sqrt(t13);
  const hk_real t15 = (t1 * t14);
  const hk_real t16 = (t12 - t15);
  const hk_real t17 = hk_sqrt(t16);
  const bool t18 = hk_eq(t11, t17);
  return t18;
}

HK_STATIC bool hk_check_FH_bounds(void) {
  const hk_real t0 = HK_LIT(0.833);
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = (t1 / t1);
  const hk_real t3 = t1 * t1;
  const hk_real t4 = HK_LIT(0.8);
  const hk_real t5 = t4 * t4;
  const hk_real t6 = (t3 - t5);
  const hk_real t7 = hk_sqrt(t6);
  const hk_real t8 = (t1 - t7);
  const hk_real t9 = (t2 - t8);
  const bool t10 = (t0 < t9);
  const hk_real t11 = HK_LIT(0.8331);
  const bool t12 = (t9 < t11);
  const bool t13 = (t10 && t12);
  return t13;
}

HK_STATIC bool hk_check_FH_eq(void) {
  const hk_real t0 = HK_LIT(2);
  const hk_real t1 = (t0 / t0);
  const hk_real t2 = t0 * t0;
  const hk_real t3 = HK_LIT(0.8);
  const hk_real t4 = t3 * t3;
  const hk_real t5 = (t2 - t4);
  const hk_real t6 = hk_sqrt(t5);
  const hk_real t7 = (t0 - t6);
  const hk_real t8 = (t1 - t7);
  const hk_real t9 = HK_LIT(3.36);
  const hk_real t10 = hk_sqrt(t9);
  const hk_real t11 = HK_LIT(1);
  const hk_real t12 = (t10 - t11);
  const bool t13 = hk_eq(t8, t12);
  return t13;
}

HK_STATIC bool hk_check_HD_bounds(void) {
  const hk_real t0 = HK_LIT(0.166);
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = t1 * t1;
  const hk_real t3 = HK_LIT(0.8);
  const hk_real t4 = t3 * t3;
  const hk_real t5 = (t2 - t4);
  const hk_real t6 = hk_sqrt(t5);
  const hk_real t7 = (t1 - t6);
  const bool t8 = (t0 < t7);
  const hk_real t9 = HK_LIT(0.168);
  const bool t10 = (t7 < t9);
  const bool t11 = (t8 && t10);
  return t11;
}

HK_STATIC bool hk_check_HD_eq(void) {
  const hk_real t0 = HK_LIT(2);
  const hk_real t1 = t0 * t0;
  const hk_real t2 = HK_LIT(0.8);
  const hk_real t3 = t2 * t2;
  const hk_real t4 = (t1 - t3);
  const hk_real t5 = hk_sqrt(t4);
  const hk_real t6 = (t0 - t5);
  const hk_real t7 = HK_LIT(3.36);
  const hk_real t8 = hk_sqrt(t7);
  const hk_real t9 = (t0 - t8);
  const bool t10 = hk_eq(t6, t9);
  return t10;
}

HK_STATIC bool hk_check_braceHeight_hashemi(void) {
  const hk_real t0 = HK_LIT(0.85);
  const hk_real t2 = HK_LIT(0.62);
  const hk_real t3 = HK_LIT(0.96);
  const hk_real t4 = HK_LIT(0.175);
  const hk_real t6 = t3 * t3;
  const hk_real t7 = (t2 - t4);
  const hk_real t8 = t7 * t7;
  const hk_real t9 = (t6 - t8);
  const hk_real t10 = hk_sqrt(t9);
  const bool t11 = (t0 < t10);
  const hk_real t12 = HK_LIT(0.851);
  const bool t13 = (t10 < t12);
  const bool t14 = (t11 && t13);
  return t14;
}

HK_STATIC bool hk_check_brace_cuts_moment(void) {
  const hk_real t0 = HK_LIT(1.30);
  const hk_real t1 = HK_LIT(0.62);
  const hk_real t2 = HK_LIT(0.96);
  const hk_real t3 = HK_LIT(0.175);
  const hk_real t5 = t2 * t2;
  const hk_real t6 = (t1 - t3);
  const hk_real t7 = t6 * t6;
  const hk_real t8 = (t5 - t7);
  const hk_real t9 = hk_sqrt(t8);
  const hk_real t10 = (t0 - t9);
  const hk_real t11 = (t10 / t0);
  const hk_real t12 = HK_LIT(0.35);
  const bool t13 = (t11 < t12);
  return t13;
}

HK_STATIC bool hk_check_brace_stiffens(void) {
  const hk_real t0 = HK_LIT(1.30);
  const hk_real t1 = HK_LIT(0.62);
  const hk_real t2 = HK_LIT(0.96);
  const hk_real t3 = HK_LIT(0.175);
  const hk_real t5 = t2 * t2;
  const hk_real t6 = (t1 - t3);
  const hk_real t7 = t6 * t6;
  const hk_real t8 = (t5 - t7);
  const hk_real t9 = hk_sqrt(t8);
  const hk_real t10 = (t0 - t9);
  const hk_real t11 = (t10 / t0);
  const hk_real t12 = t11 * t11 * t11;
  const hk_real t13 = HK_LIT(1);
  const hk_real t14 = HK_LIT(24);
  const hk_real t15 = (t13 / t14);
  const bool t16 = (t12 < t15);
  return t16;
}

HK_STATIC bool hk_check_cosTubeCut_bounds(void) {
  const hk_real t0 = HK_LIT(0.888);
  const hk_real t1 = HK_LIT(3.36);
  const hk_real t2 = HK_LIT(3.2);
  const hk_real t3 = hk_sqrt(t2);
  const hk_real t4 = (t1 - t3);
  const hk_real t5 = HK_LIT(2);
  const hk_real t6 = HK_LIT(4.36);
  const hk_real t7 = (t5 * t3);
  const hk_real t8 = (t6 - t7);
  const hk_real t9 = hk_sqrt(t8);
  const hk_real t10 = (t5 * t9);
  const hk_real t11 = (t4 / t10);
  const bool t12 = (t0 < t11);
  const hk_real t13 = HK_LIT(0.889);
  const bool t14 = (t11 < t13);
  const bool t15 = (t12 && t14);
  return t15;
}

HK_STATIC bool hk_check_deadTan_at_ym(void) {
  const hk_real t0 = HK_LIT(1.859);
  const hk_real t1 = HK_LIT(1.22);
  const hk_real t2 = HK_LIT(3.36);
  const hk_real t3 = hk_sqrt(t2);
  const hk_real t4 = HK_LIT(1);
  const hk_real t5 = (t3 - t4);
  const hk_real t6 = (t1 * t5);
  const hk_real t7 = HK_LIT(0.34);
  const hk_real t8 = HK_LIT(0.8);
  const hk_real t9 = (t7 * t8);
  const hk_real t10 = (t6 + t9);
  const hk_real t11 = (t1 * t8);
  const hk_real t12 = (t7 * t5);
  const hk_real t13 = (t11 - t12);
  const hk_real t14 = (t10 / t13);
  const bool t15 = (t0 < t14);
  const hk_real t16 = HK_LIT(1.86);
  const bool t17 = (t14 < t16);
  const bool t18 = (t15 && t17);
  return t18;
}

HK_STATIC bool hk_check_deadTan_hashemi(void) {
  const hk_real t0 = HK_LIT(1.878);
  const hk_real t1 = HK_LIT(1.2);
  const hk_real t2 = HK_LIT(3.36);
  const hk_real t3 = hk_sqrt(t2);
  const hk_real t4 = HK_LIT(1);
  const hk_real t5 = (t3 - t4);
  const hk_real t6 = (t1 * t5);
  const hk_real t7 = HK_LIT(0.34);
  const hk_real t8 = HK_LIT(0.8);
  const hk_real t9 = (t7 * t8);
  const hk_real t10 = (t6 + t9);
  const hk_real t11 = (t1 * t8);
  const hk_real t12 = (t7 * t5);
  const hk_real t13 = (t11 - t12);
  const hk_real t14 = (t10 / t13);
  const bool t15 = (t0 < t14);
  const hk_real t16 = HK_LIT(1.88);
  const bool t17 = (t14 < t16);
  const bool t18 = (t15 && t17);
  return t18;
}

HK_STATIC bool hk_check_dish_between_posts(void) {
  const hk_real t0 = HK_LIT(2);
  const hk_real t1 = HK_LIT(0.8);
  const hk_real t2 = (t0 * t1);
  const hk_real t3 = HK_LIT(1.84);
  const bool t9 = (t2 < t3);
  return t9;
}

HK_STATIC bool hk_check_dish_swings_to_vertical(void) {
  const hk_real t0 = HK_LIT(0.8);
  const hk_real t1 = HK_LIT(1.30);
  const hk_real t6 = HK_LIT(0.05);
  const hk_real t7 = (t1 - t6);
  const bool t8 = (t0 < t7);
  return t8;
}

HK_STATIC bool hk_check_facetSpot_hashemi(void) {
  const hk_real t0 = HK_LIT(0.05);
  const hk_real t1 = HK_LIT(1);
  const hk_real t2 = HK_LIT(0.0093);
  const hk_real t3 = (t1 * t2);
  const hk_real t4 = (t0 + t3);
  const hk_real t5 = HK_LIT(0.0593);
  const bool t6 = hk_eq(t4, t5);
  return t6;
}

HK_STATIC bool hk_check_hangerLength_bounds(void) {
  const hk_real t0 = HK_LIT(0.884);
  const hk_real t1 = HK_LIT(4.36);
  const hk_real t2 = HK_LIT(2);
  const hk_real t3 = HK_LIT(3.2);
  const hk_real t4 = hk_sqrt(t3);
  const hk_real t5 = (t2 * t4);
  const hk_real t6 = (t1 - t5);
  const hk_real t7 = hk_sqrt(t6);
  const bool t8 = (t0 < t7);
  const hk_real t9 = HK_LIT(0.8846);
  const bool t10 = (t7 < t9);
  const bool t11 = (t8 && t10);
  return t11;
}

HK_STATIC bool hk_check_hangerLength_halfEdge(void) {
  const hk_real t0 = HK_LIT(0);
  const hk_real t1 = t0 * t0;
  const hk_real t2 = HK_LIT(0.4);
  const hk_real t3 = t2 * t2;
  const hk_real t4 = (t1 + t3);
  const hk_real t5 = HK_LIT(2);
  const hk_real t6 = (t5 / t5);
  const hk_real t7 = t5 * t5;
  const hk_real t8 = HK_LIT(0.8);
  const hk_real t9 = t8 * t8;
  const hk_real t10 = (t9 + t3);
  const hk_real t11 = hk_sqrt(t10);
  const hk_real t12 = t11 * t11;
  const hk_real t13 = (t7 - t12);
  const hk_real t14 = hk_sqrt(t13);
  const hk_real t15 = (t5 - t14);
  const hk_real t16 = (t6 - t15);
  const hk_real t17 = t16 * t16;
  const hk_real t18 = (t4 + t17);
  const hk_real t19 = hk_sqrt(t18);
  const hk_real t20 = HK_LIT(4.36);
  const hk_real t21 = HK_LIT(3.2);
  const hk_real t22 = hk_sqrt(t21);
  const hk_real t23 = (t5 * t22);
  const hk_real t24 = (t20 - t23);
  const hk_real t25 = hk_sqrt(t24);
  const bool t26 = hk_eq(t19, t25);
  return t26;
}

HK_STATIC bool hk_check_hashemiHanger_length(void) {
  const hk_real t0 = HK_LIT(4.36);
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = HK_LIT(3.2);
  const hk_real t3 = hk_sqrt(t2);
  const hk_real t4 = (t1 * t3);
  const hk_real t5 = (t0 - t4);
  const hk_real t6 = hk_sqrt(t5);
  const hk_real t8 = HK_LIT(0);
  const hk_real t9 = t8 * t8;
  const hk_real t10 = HK_LIT(0.4);
  const hk_real t11 = t10 * t10;
  const hk_real t12 = (t9 + t11);
  const hk_real t13 = (t1 / t1);
  const hk_real t14 = t1 * t1;
  const hk_real t15 = HK_LIT(0.8);
  const hk_real t16 = t15 * t15;
  const hk_real t17 = (t16 + t11);
  const hk_real t18 = hk_sqrt(t17);
  const hk_real t19 = t18 * t18;
  const hk_real t20 = (t14 - t19);
  const hk_real t21 = hk_sqrt(t20);
  const hk_real t22 = (t1 - t21);
  const hk_real t23 = (t13 - t22);
  const hk_real t24 = t23 * t23;
  const hk_real t25 = (t12 + t24);
  const hk_real t26 = hk_sqrt(t25);
  const bool t27 = hk_eq(t6, t26);
  return t27;
}

HK_STATIC bool hk_check_hashemi_clearance(void) {
  const hk_real t0 = HK_LIT(0.1449);
  const hk_real t1 = HK_LIT(1.30);
  const hk_real t6 = HK_LIT(5);
  const hk_real t7 = HK_LIT(2);
  const hk_real t8 = HK_LIT(3.36);
  const hk_real t9 = hk_sqrt(t8);
  const hk_real t10 = (t7 * t9);
  const hk_real t11 = (t6 - t10);
  const hk_real t12 = hk_sqrt(t11);
  const hk_real t13 = (t1 - t12);
  const bool t14 = (t0 < t13);
  const hk_real t15 = HK_LIT(0.146);
  const bool t16 = (t13 < t15);
  const bool t17 = (t14 && t16);
  return t17;
}

HK_STATIC bool hk_check_hashemi_eyes_clear(void) {
  const hk_real t1 = HK_LIT(2);
  const hk_real t7 = HK_LIT(0.010);
  const hk_real t8 = (t7 / t1);
  const bool t9 = (t8 < t7);
  return t9;
}

HK_STATIC bool hk_check_hashemi_fits(void) {
  const hk_real t0 = HK_LIT(1.84);
  const hk_real t1 = HK_LIT(0.80);
  const hk_real t6 = HK_LIT(2);
  const hk_real t7 = (t0 / t6);
  const hk_real t8 = t7 * t7;
  const hk_real t9 = t1 * t1;
  const hk_real t10 = (t8 + t9);
  const hk_real t11 = hk_sqrt(t10);
  const bool t17 = hk_eq(t11, t11);
  return t17;
}

HK_STATIC bool hk_check_helixAdvance_small(void) {
  const hk_real t0 = HK_LIT(0.00175);
  const hk_real t1 = HK_LIT(62);
  const hk_real t2 = HK_PI;
  const hk_real t3 = (t1 * t2);
  const hk_real t4 = HK_LIT(180);
  const hk_real t5 = (t3 / t4);
  const hk_real t6 = (t0 * t5);
  const hk_real t7 = HK_LIT(2);
  const hk_real t8 = (t7 * t2);
  const hk_real t9 = (t6 / t8);
  const hk_real t10 = HK_LIT(0.00031);
  const bool t11 = (t9 < t10);
  return t11;
}

HK_STATIC bool hk_check_lean_one_degree(void) {
  const hk_real t0 = HK_LIT(0.02);
  const hk_real t1 = HK_LIT(1.25);
  const hk_real t2 = HK_PI;
  const hk_real t3 = HK_LIT(180);
  const hk_real t4 = (t2 / t3);
  const hk_real t5 = hk_sin(t4);
  const hk_real t6 = (t1 * t5);
  const bool t7 = (t0 < t6);
  return t7;
}

HK_STATIC bool hk_check_lowestSun_tan_at_ym(void) {
  const hk_real t0 = HK_LIT(0.537);
  const hk_real t1 = HK_LIT(1);
  const hk_real t2 = HK_LIT(1.22);
  const hk_real t3 = HK_LIT(3.36);
  const hk_real t4 = hk_sqrt(t3);
  const hk_real t5 = (t4 - t1);
  const hk_real t6 = (t2 * t5);
  const hk_real t7 = HK_LIT(0.34);
  const hk_real t8 = HK_LIT(0.8);
  const hk_real t9 = (t7 * t8);
  const hk_real t10 = (t6 + t9);
  const hk_real t11 = (t2 * t8);
  const hk_real t12 = (t7 * t5);
  const hk_real t13 = (t11 - t12);
  const hk_real t14 = (t10 / t13);
  const hk_real t15 = (t1 / t14);
  const bool t16 = (t0 < t15);
  const hk_real t17 = HK_LIT(0.538);
  const bool t18 = (t15 < t17);
  const bool t19 = (t16 && t18);
  return t19;
}

HK_STATIC bool hk_check_mastClears_hashemi(void) {
  const hk_real t0 = HK_LIT(0.8);
  const hk_real t1 = t0 * t0;
  const hk_real t2 = HK_LIT(3.36);
  const hk_real t3 = hk_sqrt(t2);
  const hk_real t4 = HK_LIT(1);
  const hk_real t5 = (t3 - t4);
  const hk_real t6 = t5 * t5;
  const hk_real t7 = (t1 + t6);
  const hk_real t8 = hk_sqrt(t7);
  const hk_real t9 = HK_LIT(1.22);
  const bool t10 = (t8 < t9);
  return t10;
}

HK_STATIC bool hk_check_mast_beyond_ring(void) {
  const hk_real t0 = HK_LIT(1.84);
  const hk_real t1 = HK_LIT(0.80);
  const hk_real t6 = HK_LIT(2);
  const hk_real t7 = (t0 / t6);
  const hk_real t8 = t7 * t7;
  const hk_real t9 = t1 * t1;
  const hk_real t10 = (t8 + t9);
  const hk_real t11 = hk_sqrt(t10);
  const hk_real t12 = HK_LIT(1.22);
  const hk_real t15 = (t1 + t12);
  const bool t16 = (t11 < t15);
  return t16;
}

HK_STATIC bool hk_check_mast_for_vertical_hashemi(void) {
  const hk_real t0 = HK_LIT(1.17);
  const hk_real t1 = HK_LIT(1.22);
  const hk_real t2 = HK_LIT(0.8);
  const hk_real t3 = (t1 * t2);
  const hk_real t4 = HK_LIT(3.36);
  const hk_real t5 = hk_sqrt(t4);
  const hk_real t6 = HK_LIT(1);
  const hk_real t7 = (t5 - t6);
  const hk_real t8 = (t3 / t7);
  const bool t9 = (t0 < t8);
  return t9;
}

HK_STATIC bool hk_check_one_turn_tilt(void) {
  const hk_real t0 = HK_LIT(0.0015);
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = HK_LIT(0.8);
  const hk_real t3 = (t1 * t2);
  const hk_real t4 = (t0 / t3);
  const hk_real t5 = HK_LIT(0.001);
  const bool t6 = (t4 < t5);
  const hk_real t7 = HK_LIT(4);
  const hk_real t8 = (t7 * t4);
  const hk_real t9 = HK_LIT(0.00465);
  const bool t10 = (t8 < t9);
  const hk_real t11 = HK_LIT(1);
  const hk_real t12 = (t11 * t4);
  const bool t13 = (t12 < t5);
  const bool t14 = (t10 && t13);
  const bool t15 = (t6 && t14);
  return t15;
}

HK_STATIC bool hk_check_panel_current(void) {
  const hk_real t0 = HK_LIT(5);
  const hk_real t1 = HK_LIT(12);
  const hk_real t2 = (t0 / t1);
  const hk_real t3 = HK_LIT(0.5);
  const bool t4 = (t2 < t3);
  return t4;
}

HK_STATIC bool hk_check_pulley_above_pivot(void) {
  const hk_real t0 = HK_LIT(1.59);
  const hk_real t3 = HK_LIT(1.30);
  const hk_real t8 = HK_LIT(0.05);
  const hk_real t9 = (t3 - t8);
  const hk_real t10 = (t0 - t9);
  const hk_real t11 = HK_LIT(0.34);
  const bool t12 = hk_eq(t10, t11);
  return t12;
}

HK_STATIC bool hk_check_receiverPost_height(void) {
  const hk_real t0 = HK_LIT(1.30);
  const hk_real t5 = HK_LIT(0.05);
  const hk_real t6 = (t0 - t5);
  const hk_real t7 = HK_LIT(1.25);
  const bool t8 = hk_eq(t6, t7);
  return t8;
}

HK_STATIC bool hk_check_rodTan_bounds(void) {
  const hk_real t0 = HK_LIT(0.507);
  const hk_real t1 = HK_LIT(0.4);
  const hk_real t2 = HK_LIT(3.2);
  const hk_real t3 = hk_sqrt(t2);
  const hk_real t4 = HK_LIT(1);
  const hk_real t5 = (t3 - t4);
  const hk_real t6 = (t1 / t5);
  const bool t7 = (t0 < t6);
  const hk_real t8 = HK_LIT(0.5072);
  const bool t9 = (t6 < t8);
  const bool t10 = (t7 && t9);
  return t10;
}

HK_STATIC bool hk_check_rollerRadius_hashemi(void) {
  const hk_real t0 = HK_LIT(1.84);
  const hk_real t1 = HK_LIT(0.80);
  const hk_real t6 = HK_LIT(2);
  const hk_real t7 = (t0 / t6);
  const hk_real t8 = t7 * t7;
  const hk_real t9 = t1 * t1;
  const hk_real t10 = (t8 + t9);
  const hk_real t11 = hk_sqrt(t10);
  const hk_real t12 = HK_LIT(1.4864);
  const hk_real t13 = hk_sqrt(t12);
  const bool t14 = hk_eq(t11, t13);
  return t14;
}

HK_STATIC bool hk_check_rollerRadius_hashemi_bounds(void) {
  const hk_real t0 = HK_LIT(1.219);
  const hk_real t1 = HK_LIT(1.84);
  const hk_real t2 = HK_LIT(0.80);
  const hk_real t7 = HK_LIT(2);
  const hk_real t8 = (t1 / t7);
  const hk_real t9 = t8 * t8;
  const hk_real t10 = t2 * t2;
  const hk_real t11 = (t9 + t10);
  const hk_real t12 = hk_sqrt(t11);
  const bool t13 = (t0 < t12);
  const hk_real t14 = HK_LIT(1.2195);
  const bool t15 = (t12 < t14);
  const bool t16 = (t13 && t15);
  return t16;
}

HK_STATIC bool hk_check_roller_rpm_hashemi(void) {
  const hk_real t0 = HK_LIT(0.13);
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = HK_LIT(360);
  const hk_real t3 = (t1 / t2);
  const hk_real t4 = HK_LIT(1.2192);
  const hk_real t5 = (t3 * t4);
  const hk_real t6 = HK_LIT(0.05);
  const hk_real t7 = (t5 / t6);
  const bool t8 = (t0 < t7);
  const hk_real t9 = HK_LIT(0.14);
  const bool t10 = (t7 < t9);
  const bool t11 = (t8 && t10);
  return t11;
}

HK_STATIC bool hk_check_screwLength_hashemi(void) {
  const hk_real t0 = HK_LIT(2);
  const hk_real t1 = (t0 / t0);
  const hk_real t2 = t0 * t0;
  const hk_real t3 = HK_LIT(1);
  const hk_real t4 = t3 * t3;
  const hk_real t5 = (t2 - t4);
  const hk_real t6 = hk_sqrt(t5);
  const hk_real t7 = (t0 - t6);
  const hk_real t8 = (t1 - t7);
  const hk_real t9 = HK_LIT(3);
  const hk_real t10 = hk_sqrt(t9);
  const hk_real t11 = (t10 - t3);
  const bool t12 = hk_eq(t8, t11);
  return t12;
}

HK_STATIC bool hk_check_screwLength_hashemi_bounds(void) {
  const hk_real t0 = HK_LIT(0.732);
  const hk_real t1 = HK_LIT(2);
  const hk_real t2 = (t1 / t1);
  const hk_real t3 = t1 * t1;
  const hk_real t4 = HK_LIT(1);
  const hk_real t5 = t4 * t4;
  const hk_real t6 = (t3 - t5);
  const hk_real t7 = hk_sqrt(t6);
  const hk_real t8 = (t1 - t7);
  const hk_real t9 = (t2 - t8);
  const bool t10 = (t0 < t9);
  const hk_real t11 = HK_LIT(0.7321);
  const bool t12 = (t9 < t11);
  const bool t13 = (t10 && t12);
  return t13;
}

HK_STATIC bool hk_check_shim_negligible(void) {
  const hk_real t0 = HK_LIT(0.0005);
  const hk_real t1 = HK_LIT(0.01);
  const hk_real t2 = HK_LIT(0.06);
  const hk_real t3 = (t1 * t2);
  const bool t4 = (t0 < t3);
  return t4;
}

HK_STATIC bool hk_check_sideGap_eq(void) {
  const hk_real t0 = HK_LIT(1.84);
  const hk_real t6 = HK_LIT(2);
  const hk_real t7 = HK_LIT(0.8);
  const hk_real t8 = (t6 * t7);
  const hk_real t9 = (t0 - t8);
  const hk_real t10 = (t9 / t6);
  const hk_real t11 = HK_LIT(0.12);
  const bool t12 = hk_eq(t10, t11);
  return t12;
}

HK_STATIC bool hk_check_sixty_reachable(void) {
  const hk_real t0 = HK_PI;
  const hk_real t1 = HK_LIT(3);
  const hk_real t2 = (t0 / t1);
  const hk_real t3 = hk_sin(t2);
  const hk_real t4 = HK_LIT(1.2);
  const hk_real t5 = HK_LIT(0.8);
  const hk_real t6 = (t4 * t5);
  const hk_real t7 = HK_LIT(0.34);
  const hk_real t8 = HK_LIT(3.36);
  const hk_real t9 = hk_sqrt(t8);
  const hk_real t10 = HK_LIT(1);
  const hk_real t11 = (t9 - t10);
  const hk_real t12 = (t7 * t11);
  const hk_real t13 = (t6 - t12);
  const hk_real t14 = (t3 * t13);
  const hk_real t15 = hk_cos(t2);
  const hk_real t16 = (t4 * t11);
  const hk_real t17 = (t7 * t5);
  const hk_real t18 = (t16 + t17);
  const hk_real t19 = (t15 * t18);
  const bool t20 = (t14 < t19);
  return t20;
}

HK_STATIC bool hk_check_slot_exit_hashemi(void) {
  const hk_real t0 = HK_LIT(0.960);
  const hk_real t1 = HK_LIT(0.8);
  const hk_real t2 = HK_LIT(3.36);
  const hk_real t3 = hk_sqrt(t2);
  const hk_real t4 = HK_LIT(1);
  const hk_real t5 = (t3 - t4);
  const hk_real t6 = (t1 / t5);
  const bool t7 = (t0 < t6);
  const hk_real t8 = HK_LIT(0.9605);
  const bool t9 = (t6 < t8);
  const bool t10 = (t7 && t9);
  return t10;
}

HK_STATIC bool hk_check_sqrt32_bounds(void) {
  const hk_real t0 = HK_LIT(1.7888);
  const hk_real t1 = HK_LIT(3.2);
  const hk_real t2 = hk_sqrt(t1);
  const bool t3 = (t0 < t2);
  const hk_real t4 = HK_LIT(1.78886);
  const bool t5 = (t2 < t4);
  const bool t6 = (t3 && t5);
  return t6;
}

HK_STATIC bool hk_check_wireLeft_at_ym(void) {
  const hk_real t0 = HK_LIT(0.111);
  const hk_real t1 = HK_LIT(1.22);
  const hk_real t2 = t1 * t1;
  const hk_real t3 = HK_LIT(0.34);
  const hk_real t4 = t3 * t3;
  const hk_real t5 = (t2 + t4);
  const hk_real t6 = hk_sqrt(t5);
  const hk_real t7 = HK_LIT(5);
  const hk_real t8 = HK_LIT(2);
  const hk_real t9 = HK_LIT(3.36);
  const hk_real t10 = hk_sqrt(t9);
  const hk_real t11 = (t8 * t10);
  const hk_real t12 = (t7 - t11);
  const hk_real t13 = hk_sqrt(t12);
  const hk_real t14 = (t6 - t13);
  const bool t15 = (t0 < t14);
  const hk_real t16 = HK_LIT(0.113);
  const bool t17 = (t14 < t16);
  const bool t18 = (t15 && t17);
  return t18;
}

HK_STATIC bool hk_check_wireLever_rest_at_ym(void) {
  const hk_real t0 = HK_LIT(1.033);
  const hk_real t1 = HK_LIT(1.22);
  const hk_real t2 = HK_LIT(3.36);
  const hk_real t3 = hk_sqrt(t2);
  const hk_real t4 = HK_LIT(1);
  const hk_real t5 = (t3 - t4);
  const hk_real t6 = (t1 * t5);
  const hk_real t7 = HK_LIT(0.34);
  const hk_real t8 = HK_LIT(0.8);
  const hk_real t9 = (t7 * t8);
  const hk_real t10 = (t6 + t9);
  const hk_real t11 = (t1 - t8);
  const hk_real t12 = t11 * t11;
  const hk_real t13 = (t7 + t5);
  const hk_real t14 = t13 * t13;
  const hk_real t15 = (t12 + t14);
  const hk_real t16 = hk_sqrt(t15);
  const hk_real t17 = (t10 / t16);
  const bool t18 = (t0 < t17);
  const hk_real t19 = HK_LIT(1.035);
  const bool t20 = (t17 < t19);
  const bool t21 = (t18 && t20);
  return t21;
}

HK_STATIC bool hk_check_wireLever_sixty_at_ym(void) {
  const hk_real t0 = HK_LIT(0.37);
  const hk_real t1 = HK_LIT(1.22);
  const hk_real t2 = (-t1);
  const hk_real t3 = HK_LIT(0.34);
  const hk_real t4 = HK_LIT(0.8);
  const hk_real t5 = (-t4);
  const hk_real t6 = HK_PI;
  const hk_real t7 = HK_LIT(3);
  const hk_real t8 = (t6 / t7);
  const hk_real t9 = hk_cos(t8);
  const hk_real t10 = (t5 * t9);
  const hk_real t11 = HK_LIT(3.36);
  const hk_real t12 = hk_sqrt(t11);
  const hk_real t13 = HK_LIT(1);
  const hk_real t14 = (t12 - t13);
  const hk_real t15 = (-t14);
  const hk_real t16 = hk_sin(t8);
  const hk_real t17 = (t15 * t16);
  const hk_real t18 = (t10 + t17);
  const hk_real t19 = (-t5);
  const hk_real t20 = (t19 * t16);
  const hk_real t21 = (t15 * t9);
  const hk_real t22 = (t20 + t21);
  const hk_real t23 = (t2 * t22);
  const hk_real t24 = (t3 * t18);
  const hk_real t25 = (t23 - t24);
  const hk_real t26 = (t18 - t2);
  const hk_real t27 = t26 * t26;
  const hk_real t28 = (t22 - t3);
  const hk_real t29 = t28 * t28;
  const hk_real t30 = (t27 + t29);
  const hk_real t31 = hk_sqrt(t30);
  const hk_real t32 = (t25 / t31);
  const bool t33 = (t0 < t32);
  const hk_real t34 = HK_LIT(0.38);
  const bool t35 = (t32 < t34);
  const bool t36 = (t33 && t35);
  return t36;
}

HK_STATIC bool hk_check_wire_short_of_vertical(void) {
  const hk_real t0 = HK_LIT(0.34);
  const hk_real t1 = HK_LIT(3.36);
  const hk_real t2 = hk_sqrt(t1);
  const hk_real t3 = HK_LIT(1);
  const hk_real t4 = (t2 - t3);
  const hk_real t5 = (t0 * t4);
  const hk_real t6 = HK_LIT(1.22);
  const hk_real t7 = HK_LIT(0.8);
  const hk_real t8 = (t6 * t7);
  const hk_real t9 = (t5 - t8);
  const hk_real t10 = HK_LIT(0);
  const bool t11 = (t9 < t10);
  return t11;
}

HK_STATIC bool hk_check_ym_is_standStation(void) {
  const hk_real t0 = HK_LIT(1.22);
  const bool t9 = hk_eq(t0, t0);
  return t9;
}

#endif