/* generated by RequestProject/CccScene.lean - do not edit. */
#ifndef SCENE_REGISTRY_H
#define SCENE_REGISTRY_H
#include "scene_hashemi.h"
#include "scene_beam.h"
#include "scene_optic.h"
typedef struct {
  const char *name;
  int n_in, n_static, n_ray, n_rays, n_entry;
  const int *kind, *colour, *off, *w, *ray;
  const char **label;
  const char **input;
  void (*eval)(const hk_real *, const hk_real *, hk_real *, hk_real *);
} hk_scene_t;
static const hk_scene_t HK_SCENES[] = {
  { "hashemi", SCENEHASHEMI_N_IN, SCENEHASHEMI_N_STATIC, SCENEHASHEMI_N_RAY, SCENEHASHEMI_P, SCENEHASHEMI_N_ENTRY, SCENEHASHEMI_KIND, SCENEHASHEMI_COLOUR, SCENEHASHEMI_OFF, SCENEHASHEMI_W, SCENEHASHEMI_RAY, SCENEHASHEMI_LABEL, SCENEHASHEMI_INPUT, hk_sceneHashemi_eval },
  { "beam", SCENEBEAM_N_IN, SCENEBEAM_N_STATIC, SCENEBEAM_N_RAY, SCENEBEAM_P, SCENEBEAM_N_ENTRY, SCENEBEAM_KIND, SCENEBEAM_COLOUR, SCENEBEAM_OFF, SCENEBEAM_W, SCENEBEAM_RAY, SCENEBEAM_LABEL, SCENEBEAM_INPUT, hk_sceneBeam_eval },
  { "optic", SCENEOPTIC_N_IN, SCENEOPTIC_N_STATIC, SCENEOPTIC_N_RAY, SCENEOPTIC_P, SCENEOPTIC_N_ENTRY, SCENEOPTIC_KIND, SCENEOPTIC_COLOUR, SCENEOPTIC_OFF, SCENEOPTIC_W, SCENEOPTIC_RAY, SCENEOPTIC_LABEL, SCENEOPTIC_INPUT, hk_sceneOptic_eval }
};
#define HK_N_SCENES 3
#endif