# generated by RequestProject/SceneCcc.lean - do not edit.
import numpy as np

def hk_eq(a, b):
    return np.abs(a - b) <= 1e-9 * np.maximum(1.0, np.maximum(np.abs(a), np.abs(b)))

def hk_sceneSunAt(lat, doy, hour):
    t0 = lat
    t1 = doy
    t2 = hour
    t3 = np.pi
    t4 = (t0 * t3)
    t5 = 180
    t6 = (t4 / t5)
    t7 = 23.44
    t8 = (t7 * t3)
    t9 = (t8 / t5)
    t10 = 2
    t11 = (t10 * t3)
    t12 = 284
    t13 = (t12 + t1)
    t14 = (t11 * t13)
    t15 = 365
    t16 = (t14 / t15)
    t17 = np.sin(t16)
    t18 = (t9 * t17)
    t19 = 15
    t20 = (t19 * t3)
    t21 = (t20 / t5)
    t22 = 12
    t23 = (t2 - t22)
    t24 = (t21 * t23)
    t25 = np.sin(t6)
    t26 = np.sin(t18)
    t27 = (t25 * t26)
    t28 = np.cos(t6)
    t29 = np.cos(t18)
    t30 = (t28 * t29)
    t31 = np.cos(t24)
    t32 = (t30 * t31)
    t33 = (t27 + t32)
    t34 = 1
    t35 = (-t34)
    t36 = np.minimum(t34, t33)
    t37 = np.maximum(t35, t36)
    t38 = np.arcsin(t37)
    t39 = (t33 * t25)
    t40 = (t26 - t39)
    t41 = np.cos(t38)
    t42 = (t41 * t28)
    t43 = 0.000000001
    t44 = np.maximum(t42, t43)
    t45 = (t40 / t44)
    t46 = np.minimum(t34, t45)
    t47 = np.maximum(t35, t46)
    t48 = np.arccos(t47)
    t49 = 0
    t50 = (t49 < t24)
    t51 = (t11 - t48)
    t52 = np.where(t50, t51, t48)
    return np.stack([np.broadcast_to(np.asarray(t38, dtype=float), np.broadcast(*[np.asarray(x) for x in [lat, doy, hour]]).shape), np.broadcast_to(np.asarray(t52, dtype=float), np.broadcast(*[np.asarray(x) for x in [lat, doy, hour]]).shape)], axis=-1)
