/* generated by RequestProject/CccScene.lean - do not edit.
   Every vertex below is a definition of the specification, composed with its frame IN THE
   GRAPH and printed by RequestProject/Ccc.lean.  No geometry is written here or in C. */
#ifndef SCENE_SUN_H
#define SCENE_SUN_H
#ifndef HK_NO_STD
#include <math.h>
#include <stdbool.h>
#endif
#ifndef HK_STATIC
#define HK_STATIC static inline
#endif
#ifndef HK_ADDR
#define HK_ADDR
#endif
#ifndef hk_real
#define hk_real double
#endif
#ifndef HK_LIT
#define HK_LIT(x) ((hk_real)(x))
#endif
#ifndef HK_PI
#define HK_PI HK_LIT(3.14159265358979323846)
#endif
#ifndef hk_sqrt
#define hk_sqrt(x) sqrt(hk_max((x), 0.0))
#define hk_sin sin
#define hk_cos cos
#define hk_tan tan
#define hk_atan atan
#define hk_acos(x) acos(hk_min(hk_max((x), -1.0), 1.0))
#define hk_asin(x) asin(hk_min(hk_max((x), -1.0), 1.0))
#define hk_exp exp
#define hk_log log
#define hk_fabs fabs
#define hk_floor floor
#define hk_tanh tanh
#define hk_min fmin
#define hk_max fmax
#endif
#ifndef hk_eq
#define hk_eq(a, b) (hk_fabs((a) - (b)) <= HK_LIT(1e-9) * hk_max(HK_LIT(1), hk_max(hk_fabs(a), hk_fabs(b))))
#endif
#ifndef hk_sigmoid
#define hk_sigmoid(x) (HK_LIT(1) / (HK_LIT(1) + hk_exp(-(x))))
#endif
#ifndef HK_RADDR
#define HK_RADDR
#endif

HK_STATIC void hk_sceneSunAt(hk_real lat, hk_real doy, hk_real hour, hk_real HK_ADDR* out) {
  const hk_real t0 = lat;
  const hk_real t1 = doy;
  const hk_real t2 = hour;
  const hk_real t3 = HK_PI;
  const hk_real t4 = (t0 * t3);
  const hk_real t5 = HK_LIT(180);
  const hk_real t6 = (t4 / t5);
  const hk_real t7 = HK_LIT(23.44);
  const hk_real t8 = (t7 * t3);
  const hk_real t9 = (t8 / t5);
  const hk_real t10 = HK_LIT(2);
  const hk_real t11 = (t10 * t3);
  const hk_real t12 = HK_LIT(284);
  const hk_real t13 = (t12 + t1);
  const hk_real t14 = (t11 * t13);
  const hk_real t15 = HK_LIT(365);
  const hk_real t16 = (t14 / t15);
  const hk_real t17 = hk_sin(t16);
  const hk_real t18 = (t9 * t17);
  const hk_real t19 = HK_LIT(15);
  const hk_real t20 = (t19 * t3);
  const hk_real t21 = (t20 / t5);
  const hk_real t22 = HK_LIT(12);
  const hk_real t23 = (t2 - t22);
  const hk_real t24 = (t21 * t23);
  const hk_real t25 = hk_sin(t6);
  const hk_real t26 = hk_sin(t18);
  const hk_real t27 = (t25 * t26);
  const hk_real t28 = hk_cos(t6);
  const hk_real t29 = hk_cos(t18);
  const hk_real t30 = (t28 * t29);
  const hk_real t31 = hk_cos(t24);
  const hk_real t32 = (t30 * t31);
  const hk_real t33 = (t27 + t32);
  const hk_real t34 = HK_LIT(1);
  const hk_real t35 = (-t34);
  const hk_real t36 = hk_min(t34, t33);
  const hk_real t37 = hk_max(t35, t36);
  const hk_real t38 = hk_asin(t37);
  const hk_real t39 = (t33 * t25);
  const hk_real t40 = (t26 - t39);
  const hk_real t41 = hk_cos(t38);
  const hk_real t42 = (t41 * t28);
  const hk_real t43 = HK_LIT(0.000000001);
  const hk_real t44 = hk_max(t42, t43);
  const hk_real t45 = (t40 / t44);
  const hk_real t46 = hk_min(t34, t45);
  const hk_real t47 = hk_max(t35, t46);
  const hk_real t48 = hk_acos(t47);
  const hk_real t49 = HK_LIT(0);
  const bool t50 = (t49 < t24);
  const hk_real t51 = (t11 - t48);
  const hk_real t52 = (t50 ? t51 : t48);
  out[0] = t38;
  out[1] = t52;
}
#endif