/* generated by RequestProject/CccScene.lean - do not edit.
   Every vertex below is a definition of the specification, composed with its frame IN THE
   GRAPH and printed by RequestProject/Ccc.lean.  No geometry is written here or in C. */
#ifndef SCENE_SCENEBEAM_H
#define SCENE_SCENEBEAM_H
#ifndef HK_NO_STD
#include <math.h>
#include <stdbool.h>
#endif
#ifndef HK_STATIC
#define HK_STATIC static inline
#endif
#ifndef HK_ADDR
#define HK_ADDR
#endif
#ifndef hk_real
#define hk_real double
#endif
#ifndef HK_LIT
#define HK_LIT(x) ((hk_real)(x))
#endif
#ifndef HK_PI
#define HK_PI HK_LIT(3.14159265358979323846)
#endif
#ifndef hk_sqrt
#define hk_sqrt sqrt
#define hk_sin sin
#define hk_cos cos
#define hk_tan tan
#define hk_atan atan
#define hk_acos acos
#define hk_asin asin
#define hk_exp exp
#define hk_log log
#define hk_fabs fabs
#define hk_floor floor
#define hk_tanh tanh
#define hk_min fmin
#define hk_max fmax
#endif
#ifndef hk_eq
#define hk_eq(a, b) (hk_fabs((a) - (b)) <= HK_LIT(1e-9) * hk_max(HK_LIT(1), hk_max(hk_fabs(a), hk_fabs(b))))
#endif
#ifndef hk_sigmoid
#define hk_sigmoid(x) (HK_LIT(1) / (HK_LIT(1) + hk_exp(-(x))))
#endif
#ifndef HK_RADDR
#define HK_RADDR
#endif

HK_STATIC void hk_sceneBeam(hk_real az, hk_real t, hk_real apexH, hk_real zBolt, hk_real f, hk_real beta, hk_real L, hk_real dm, hk_real H_0, hk_real H_1, hk_real H_2, hk_real r_0, hk_real r_1, hk_real r_2, hk_real R, hk_real a, hk_real k, hk_real rm, hk_real rt, hk_real slotW, hk_real onPanel, hk_real HK_ADDR* out) {
  const hk_real t0 = az;
  const hk_real t1 = t;
  const hk_real t2 = apexH;
  const hk_real t3 = zBolt;
  const hk_real t4 = f;
  const hk_real t5 = beta;
  const hk_real t6 = L;
  const hk_real t7 = dm;
  const hk_real t8 = H_0;
  const hk_real t9 = H_1;
  const hk_real t10 = H_2;
  const hk_real t11 = r_0;
  const hk_real t12 = r_1;
  const hk_real t13 = r_2;
  const hk_real t14 = R;
  const hk_real t15 = a;
  const hk_real t16 = k;
  const hk_real t17 = rm;
  const hk_real t18 = rt;
  const hk_real t19 = slotW;
  const hk_real t20 = onPanel;
  const hk_real t21 = hk_cos(t0);
  const hk_real t22 = HK_LIT(0);
  const hk_real t23 = hk_cos(t1);
  const hk_real t24 = (t22 * t23);
  const hk_real t25 = (-t4);
  const hk_real t26 = hk_sin(t1);
  const hk_real t27 = (t25 * t26);
  const hk_real t28 = (t24 + t27);
  const hk_real t29 = (-t22);
  const hk_real t30 = (t29 * t26);
  const hk_real t31 = (t25 * t23);
  const hk_real t32 = (t30 + t31);
  const hk_real t33 = (t2 + t28);
  const hk_real t34 = (t21 * t33);
  const hk_real t35 = hk_sin(t0);
  const hk_real t36 = (t35 * t22);
  const hk_real t37 = (t34 - t36);
  const hk_real t38 = (t35 * t33);
  const hk_real t39 = (t21 * t22);
  const hk_real t40 = (t38 + t39);
  const hk_real t41 = (t3 + t32);
  const hk_real t42 = (t1 + t5);
  const hk_real t43 = hk_sin(t42);
  const hk_real t44 = hk_cos(t42);
  const hk_real t45 = (-t44);
  const hk_real t46 = (t26 * t21);
  const hk_real t47 = (t26 * t35);
  const hk_real t48 = (t23 * t21);
  const hk_real t49 = (t23 * t35);
  const hk_real t50 = (-t26);
  const hk_real t51 = (t49 * t23);
  const hk_real t52 = (t50 * t47);
  const hk_real t53 = (t51 - t52);
  const hk_real t54 = (t50 * t46);
  const hk_real t55 = (t48 * t23);
  const hk_real t56 = (t54 - t55);
  const hk_real t57 = (t48 * t47);
  const hk_real t58 = (t49 * t46);
  const hk_real t59 = (t57 - t58);
  const hk_real t60 = (t43 * t53);
  const hk_real t61 = (t22 * t48);
  const hk_real t62 = (t60 + t61);
  const hk_real t63 = (t45 * t46);
  const hk_real t64 = (t62 + t63);
  const hk_real t65 = (t37 + t64);
  const hk_real t66 = (t43 * t56);
  const hk_real t67 = (t22 * t49);
  const hk_real t68 = (t66 + t67);
  const hk_real t69 = (t45 * t47);
  const hk_real t70 = (t68 + t69);
  const hk_real t71 = (t40 + t70);
  const hk_real t72 = (t43 * t59);
  const hk_real t73 = (t22 * t50);
  const hk_real t74 = (t72 + t73);
  const hk_real t75 = (t45 * t23);
  const hk_real t76 = (t74 + t75);
  const hk_real t77 = (t41 + t76);
  const hk_real t78 = HK_LIT(2);
  const hk_real t79 = (t6 / t78);
  const hk_real t80 = (t79 - t7);
  const hk_real t81 = t79 * t79;
  const hk_real t82 = t80 * t80;
  const hk_real t83 = (t81 - t82);
  const hk_real t84 = (t43 * t79);
  const hk_real t85 = (t22 * t79);
  const hk_real t86 = (t45 * t79);
  const hk_real t87 = (t4 + t86);
  const hk_real t88 = (t8 - t84);
  const hk_real t89 = (t9 - t85);
  const hk_real t90 = (t10 - t87);
  const hk_real t91 = (t88 * t43);
  const hk_real t92 = (t89 * t22);
  const hk_real t93 = (t91 + t92);
  const hk_real t94 = (t90 * t45);
  const hk_real t95 = (t93 + t94);
  const hk_real t96 = (-t95);
  const hk_real t97 = (t11 * t43);
  const hk_real t98 = (t12 * t22);
  const hk_real t99 = (t97 + t98);
  const hk_real t100 = (t13 * t45);
  const hk_real t101 = (t99 + t100);
  const hk_real t102 = (-t101);
  const hk_real t103 = HK_LIT(1);
  const hk_real t104 = (t103 / t82);
  const hk_real t105 = (t103 / t83);
  const hk_real t106 = (t104 + t105);
  const hk_real t107 = t102 * t102;
  const hk_real t108 = (t107 * t106);
  const hk_real t109 = (t11 * t11);
  const hk_real t110 = (t12 * t12);
  const hk_real t111 = (t109 + t110);
  const hk_real t112 = (t13 * t13);
  const hk_real t113 = (t111 + t112);
  const hk_real t114 = (t113 / t83);
  const hk_real t115 = (t108 - t114);
  const hk_real t116 = (t78 * t96);
  const hk_real t117 = (t116 * t102);
  const hk_real t118 = (t117 * t106);
  const hk_real t119 = (t88 * t11);
  const hk_real t120 = (t89 * t12);
  const hk_real t121 = (t119 + t120);
  const hk_real t122 = (t90 * t13);
  const hk_real t123 = (t121 + t122);
  const hk_real t124 = (t78 * t123);
  const hk_real t125 = (t124 / t83);
  const hk_real t126 = (t118 - t125);
  const hk_real t127 = t96 * t96;
  const hk_real t128 = (t127 * t106);
  const hk_real t129 = (t88 * t88);
  const hk_real t130 = (t89 * t89);
  const hk_real t131 = (t129 + t130);
  const hk_real t132 = (t90 * t90);
  const hk_real t133 = (t131 + t132);
  const hk_real t134 = (t133 / t83);
  const hk_real t135 = (t128 - t134);
  const hk_real t136 = (t135 - t103);
  const hk_real t137 = t126 * t126;
  const hk_real t138 = HK_LIT(4);
  const hk_real t139 = (t138 * t115);
  const hk_real t140 = (t139 * t136);
  const hk_real t141 = (t137 - t140);
  const hk_real t142 = hk_max(t141, t22);
  const hk_real t143 = hk_sqrt(t142);
  const hk_real t144 = (-t126);
  const hk_real t145 = (t144 - t143);
  const hk_real t146 = (t78 * t115);
  const hk_real t147 = (t145 / t146);
  const hk_real t148 = (t144 + t143);
  const hk_real t149 = (t148 / t146);
  const hk_real t150 = HK_LIT(0.000001);
  const bool t151 = (t147 > t150);
  const hk_real t152 = (t147 * t102);
  const hk_real t153 = (t96 + t152);
  const bool t154 = (t153 > t22);
  const bool t155 = (t151 && t154);
  const bool t156 = (t149 > t150);
  const hk_real t157 = (t149 * t102);
  const hk_real t158 = (t96 + t157);
  const bool t159 = (t158 > t22);
  const bool t160 = (t156 && t159);
  const bool t161 = (t155 && t160);
  const hk_real t162 = hk_min(t147, t149);
  const hk_real t163 = (-t103);
  const hk_real t164 = (t160 ? t149 : t163);
  const hk_real t165 = (t155 ? t147 : t164);
  const hk_real t166 = (t161 ? t162 : t165);
  const hk_real t167 = (t166 * t11);
  const hk_real t168 = (t8 + t167);
  const hk_real t169 = (t166 * t12);
  const hk_real t170 = (t9 + t169);
  const hk_real t171 = (t166 * t13);
  const hk_real t172 = (t10 + t171);
  const hk_real t173 = (t166 * t102);
  const hk_real t174 = (t96 + t173);
  const hk_real t175 = (t168 - t84);
  const hk_real t176 = (t174 * t43);
  const hk_real t177 = (t175 + t176);
  const hk_real t178 = (t170 - t85);
  const hk_real t179 = (t174 * t22);
  const hk_real t180 = (t178 + t179);
  const hk_real t181 = (t172 - t87);
  const hk_real t182 = (t174 * t45);
  const hk_real t183 = (t181 + t182);
  const hk_real t184 = (t177 * t177);
  const hk_real t185 = (t180 * t180);
  const hk_real t186 = (t184 + t185);
  const hk_real t187 = (t183 * t183);
  const hk_real t188 = (t186 + t187);
  const hk_real t189 = HK_LIT(0.000000000000000001);
  const hk_real t190 = hk_max(t188, t189);
  const hk_real t191 = hk_sqrt(t190);
  const hk_real t192 = (t174 / t82);
  const hk_real t193 = (-t192);
  const hk_real t194 = (t193 * t43);
  const hk_real t195 = (t177 / t83);
  const hk_real t196 = (t194 - t195);
  const hk_real t197 = (t193 * t22);
  const hk_real t198 = (t180 / t83);
  const hk_real t199 = (t197 - t198);
  const hk_real t200 = (t193 * t45);
  const hk_real t201 = (t183 / t83);
  const hk_real t202 = (t200 - t201);
  const hk_real t203 = (t196 * t196);
  const hk_real t204 = (t199 * t199);
  const hk_real t205 = (t203 + t204);
  const hk_real t206 = (t202 * t202);
  const hk_real t207 = (t205 + t206);
  const hk_real t208 = hk_max(t207, t189);
  const hk_real t209 = hk_sqrt(t208);
  const hk_real t210 = (t196 / t209);
  const hk_real t211 = (t199 / t209);
  const hk_real t212 = (t202 / t209);
  const hk_real t213 = (t168 * t53);
  const hk_real t214 = (t170 * t48);
  const hk_real t215 = (t213 + t214);
  const hk_real t216 = (t172 * t46);
  const hk_real t217 = (t215 + t216);
  const hk_real t218 = (t37 + t217);
  const hk_real t219 = (t168 * t56);
  const hk_real t220 = (t170 * t49);
  const hk_real t221 = (t219 + t220);
  const hk_real t222 = (t172 * t47);
  const hk_real t223 = (t221 + t222);
  const hk_real t224 = (t40 + t223);
  const hk_real t225 = (t168 * t59);
  const hk_real t226 = (t170 * t50);
  const hk_real t227 = (t225 + t226);
  const hk_real t228 = (t172 * t23);
  const hk_real t229 = (t227 + t228);
  const hk_real t230 = (t41 + t229);
  const hk_real t231 = (t8 * t53);
  const hk_real t232 = (t9 * t48);
  const hk_real t233 = (t231 + t232);
  const hk_real t234 = (t10 * t46);
  const hk_real t235 = (t233 + t234);
  const hk_real t236 = (t37 + t235);
  const hk_real t237 = (t8 * t56);
  const hk_real t238 = (t9 * t49);
  const hk_real t239 = (t237 + t238);
  const hk_real t240 = (t10 * t47);
  const hk_real t241 = (t239 + t240);
  const hk_real t242 = (t40 + t241);
  const hk_real t243 = (t8 * t59);
  const hk_real t244 = (t9 * t50);
  const hk_real t245 = (t243 + t244);
  const hk_real t246 = (t10 * t23);
  const hk_real t247 = (t245 + t246);
  const hk_real t248 = (t41 + t247);
  const hk_real t249 = (t210 * t53);
  const hk_real t250 = (t211 * t48);
  const hk_real t251 = (t249 + t250);
  const hk_real t252 = (t212 * t46);
  const hk_real t253 = (t251 + t252);
  const hk_real t254 = (t37 + t253);
  const hk_real t255 = (t210 * t56);
  const hk_real t256 = (t211 * t49);
  const hk_real t257 = (t255 + t256);
  const hk_real t258 = (t212 * t47);
  const hk_real t259 = (t257 + t258);
  const hk_real t260 = (t40 + t259);
  const hk_real t261 = (t210 * t59);
  const hk_real t262 = (t211 * t50);
  const hk_real t263 = (t261 + t262);
  const hk_real t264 = (t212 * t23);
  const hk_real t265 = (t263 + t264);
  const hk_real t266 = (t41 + t265);
  const hk_real t267 = HK_LIT(0.5);
  const bool t268 = (t20 > t267);
  const bool t269 = (t166 > t22);
  const bool t270 = (t191 <= t17);
  const bool t271 = (t269 && t270);
  const bool t272 = (t268 && t271);
  const hk_real t273 = (t11 * t210);
  const hk_real t274 = (t12 * t211);
  const hk_real t275 = (t273 + t274);
  const hk_real t276 = (t13 * t212);
  const hk_real t277 = (t275 + t276);
  const hk_real t278 = (t78 * t277);
  const hk_real t279 = (t278 * t210);
  const hk_real t280 = (t11 - t279);
  const hk_real t281 = (t278 * t211);
  const hk_real t282 = (t12 - t281);
  const hk_real t283 = (t278 * t212);
  const hk_real t284 = (t13 - t283);
  const hk_real t285 = (t103 + t16);
  const hk_real t286 = (t103 / t14);
  const hk_real t287 = t280 * t280;
  const hk_real t288 = t282 * t282;
  const hk_real t289 = (t287 + t288);
  const hk_real t290 = t284 * t284;
  const hk_real t291 = (t285 * t290);
  const hk_real t292 = (t289 + t291);
  const hk_real t293 = (t286 * t292);
  const hk_real t294 = (t78 * t286);
  const hk_real t295 = (t168 * t280);
  const hk_real t296 = (t170 * t282);
  const hk_real t297 = (t295 + t296);
  const hk_real t298 = (t285 * t172);
  const hk_real t299 = (t298 * t284);
  const hk_real t300 = (t297 + t299);
  const hk_real t301 = (t294 * t300);
  const hk_real t302 = (t78 * t284);
  const hk_real t303 = (t301 - t302);
  const hk_real t304 = t168 * t168;
  const hk_real t305 = t170 * t170;
  const hk_real t306 = (t304 + t305);
  const hk_real t307 = t172 * t172;
  const hk_real t308 = (t285 * t307);
  const hk_real t309 = (t306 + t308);
  const hk_real t310 = (t286 * t309);
  const hk_real t311 = (t78 * t172);
  const hk_real t312 = (t310 - t311);
  const hk_real t313 = (t78 * t312);
  const hk_real t314 = (-t303);
  const hk_real t315 = t303 * t303;
  const hk_real t316 = (t138 * t293);
  const hk_real t317 = (t316 * t312);
  const hk_real t318 = (t315 - t317);
  const hk_real t319 = hk_max(t318, t22);
  const hk_real t320 = hk_sqrt(t319);
  const hk_real t321 = (t314 - t320);
  const hk_real t322 = (t313 / t321);
  const hk_real t323 = (t322 * t280);
  const hk_real t324 = (t168 + t323);
  const hk_real t325 = (t322 * t282);
  const hk_real t326 = (t170 + t325);
  const hk_real t329 = hk_fabs(t324);
  const bool t330 = (t329 <= t15);
  const hk_real t331 = hk_fabs(t326);
  const bool t332 = (t331 <= t15);
  const bool t333 = (t330 && t332);
  const hk_real t334 = (t19 / t78);
  const bool t335 = (t331 <= t334);
  const bool t336 = (t324 >= t22);
  const bool t337 = (t335 && t336);
  const bool t338 = (t322 > t22);
  const bool t339 = (!t333);
  const bool t340 = (t339 || t337);
  const bool t341 = (!t338 || t340);
  const hk_real t342 = (t43 * t6);
  const hk_real t343 = (t22 * t6);
  const hk_real t344 = (t45 * t6);
  const hk_real t345 = (t4 + t344);
  const hk_real t346 = (t342 - t168);
  const hk_real t347 = (t346 * t43);
  const hk_real t348 = (t343 - t170);
  const hk_real t349 = (t348 * t22);
  const hk_real t350 = (t347 + t349);
  const hk_real t351 = (t345 - t172);
  const hk_real t352 = (t351 * t45);
  const hk_real t353 = (t350 + t352);
  const hk_real t354 = (t280 * t43);
  const hk_real t355 = (t282 * t22);
  const hk_real t356 = (t354 + t355);
  const hk_real t357 = (t284 * t45);
  const hk_real t358 = (t356 + t357);
  const hk_real t359 = (t353 / t358);
  const hk_real t360 = (t359 * t280);
  const hk_real t361 = (t168 + t360);
  const hk_real t362 = (t359 * t282);
  const hk_real t363 = (t170 + t362);
  const hk_real t364 = (t359 * t284);
  const hk_real t365 = (t172 + t364);
  const hk_real t366 = (t361 - t342);
  const hk_real t367 = t366 * t366;
  const hk_real t368 = (t363 - t343);
  const hk_real t369 = t368 * t368;
  const hk_real t370 = (t367 + t369);
  const hk_real t371 = (t365 - t345);
  const hk_real t372 = t371 * t371;
  const hk_real t373 = (t370 + t372);
  const hk_real t374 = hk_sqrt(t373);
  const bool t375 = (t374 <= t18);
  const bool t376 = (t359 > t22);
  const bool t377 = (t375 && t376);
  const bool t378 = (t341 && t377);
  const bool t379 = (t272 && t378);
  const hk_real t380 = (t379 ? t103 : t22);
  const hk_real t381 = (t272 ? t103 : t22);
  const bool t384 = (!t272);
  const bool t385 = (!t341);
  const bool t386 = (!t377);
  const hk_real t387 = HK_LIT(3);
  const hk_real t388 = (t386 ? t78 : t387);
  const hk_real t389 = (t385 ? t103 : t388);
  const hk_real t390 = (t384 ? t22 : t389);
  out[0] = t65;
  out[1] = t71;
  out[2] = t77;
  out[3] = t218;
  out[4] = t224;
  out[5] = t230;
  out[6] = t236;
  out[7] = t242;
  out[8] = t248;
  out[9] = t218;
  out[10] = t224;
  out[11] = t230;
  out[12] = t254;
  out[13] = t260;
  out[14] = t266;
  out[15] = t380;
  out[16] = t381;
  out[17] = t374;
  out[18] = t324;
  out[19] = t326;
  out[20] = t191;
  out[21] = t390;
}

HK_STATIC void hk_sceneBeam_eval(const hk_real *in, hk_real *verts) {
  hk_sceneBeam(in[0], in[1], in[2], in[3], in[4], in[5], in[6], in[7], in[8], in[9], in[10], in[11], in[12], in[13], in[14], in[15], in[16], in[17], in[18], in[19], in[20], verts);
}
#define SCENEBEAM_N_IN 21
#define SCENEBEAM_N_VERT 22
#define SCENEBEAM_N_ENTRY 11
static const char *SCENEBEAM_INPUT[] = {"az", "t", "apexH", "zBolt", "f", "beta", "L", "dm", "H_0", "H_1", "H_2", "r_0", "r_1", "r_2", "R", "a", "k", "rm", "rt", "slotW", "onPanel"};
static const char *SCENEBEAM_LABEL[] = {"beam_axis", "secondary_hit", "beam_leg", "secondary_normal", "captured", "hit_secondary", "spill", "crossing_x", "crossing_y", "radius_on_secondary", "fate"};
static const int SCENEBEAM_KIND[] = {0, 0, 1, 0, 4, 4, 4, 4, 4, 4, 4};
static const int SCENEBEAM_COLOUR[] = {1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 6};
static const int SCENEBEAM_OFF[] = {0, 3, 6, 12, 15, 16, 17, 18, 19, 20, 21};
static const int SCENEBEAM_W[] = {3, 3, 6, 3, 1, 1, 1, 1, 1, 1, 1};
#endif